/* ============================================================
 * i18n.js — 라이딩 분석 대시보드 한↔영 토글 (Danny 2026-05-25)
 *
 * 아키텍처
 *  · 소스-텍스트-키 (source-as-key) 방식 — 한국어 원문을 키로 영어 매핑.
 *    호출부에서 RDI18n.T('한국어 텍스트') 또는 T('한국어 {n}개', {n:5}) 사용.
 *  · DOM 자동 번역 — 렌더 후 텍스트노드/속성을 walk 해 사전과 매칭되는
 *    한국어를 영어로 치환. 호출부 수정 없이 정적 HTML·동적 innerHTML
 *    모두 자동 처리. 원문은 _rdOrig 에 보존해 ko 로 토글 시 복원.
 *  · MutationObserver — 렌더로 새로 들어온 노드를 자동 번역.
 *  · 캔버스 텍스트(Chart.js·custom canvas) — DOM walk 가 닿지 않아
 *    호출부에서 T() 래핑 필요. lang 변경 시 RDDashboard 가 renderDashboard
 *    재호출 → 차트 재생성 → T() 가 'en' 분기 반환.
 *  · localStorage 키 = dmj_rd_lang ('ko'|'en'). 기본 'ko'.
 *  · 토글 버튼 = data-rd-lang-btn="ko|en" 속성. setupToggle 자동 결선.
 * ============================================================ */
(function (global) {
  'use strict';

  var STORE_KEY = 'dmj_rd_lang';

  /* ============================================================
   * 한↔영 사전 — source(ko) → target(en)
   * 키는 한국어 원문 그대로(공백·구두점 포함). 동적 보간은 {name} 토큰.
   * 추가 시 알파벳 순서 무관 — JS 객체 키 직접 조회(O(1)).
   * ============================================================ */
  var MAP = {
    /* ---------------- 페이지 메타 / 헤더 ---------------- */
    '라이딩 통계 대시보드 — GPX 분석 (Phase 1)':
      'Riding Stats Dashboard — GPX Analysis (Phase 1)',
    '윙포일·세일링 GPX 트랙 분석 — 속도·택킹/자이빙 효율·VMG·TWA 폴라. 코치 등급 분석.':
      'Wingfoil / sailing GPX track analysis — speed, tacking & gybing efficiency, VMG, TWA polar. Coach-grade analysis.',

    /* ---------------- 인트로 화면 ---------------- */
    'GPX 파일 하나로 라이딩을 분석합니다':
      'Analyze your riding from a single GPX file',
    '택킹·자이빙 효율, VMG, TWA 폴라':
      'tacking & gybing efficiency, VMG, TWA polar',
    '1. 스포츠 선택': '1. Choose your sport',
    '스포츠 종류': 'Sport',
    '2. GPX · VKX 파일 업로드': '2. Upload GPX or VKX file',
    'GPX 또는 VKX 파일을 끌어다 놓거나 선택':
      'Drop a GPX or VKX file here, or click to select',
    'GPX 또는 VKX 파일을 여기에 끌어다 놓으세요':
      'Drop your GPX or VKX file here',
    '또는 클릭해서 파일 선택 · .gpx · .vkx (Vakaros Atlas 2)':
      'Or click to select · .gpx · .vkx (Vakaros Atlas 2)',
    '샘플 데이터로 둘러보기 →': 'Browse with sample data →',
    '처음이라면 샘플로 먼저 살펴보세요':
      'New here? Try the sample first',
    '워치·앱에서 GPX 파일 내보내는 법':
      'How to export GPX from your watch / app',
    '분석은 모두 브라우저 안에서 처리되며, 파일은 어디에도 업로드되지 않습니다.':
      'All analysis runs in your browser — files are never uploaded.',
    '속도 시계열·분포·2초/10초/500m/1해리 베스트·고속 구간':
      'Speed time series · distribution · 2s/10s/500m/1NM bests · high-speed runs',
    '택킹·자이빙 자동 감지 + 진입/최저/탈출 속도·손실·회복':
      'Auto-detected tacks / gybes with entry / min / exit speed, loss & recovery',
    '코치 분석': 'Coach Analysis',
    'VMG·TWA 폴라·풍향 추정 — 풍향만 입력하면 열립니다':
      'VMG · TWA polar · wind estimation — unlocks once you set the wind',

    /* ---------------- 세션 헤더 ---------------- */
    '세션 제목 — 클릭하면 편집합니다':
      'Session title — click to edit',
    '클릭하면 세션 제목을 편집합니다':
      'Click to edit the session title',
    '라이딩 세션': 'Riding session',
    '세션 제목 편집': 'Edit session title',
    '세션 제목 입력': 'Session title',
    '편집본': 'Edited',
    '스포츠:': 'Sport:',
    '새 파일': 'New file',
    '이 세션 저장': 'Save session',

    /* ---------------- PDF 보고서 (Danny 2026-05-26) ---------------- */
    '📄 PDF 보고서': '📄 PDF Report',
    '📤 PDF 공유': '📤 Share PDF',
    'PDF 보고서 다운로드': 'Download PDF report',
    'PDF 보고서 공유': 'Share PDF report',
    '생성 중…': 'Generating…',
    'PDF 보고서 생성 중…': 'Generating PDF report…',
    'PDF 다운로드 완료': 'PDF downloaded',
    'PDF 공유 완료': 'PDF shared',
    'PDF 공유 취소': 'PDF share canceled',
    'PDF 생성 실패': 'PDF generation failed',
    'PDF 보고서는 세션이 로드되었을 때만 생성할 수 있습니다':
      'A session must be loaded to generate a PDF report',
    '라이딩 분석 보고서': 'Riding Analysis Report',
    '단무지공방 라이딩 분석 보고서': 'DMJ Gongbang Riding Analysis Report',
    '윙포일·세일링 GPX 트랙 분석': 'Wingfoil / sailing GPX track analysis',
    '단무지공방': 'DMJ Gongbang',
    '세션': 'Session',
    '일자': 'Date',
    '스포츠': 'Sport',
    '데이터': 'Data',
    '풍향·풍속': 'Wind dir · speed',
    '라이더 · 장비': 'Rider · Gear',
    '생성 시각': 'Generated',
    '이 보고서는 단무지공방 라이딩 분석 대시보드로 생성되었습니다':
      'Report generated by the DMJ Gongbang Riding Analysis Dashboard',
    '{n}쪽': 'p.{n}',
    '세션 요약': 'Session Summary',
    '풍상': 'Upwind',
    '종합': 'Overall',
    '풍하': 'Downwind',
    '세션 통계': 'Session Stats',
    '퍼포먼스 통계': 'Performance Stats',
    '지표': 'Metric',
    '값': 'Value',
    'GPS 트랙': 'GPS Track',
    '색상 = 속도(빨강 느림·초록 빠름) · 마커 = 택킹/자이빙':
      'Color = speed (red slow · green fast) · markers = tacks/gybes',
    '지도 캡쳐를 사용할 수 없습니다 (CORS 제한). 대시보드에서 확인하세요.':
      'Map capture unavailable (CORS). Please view on the dashboard.',
    '풍향 설정': 'Wind setting',
    '풍향 미설정': 'Wind not set',
    '속도 분석': 'Speed Analysis',
    '속도 시계열': 'Speed time series',
    '세션 전체 속도 · 색상은 속도 구간을 반영':
      'Full-session speed · colored by speed range',
    '속도 분포': 'Speed distribution',
    '속도 구간별 체류 시간 비율': 'Time-share by speed range',
    '차트 데이터 없음': 'No chart data',
    '고속 구간 (Run)': 'High-speed Runs',
    '회전 분석': 'Maneuver Analysis',
    '택킹 / 자이빙 요약': 'Tacks / Gybes summary',
    '폴라 다이어그램': 'Polar diagram',
    '이번 세션 포트·스타보드(실선) + 개인 베스트 타깃(점선)':
      'This session Port·Starboard (solid) + Personal best target (dashed)',
    '택 분포 — 포트 · 스타보드': 'Tack distribution — Port · Starboard',
    '가운데 축 기준 좌 = 포트(P) · 우 = 스타보드(S)':
      'Center axis: left = Port (P) · right = Starboard (S)',
    '심박 분석': 'Heart Rate Analysis',
    '세션 중 심박 추이': 'In-session HR trend',
    '배경 띠 = 심박 존': 'Background bands = HR zones',
    '심박 존 분포': 'HR zone distribution',
    '각 심박 존에 머문 시간': 'Time spent in each HR zone',
    '퍼포먼스 대비 심박 효율': 'HR efficiency vs performance',
    '같은 속도를 더 낮은 심박으로 — 유산소 효율':
      'Same speed at lower HR — aerobic efficiency',
    'Coach Danny 코멘트': 'Coach Danny Comments',
    'Coach Danny 코멘트가 아직 생성되지 않았습니다 (풍향을 확정하면 활성화됩니다)':
      'Coach Danny comments not yet generated (activates after wind is confirmed)',
    'What-if 윙 추천': 'What-if Wing Recommendation',
    '윙 사이즈 추천': 'Wing size recommendation',
    'VMG 기반 윙 사이즈 추천은 풍향·풍속·라이더 입력이 모두 확정되면 활성화됩니다.':
      'VMG-based wing size recommendation activates when wind direction, speed and rider inputs are all set.',
    '대시보드의 라이더·장비 카드와 풍향 설정 카드를 확인해 주세요.':
      'Please check the Rider · Gear card and Wind Setting card on the dashboard.',
    '부록 · 방법론': 'Appendix · Methodology',
    '알고리즘 방법론': 'Algorithm methodology',
    '속도·VMG·TWA·택킹/자이빙 자동 감지는 GPX trkpt 의 시각·좌표 데이터를 Haversine 거리·시간 차분으로 계산합니다. 풍향은 (1) 사용자 입력 (2) no-go 구간 추정 (3) 회전 기하 추정 (4) 외부 기상 데이터 중 사용자가 확정한 소스를 기준으로 사용합니다.':
      'Speed, VMG, TWA and tack/gybe auto-detection compute from GPX trkpt time/coordinate data via Haversine distance and time differentials. Wind direction uses one of: (1) manual input, (2) no-go segment estimation, (3) turn geometry estimation, or (4) external weather data — whichever source the user has confirmed.',
    '데이터 소스': 'Data sources',
    'GPX 1.1 (xmlns="http://www.topografix.com/GPX/1/1") · Vakaros Atlas 2 .vkx 바이너리 포맷. 모든 분석은 브라우저 안에서 처리되며 파일은 서버로 업로드되지 않습니다.':
      'GPX 1.1 (xmlns="http://www.topografix.com/GPX/1/1") and Vakaros Atlas 2 .vkx binary format. All analysis runs in the browser — files are never uploaded to a server.',
    '점수 체계': 'Scoring system',
    '세일링 퍼포먼스 스코어(VPS)는 풍상·풍하·종합 3축으로 라이더의 스킬·장비 대비 실제 트랙 효율을 비교합니다. 절대 등급이 아니라 개인 베스트 대비 상대 점수입니다.':
      'The Sailing Performance Score (VPS) compares actual track efficiency to rider skill / gear on three axes — upwind, downwind, overall. It is a personal-best-relative score, not an absolute grade.',
    '한계': 'Limitations',
    '이 보고서는 클라이언트 사이드 자동 분석 결과입니다. 코칭은 보조 도구로 활용하시고 안전·기술 판단은 라이더 본인 또는 자격 코치의 판단을 우선해 주세요.':
      'This report is the result of automated client-side analysis. Use the coaching as a supplement — for safety and technique decisions, always rely on the rider or a qualified coach.',
    '© 단무지공방 / SailTech. 본 보고서는 dmjgroup.kr 라이딩 분석 대시보드로 자동 생성되었습니다.':
      '© DMJ Gongbang / SailTech. This report was auto-generated by the dmjgroup.kr Riding Analysis Dashboard.',

    /* ---------------- 섹션 헤딩 ---------------- */
    '요약': 'Summary',
    '분석 1': 'Analysis 1',
    '분석 2': 'Analysis 2',
    '분석 3': 'Analysis 3',
    '코칭': 'Coaching',
    '기록': 'History',
    '🧭 세션 요약 · 세일링 퍼포먼스 스코어':
      '🧭 Session Summary · Sailing Performance Score',
    '📊 Speed Analysis · 속도 분석':
      '📊 Speed Analysis',
    '🔄 Maneuver Analysis · 회전(택킹·자이빙) 분석':
      '🔄 Maneuver Analysis (Tacking · Gybing)',
    '❤️ Heart Rate Analysis · 심박수 분석':
      '❤️ Heart Rate Analysis',
    '💬 Coach Danny 코멘트 · 장비 코칭':
      '💬 Coach Danny · Gear Coaching',
    '📈 저장된 세션 · 시즌 흐름':
      '📈 Saved Sessions · Season Trend',

    /* ---------------- 라이더·장비 ---------------- */
    '라이더 · 장비': 'Rider · Gear',
    '세일링 퍼포먼스 스코어·Coach Danny 분석에 사용 · 이 브라우저에 저장됩니다':
      'Used by Sailing Performance Score and Coach Danny · stored in this browser',
    '체중 (kg)': 'Weight (kg)',
    '예: 75': 'e.g. 75',
    '스킬 등급': 'Skill level',
    '윙 사이즈 (m²)': 'Wing size (m²)',
    '예: 6.0': 'e.g. 6.0',
    '프론트 윙 AR (선택)': 'Front-wing AR (optional)',
    '기본 6.5': 'Default 6.5',

    /* ---------------- 풍향 설정 ---------------- */
    '풍향 설정': 'Wind direction',
    '확정하면 택킹/자이빙 분류 · VMG · 폴라가 갱신됩니다':
      'Confirming updates tack / gybe classification, VMG and polar',
    '풍향 다이얼': 'Wind dial',
    '풍향 미설정': 'Wind not set',
    '빨간 바늘 = 바람이 불어오는 방향 · 다이얼 클릭/슬라이더로 조정':
      'Red needle = where the wind is coming FROM · click the dial or use the slider',
    '풍향 (°)': 'Wind direction (°)',
    '예: 205': 'e.g. 205',
    '풍속 (선택, kt)': 'Wind speed (optional, kt)',
    '예: 18': 'e.g. 18',
    '✦ 트랙으로 추정': '✦ Estimate from track',
    '초기화': 'Reset',
    '✓ 이 풍향으로 확정': '✓ Confirm wind',

    /* ---------------- 트랙 편집 ---------------- */
    '트랙 편집': 'Track editor',
    '원본 전체': 'Full track',
    'X축 시간 표기': 'X-axis time format',
    '경과 시간': 'Elapsed',
    '실제 시간': 'Clock time',
    '원본 복원': 'Restore original',
    '⧉ 편집본 복사 저장': '⧉ Save edited copy',

    /* ---------------- 지도 ---------------- */
    'GPS 트랙': 'GPS Track',
    '색상 = 속도(빨강 느림·초록 빠름) · 마커 = 택킹/자이빙':
      'Color = speed (red slow · green fast) · markers = tacks / gybes',
    '▶ 라이딩 리플레이': '▶ Riding Replay',
    '⛶ 전체화면': '⛶ Fullscreen',
    'GPS 트랙 — 전체화면 · 지도/그래프 hover 로 위치 확인':
      'GPS Track — fullscreen · hover the map or graph to locate',
    '✕ 닫기 (ESC)': '✕ Close (ESC)',

    /* ---------------- 퍼포먼스 통계 ---------------- */
    '퍼포먼스 통계': 'Performance Stats',
    '핵심 지표의 평균 · 대표 최댓값 · 대표 최솟값':
      'Key metrics — average · representative max · representative min',
    '오늘의 세션 속도 (노트)': 'Today’s session speed (knots)',
    '구간별 베스트 속도': 'Best speed by distance / window',
    '속도 분포': 'Speed distribution',
    '속도 구간별 체류 시간 비율': 'Dwell-time share by speed band',
    '고속 구간 (Run)': 'High-Speed Runs',

    /* ---------------- Maneuver section ---------------- */
    '택킹 / 자이빙 요약': 'Tacking / Gybing Summary',
    '택킹 / 자이빙 목록': 'Tacking / Gybing List',
    '행을 누르면 지도 번호·±10초 곡선에 표시':
      'Click a row to highlight on the map and the ±10s curve',
    '회전 종류 필터': 'Maneuver type filter',
    '전체': 'All',
    '택킹': 'Tacking',
    '자이빙': 'Gybing',
    '자세히 ▾': 'Details ▾',
    '회전 상세 — ±10초 곡선': 'Maneuver Detail — ±10s curve',
    '여러 회전을 선택하면 겹쳐 그리고 평균선을 표시':
      'Select multiple maneuvers to overlay them with a mean line',
    '위 회전 목록 또는 지도에서 회전을 선택하면 정점 ±10초 곡선이 표시됩니다.\n        여러 회전을 선택하면 겹쳐 그리고 평균 곡선을 함께 보여줍니다.':
      'Select a maneuver from the list or map above to show the apex ±10s curve. Select multiple to overlay them with a mean curve.',
    '목록의 회전 모두 선택': 'Select all maneuvers in list',
    '포트 회전': 'Port maneuvers',
    '스타보드 회전': 'Starboard maneuvers',

    /* ---------------- 바이올린 ---------------- */
    '택 분포 — 포트 · 스타보드': 'Tack Distribution — Port · Starboard',
    '가운데 축 기준 좌 = 포트(P) · 우 = 스타보드(S)':
      'Left of center = Port (P) · Right = Starboard (S)',
    '풍상/풍하 선택': 'Upwind / Downwind',
    '풍상': 'Upwind',
    '풍하': 'Downwind',
    '지표 선택': 'Metric',
    '모집단 선택': 'Population',
    '상위 50%': 'Top 50%',
    '상위 20%': 'Top 20%',

    /* ---------------- 폴라 ---------------- */
    '폴라 다이어그램 · % of target': 'Polar Diagram · % of target',
    '이번 세션 포트·스타보드(실선) + 개인 베스트 타깃(점선)':
      'This session — Port · Starboard (solid) + personal-best target (dashed)',

    /* ---------------- HR section ---------------- */
    '심박수 요약': 'Heart Rate Summary',
    'GPX 트랙에 기록된 포인트별 심박수(bpm)':
      'Per-point heart rate (bpm) recorded in the GPX',
    '최대 심박수 (bpm)': 'Max heart rate (bpm)',
    '세션 중 심박 추이': 'Heart Rate Trend',
    '배경 띠 = 심박 존 · 속도 그래프·지도와 커서가 함께 움직입니다':
      'Background bands = HR zones · cursor synced with speed chart and map',
    '심박 존 분포': 'HR Zone Distribution',
    '각 심박 존에 머문 시간': 'Time spent in each HR zone',
    '퍼포먼스 대비 심박 효율': 'Performance vs HR — Aerobic Efficiency',
    '같은 속도를 더 낮은 심박으로 — 유산소 효율':
      'Same speed with lower HR — aerobic efficiency',
    '스킬–심박수 분석': 'Skill – Heart Rate Analysis',
    '택킹·자이빙의 진입 전 → 기술 중 → 완료 후 심박 반응과 회복':
      'Tacking / gybing — HR response and recovery: before entry → during → after exit',

    /* ---------------- 저장된 세션 ---------------- */
    '세션 비교': 'Session Compare',
    '전체 삭제': 'Delete all',
    '아직 저장된 세션이 없습니다. 위에서 이 세션 저장을 누르면\n        시즌별 성장 흐름과 개인 베스트가 여기에 쌓입니다.':
      'No saved sessions yet. Save a session above to build a season trend and personal-best history here.',
    '표시 지표': 'Metrics shown',
    '표시할 지표 선택': 'Choose metrics to show',
    '평균 속도': 'Avg Speed',
    '최고 속도': 'Top Speed',
    '거리': 'Distance',
    '라이딩 시간': 'Ride Time',
    '심박 회복 지수': 'HR Recovery Index',
    '차트 종류': 'Chart type',
    '선': 'Line',
    '막대': 'Bar',
    '표시할 지표를 1개 이상 선택해 주세요.':
      'Please select at least one metric to display.',
    '날짜': 'Date',
    '스포츠': 'Sport',
    '최고': 'Top',
    '평균': 'Avg',

    /* ---------------- Footer ---------------- */
    '라이딩 통계 대시보드 — Phase 1 (검증용 MVP) · GPX 클라이언트 사이드 분석':
      'Riding Stats Dashboard — Phase 1 (validation MVP) · client-side GPX analysis',
    '데이터는 브라우저에만 저장됩니다 · 단무지공방 / SailTech':
      'Data stays in your browser only · DMJ Workshop / SailTech',

    /* ---------------- Nav ---------------- */
    '주 메뉴': 'Main menu',
    '단무지공방 홈': 'DMJ Workshop home',

    /* ---------------- 공통 라벨 ---------------- */
    '포트': 'Port',
    '스타보드': 'Starboard',
    '종합': 'Overall',
    '회전효율': 'Turn Efficiency',
    '회전 효율': 'Turn Efficiency',
    '평균 회전효율': 'Avg Turn Efficiency',
    '심박수': 'Heart Rate',
    '심박': 'HR',
    '풍상 평균': 'Upwind Avg',
    '풍하 평균': 'Downwind Avg',

    /* ---------------- 표 헤더 / 셀 ---------------- */
    '포트 · 풍상': 'Port · Upwind',
    '스타보드 · 풍상': 'Starboard · Upwind',
    '포트 · 풍하': 'Port · Downwind',
    '스타보드 · 풍하': 'Starboard · Downwind',
    '세션 평균': 'Session Averages',
    '포트·스타보드 × 풍상·풍하 평균 — VMG·TWA·SOG · 구간 통계(상위 50%·20%)는 아래 퍼포먼스 통계 표':
      'Port·Starboard × Upwind·Downwind averages — VMG·TWA·SOG · tier stats (Top 50% / 20%) in the Performance Stats table below',

    /* ---------------- VPS / SPS ---------------- */
    '세일링 퍼포먼스 스코어': 'Sailing Performance Score',
    '세일링 퍼포먼스 스코어 산출 방식': 'How the Sailing Performance Score is computed',
    '속도 점수 70%': 'Speed score 70%',
    '회전 효율 30%': 'Turn efficiency 30%',
    '풍상 속도': 'Upwind speed',
    '풍하 속도': 'Downwind speed',
    'Upwind 풍상': 'Upwind',
    'Downwind 풍하': 'Downwind',
    'Overall 종합': 'Overall',
    'Tacking 택킹': 'Tacking',
    'Gybing 자이빙': 'Gybing',
    '비교 데이터 부족': 'Insufficient comparison data',
    '동일 풍속대 평균 대비': 'vs avg at same wind range',
    '점수': 'score',
    '— 동일 풍속대 세션 없음': '— no sessions at same wind range',
    '미풍 ≤10kt': 'Light ≤10kt',
    '중풍 11–16kt': 'Medium 11–16kt',
    '강풍 ≥17kt': 'Strong ≥17kt',
    '산출 불가': 'Not computable',
    '회전 데이터 없음 — 속도 항목만 반영 (회전 30% 미적용)':
      'No maneuver data — speed only (turn 30% omitted)',
    '속도 점수 산출 불가 — 계산기가 이 조건에서 풍상 주행 불가로 예측':
      'Speed score not available — calculator predicts upwind sailing is infeasible at these conditions',

    /* ---------------- 풍향 추정 / 안내 ---------------- */
    '수동 입력': 'Manual input',
    '확정': 'Confirmed',
    '사용자가 직접 지정해 확정한 풍향입니다.':
      'Wind direction confirmed by direct user input.',
    '다이얼·슬라이더로 직접 입력할 수 있습니다.':
      'Set wind direction with the dial or slider.',
    'no-go zone 추정': 'No-go zone estimate',
    '회전 기하 추정': 'Maneuver geometry estimate',
    '회전 기하': 'Maneuver geometry',
    '외부 날씨 (준비 중)': 'External weather (coming soon)',
    '신뢰도': 'Confidence',
    '높음': 'High',
    '보통': 'Medium',
    '중': 'Medium',
    '낮음': 'Low',
    /* 풍향 추정 소스 — compass 8방위 (Danny 2026-05-26 i18n fix).
       compass(deg) 가 반환하는 한국어 단어를 EN 모드에서 영문 약어로 치환.
       단독 텍스트노드일 때만 적용되므로 windSourceRow / windRecBanner 의
       값 출력은 방위어를 자체 <span> 으로 감싸 별도 텍스트노드로 두어야 함. */
    '북': 'N',
    '북동': 'NE',
    '동': 'E',
    '남동': 'SE',
    '남': 'S',
    '남서': 'SW',
    '서': 'W',
    '북서': 'NW',
    '풍향을 설정하고 “확정”하면 택킹·자이빙 분류와 VMG·폴라 분석이 활성화됩니다.':
      'Set the wind direction and tap "Confirm" to unlock tack / gybe classification and VMG / polar analysis.',
    '풍상·풍하 주행이 부족해 no-go zone 으로 추정할 수 없습니다.':
      'Not enough upwind / downwind sailing to estimate via no-go zone.',
    '세션 헤딩 분포의 빈 쐐기(세일 불가 구역) 중심으로 추정했습니다.':
      'Estimated from the empty wedge (no-go zone) in the heading distribution.',
    'OpenWeather 등 외부 날씨 데이터 연동 예정입니다 — API 키를 입력하면 세션 시각·위치의 풍향을 자동으로 불러옵니다.':
      'External weather data integration (e.g. OpenWeather) is coming — enter an API key to auto-fetch the wind direction for the session’s time and location.',
    '풍축을 가릴 만한 택·자이브가 부족해 회전 기하로 추정할 수 없습니다.':
      'Not enough tacks / gybes that cross the wind axis to estimate via maneuver geometry.',
    '택·자이브 진입/탈출 헤딩의 이등분선으로 풍축을 재구성했습니다.':
      'Reconstructed the wind axis from the bisector of tack / gybe entry / exit headings.',
    '외부 날씨 데이터에서 불러온 풍향입니다.':
      'Wind direction fetched from external weather data.',
    '수동으로 확정한 풍향을 사용합니다.': 'Using the manually confirmed wind direction.',

    /* ---------------- 코치(옥코치 ↔ Coach Danny) 카드 ----------------
       KO 노출 = 옥코치, EN 노출 = Coach Danny. coach.js 의 동적 narration
       은 양 언어 모두 자체 분기로 출력하므로 여기엔 정적 라벨만 매핑한다.
       (Danny 2026-05-26 정정 — 이전 일괄치환에서 KO 컨텍스트의 '옥코치' 가
        실수로 영어 'Coach Danny' 로 바뀐 부분은 별도 revert 패스 필요.) */
    'Coach Danny 코멘트': 'Coach Danny',
    'Coach Danny': 'Coach Danny',
    '옥코치': 'Coach Danny',
    '옥코치 코멘트': 'Coach Danny Comments',
    '옥코치 코멘트 · 장비 코칭': 'Coach Danny · Gear Coaching',
    '💬 옥코치 코멘트 · 장비 코칭': '💬 Coach Danny · Gear Coaching',
    '세일링 퍼포먼스 스코어·옥코치 분석에 사용 · 이 브라우저에 저장됩니다':
      'Used by Sailing Performance Score and Coach Danny · stored in this browser',
    '윙 사이즈는 옥코치 what-if 분석의 필수 입력입니다.':
      'Wing size is required for Coach Danny what-if analysis.',

    /* ---------------- 단위·짧은 라벨 ---------------- */
    '회': 'times',
    '점': 'score',
    '초': 'sec',
    '개': '',
    '분': 'min',
    '시간': 'h',
    '미지정': 'Unset',
    '없음': 'None',
    '있음': 'Available',

    /* ---------------- 안내문 (sentence) ---------------- */
    '시각 정보 없음': 'No time information',
    '저장된 세션을 정말 모두 삭제할까요?': 'Delete all saved sessions?',
    '편집된 트랙을 별도 세션으로 저장합니다.':
      'Save the edited track as a separate session.',
    '데이터가 부족합니다.': 'Insufficient data.',
    '풍향을 확정해 주세요.': 'Please confirm a wind direction.',
    '회전이 감지되지 않았습니다.': 'No maneuvers detected.',
    '심박 데이터가 없습니다.': 'No heart rate data.',
    '계산 중...': 'Computing…',
    '잠시만 기다려 주세요.': 'Please wait…',
    '파일을 읽는 중...': 'Reading file…',
    '분석 중...': 'Analyzing…',
    '파일 형식을 인식하지 못했습니다.':
      'Unrecognized file format.',
    '풍향을 확정하면 SOG·VMG·TWA 통계가, 심박 데이터가 있으면 심박 통계가 이 표에 표시됩니다.':
      'Confirming the wind shows SOG / VMG / TWA stats here. HR stats appear if heart rate data is present.',
    '풍향을 확정하면 SOG·VMG·TWA 통계가 이 표에 추가됩니다.':
      'Confirming the wind adds SOG / VMG / TWA stats to this table.',
    'TWA 계산에 풍향이 필요합니다.':
      'TWA calculation requires a wind direction.',
    'TWA 빈별 주행 데이터가 더 필요합니다.':
      'More sailing data per TWA bin is needed.',
    '타깃 폴라를 만들 폴라 데이터가 부족합니다.':
      'Not enough polar data to build a target polar.',
    '타깃 곡선을 만들 표본이 부족합니다 — TWA 빈별 주행 데이터가 더 필요합니다.':
      'Not enough samples to build a target curve — more sailing data per TWA bin is needed.',

    /* ---------------- 차트 축 / 캡션 ---------------- */
    '경과 시간 (분:초)': 'Elapsed time (mm:ss)',
    '속도 (노트)': 'Speed (knots)',
    '속도 (kt)': 'Speed (kt)',
    '속도 (km/h)': 'Speed (km/h)',
    '시간': 'Time',
    '심박수 (bpm)': 'Heart Rate (bpm)',
    '체류 시간': 'Dwell Time',
    '기타': 'Other',

    /* ---------------- 카카오톡 채널 (Danny 2026-05-26 · DMJ GROUP /_VITZX) ---------------- */
    '카톡 상담': 'KakaoTalk Chat',
    '카톡 상담 ↗': 'KakaoTalk Chat ↗',
    '카톡 상담 가능': 'KakaoTalk chat available',
    '카톡 1:1 상담': '1:1 KakaoTalk Chat',
    '카톡 1:1 상담 — 8분 응답': '1:1 KakaoTalk Chat — 8 min response',
    '카톡 1:1 컨설팅': '1:1 KakaoTalk consulting',
    '카톡 컨설팅': 'KakaoTalk consulting',
    '카톡 채널 상담이 가장 빠릅니다.': 'KakaoTalk channel is the fastest way to reach us.',
    '카톡 채널이 가장 빠릅니다.': 'KakaoTalk channel is the fastest way to reach us.',
    '카톡 1:1 견적': '1:1 KakaoTalk quote',
    '1:1 카톡 컨설팅': '1:1 KakaoTalk consulting',

    /* ---------------- 컨트롤·작은 텍스트 ---------------- */
    '윙 사이즈는 Coach Danny what-if 분석의 필수 입력입니다.\n        풍속은 아래 풍향 설정 카드에서 입력합니다. 프론트 윙 면적 조언은 v2 범위입니다.':
      'Wing size is required for Coach Danny what-if analysis. Wind speed is entered in the Wind Direction card below. Front-wing area advice is planned for v2.',
    '양끝 핸들을 드래그해 워밍업·이동 구간을 잘라내면 남은 트랙이\n        가로 폭을 꽉 채웁니다. 그래프 위를 가로로 드래그하면 제외 구간(휴식·표류\n        등)이 만들어지고, 제외 구간을 누르면 해제됩니다. 편집은 실제 시간을 기준으로\n        하며 즉시 거리·속도·회전 분석에 반영됩니다.':
      'Drag the handles at either end to trim warm-up / travel sections — the remaining track fills the width. Drag horizontally over the chart to create an exclude zone (rest, drift, etc.); click an exclude zone to remove it. Edits are based on clock time and immediately update distance / speed / maneuver analysis.',

    /* ---------------- Garmin 등 (인트로 가이드) ---------------- */
    'Garmin Connect 웹 → 액티비티 열기 → 우측 상단 ⚙(톱니) →\n             원본 내보내기 또는 GPX 내보내기':
      'Garmin Connect (web) → open the activity → top-right ⚙ (gear) → Export original or Export GPX',
    'Apple 건강 앱에는 GPX 내보내기가 없습니다. HealthFit 또는\n             RunGap 같은 앱으로 워크아웃을 GPX/FIT 로 내보내세요.':
      'Apple Health has no GPX export. Use a third-party app like HealthFit or RunGap to export workouts as GPX / FIT.',
    'Samsung Health 에서 운동 기록 내보내기를 사용하거나, GPX 를 지원하는\n             서드파티 트래킹 앱(예: 윙포일 GPS 앱)으로 기록하세요.':
      'Use Samsung Health workout export, or a third-party GPS app that supports GPX (e.g., wingfoil GPS apps).',

    /* ---------------- 토글 ---------------- */
    '한글': '한글',     /* keep — both visible in toggle */
    'English': 'English',
    'Language': 'Language',
    '언어': 'Language',
    'Korean': 'Korean',

    /* ============================================================
     * Phase 2 — charts.js (Chart.js config + custom canvas) (Danny 2026-05-25)
     * ============================================================ */
    '시작': 'Start',
    '종료': 'End',
    '제외 ✕ 클릭 해제': 'Excluded ✕ click to clear',
    '경과 시간': 'Elapsed time',
    '속도 ({u})': 'Speed ({u})',
    '심박 기록 없음': 'No HR data',
    '회전 정점': 'Apex',
    'VMG ({dir}, {u})': 'VMG ({dir}, {u})',
    '회전율 (°/s)': 'Turn rate (°/s)',
    '회전율 크기 (°/s)': 'Turn rate magnitude (°/s)',
    'SOG ±1σ 밴드': 'SOG ±1σ band',
    '회전율 ±1σ 밴드': 'Turn rate ±1σ band',
    '평균 SOG ({u})': 'Avg SOG ({u})',
    '평균 회전율 (°/s)': 'Avg turn rate (°/s)',
    '회전 정점 기준 경과 시간 (sec)': 'Time relative to apex (s)',
    '표본 부족 ({n})': 'Insufficient samples ({n})',
    '데이터 없음': 'No data',
    '◀ 포트 (P)': '◀ Port (P)',
    '스타보드 (S) ▶': 'Starboard (S) ▶',
    '← 밀도': '← density',
    '밀도 →': 'density →',
    '체류 시간': 'Dwell time',
    ' ─ 합쳐진 구간 ─': ' ─ Merged bands ─',
    '기록 공백': 'Recording gap',
    '심박수 ({u})': 'Heart rate ({u})',
    '휴식 (Z1 미만)': 'Rest (below Z1)',
    '머문 시간 (min)': 'Time in zone (min)',
    '{n}분 (': '{n} min (',
    '순간 기록 (속도 · 심박)': 'Instant samples (speed · HR)',
    '속도 구간별 심박 중앙값': 'Median HR by speed band',
    '개인 베스트 타깃': 'Personal-best target',
    '이번 세션 · 포트(P)': 'This session · Port (P)',
    '이번 세션 · 스타보드(S)': 'This session · Starboard (S)',
    '▲ 풍상 0°': '▲ Upwind 0°',
    '▼ 풍하 180°': '▼ Downwind 180°',
    '━ 포트(P) 실측': '━ Port (P) actual',
    '스타보드(S) 실측 ━': 'Starboard (S) actual ━',
    '┈ 개인 베스트 타깃(기준)': '┈ Personal-best target (reference)',
    '반지름 = 속도 ({u})': 'Radius = speed ({u})',
    '거리 (km)': 'Distance (km)',
    '라이딩 시간 (min)': 'Ride time (min)',
    '심박 회복 지수 (bpm/min)': 'HR recovery index (bpm/min)',

    /* ============================================================
     * Phase 2 — coach.js (Coach Danny 코멘트 + 동적 narration) (Danny 2026-05-25)
     * ============================================================ */

    /* --- 스킬 등급 --- */
    '입문': 'Novice',
    '초급': 'Beginner',
    '중급': 'Intermediate',
    '상급': 'Advanced',
    '상급-선수': 'Advanced–Pro',
    '선수': 'Pro',

    /* --- 짧은 라벨 (tcSideLabel · recTxt) --- */
    '선택 회전': 'Selected maneuver',
    '미회복': 'no recovery',
    '{n}초': '{n}s',

    /* --- 룰별 narration nums --- */
    '진입 SOG 포트 {p} · 스타보드 {s} {u} · 진입 TWA 차 {d}°':
      'Entry SOG — Port {p} · Starboard {s} {u} · ΔTWA {d}°',
    '진입 SOG 포트 {p} · 스타보드 {s} {u}':
      'Entry SOG — Port {p} · Starboard {s} {u}',
    '{side} 진입 SOG 편차 ±{sd} {u} · 표본 {n}회':
      '{side} entry-SOG spread ±{sd} {u} · {n} samples',
    '속도 손실 포트 {p}% · 스타보드 {s}%':
      'Speed loss — Port {p}% · Starboard {s}%',
    '회복 시간 포트 {p} · 스타보드 {s}':
      'Recovery time — Port {p} · Starboard {s}',
    '택킹 진입→풍축 시간 평균 {dur}초 ({skill} 기준 {thr}초)':
      'Avg tack entry→wind-axis time {dur}s ({skill} threshold {thr}s)',
    '회전율 봉우리 2개 이상 {a}/{b}회':
      'Multi-peak turn rate {a}/{b}',
    '자이빙 탈출 TWA 평균 {x}° (라이더 풍하 평균 {r}°)':
      'Avg gybe exit TWA {x}° (rider downwind avg {r}°)',
    '평균 회전 효율 {eff}/100':
      'Avg turn efficiency {eff}/100',

    /* --- TURN_COACH_TEXT R1 — 진입 속도-각도 트레이드오프 --- */
    '진입 — 속도와 각도 맞바꿈': 'Entry — speed-vs-angle trade-off',
    '{fast}택이 더 빠르지만 풍상 각도를 내주고 있습니다.':
      '{fast} tack is faster, but giving up upwind angle.',
    '{fast}택으로 들어갈 때 발 스위치(토우사이드 전환) 중 윙 당기는 힘을 잃었거나, 속도를 얻으려 풍하로 살짝 베어어웨이한 것으로 보입니다. 중급~상급 초반까지 흔한 패턴입니다.':
      'On {fast} tack entry, it looks like you lost wing power during the foot-switch (toe-side transition), or bore away slightly downwind to gain speed. Common pattern from intermediate through early advanced.',
    '윙을 머리 위·보드 앞쪽으로 두고 리딩엣지를 수평으로 유지해 기류를 깨지 않은 채로 손을 바꾸면, 각도를 내주지 않고도 속도를 실어 갈 수 있습니다.':
      'Keep the wing overhead and forward, leading edge level, and switch hands without disrupting the airflow — you can carry speed without giving up angle.',

    /* --- R2a — 진입 속도 부족, 보드 힐 과다 --- */
    '진입 속도 부족 — 보드 힐 과다': 'Low entry speed — too much board heel',
    '{slow}택 진입 속도가 낮습니다.': '{slow} tack entry speed is low.',
    '{slow}택 진입 속도가 {fast}택보다 느립니다. 항적이 더 날카로운 것으로 보아, 보드 힐을 너무 깊게 줘 회전 중 속도를 잃은 것으로 보입니다.':
      '{slow} tack entry is slower than {fast}. The sharper track suggests you’re heeling the board too deep, bleeding speed through the turn.',
    '보드를 과하게 눕히지 말고 한 박자 길게, 일정한 반경으로 카빙하며 속도를 지킵니다.':
      'Don’t over-heel the board — carve one beat longer at a steady radius to preserve speed.',

    /* --- R2b — 진입 속도 부족, 윙 프로파일·시팅 --- */
    '진입 속도 부족 — 윙 프로파일·시팅': 'Low entry speed — wing profile / sheeting',
    '{slow}택 진입 속도가 {fast}택보다 느립니다. 항적은 매끄러운데 속도가 빨리 빠지는 것으로 보아, 윙 프로파일 문제(리치 펄럭임·스톨링)이거나 오버시팅으로 보입니다.':
      '{slow} tack entry is slower than {fast}. The track is smooth but speed drops fast — likely a wing profile issue (leech flutter / stall) or over-sheeting.',
    '윙을 과하게 당기지 말고 리치가 펄럭이지 않는 시팅을 찾아, 회전 내내 깨끗한 기류를 유지합니다.':
      'Don’t over-sheet — find a sheeting where the leech doesn’t flutter, keeping clean airflow through the entire turn.',

    /* --- R3 — 진입 일관성 부족 --- */
    '진입 일관성 부족': 'Inconsistent entry',
    '{side} 진입 속도가 회전마다 들쭉날쭉합니다.':
      '{side} entry speed varies maneuver to maneuver.',
    '{side} 진입 속도가 회전마다 편차 ±{sd} {unit} 로 들쭉날쭉합니다. 같은 바람·해상 조건이라면, 반복 경험이 부족해 매번 같은 진입 지점을 못 찾는 것으로 보입니다.':
      '{side} entry speed varies ±{sd} {unit} between maneuvers. With consistent wind and sea state, this suggests insufficient repetition — you’re not finding the same entry point each time.',
    '같은 조건에서 같은 진입 동작을 반복하며 가장 잘 되는 지점을 몸에 익히면 분산이 줄어듭니다.':
      'Repeat the same entry motion under the same conditions until your body locks onto the best point — the variance will shrink.',

    /* --- R4 — 회전 속도 손실 --- */
    '회전 속도 손실': 'Speed loss through the turn',
    '{side} 회전에서 속도 손실이 큽니다.':
      '{side} turn loses too much speed.',
    '{side} 회전에서 속도 손실이 더 큽니다(평균 {loss}%). 손·발 바꾸기가 늦었거나, 손은 바꿨지만 윙을 바람 받게 빨리 당기지 못했거나, 보드 힐을 새 풍상쪽으로 빨리 주지 못해 아래쪽 리프팅을 제때 만들지 못한 것으로 보입니다.':
      '{side} turn shows greater speed loss (avg {loss}%). Hand/foot switch was late, the wing wasn’t powered up fast enough after the switch, or board heel toward the new upwind side wasn’t delivered in time to maintain foil lift.',
    '손·발 바꾸기를 지체 없이 끝내고, 바꾼 즉시 윙을 당겨 바람을 받게 하며, 보드 힐을 새 풍상쪽으로 곧장 줘 회전 중에도 리프팅이 끊기지 않게 합니다.':
      'Complete the hand/foot switch without delay, sheet in immediately to power the wing, and heel the board to the new upwind side at once — keep foil lift unbroken through the turn.',

    /* --- R5 — 회전 후 회복 지연 --- */
    '회전 후 회복 지연': 'Slow post-turn recovery',
    '{side} 회전 후 활주 복귀가 느립니다.':
      '{side} turn — slow return to planing speed.',
    '{side} 회전 후 활주 속도로 복귀가 느립니다. 발을 바꾼 뒤 보드 힐을 풍상쪽으로 주지 않으면 보드가 가라앉는데, 아래쪽 리프팅이 확보돼야 윙을 당겨 탈출할 수 있습니다.':
      '{side} turn is slow to return to planing. After switching feet, if you don’t heel the board toward the upwind side, the board sinks — foil lift must be re-established before you can sheet in to exit.',
    '탈출 직후 보드를 풍상쪽으로 기울여 리프팅을 만들고, 속도가 살아나면 윙을 당겨 가속합니다. 속도가 죽었다면 먼저 보드를 기울여 리프팅부터 만듭니다.':
      'Right after exit, heel the board toward the upwind side to build lift; once speed picks up, sheet in to accelerate. If speed has died, restore lift first — then power up.',

    /* --- R6 — 택킹이 느림 --- */
    '택킹이 느림': 'Tack is too slow',
    '택킹 진입에서 풍축까지가 {skill} 기준보다 오래 걸립니다.':
      'Time from tack entry to wind-axis is slower than the {skill} benchmark.',
    '택킹 진입부터 풍축(정풍상) 도달까지 평균 {dur}초로, {skill} 기준 {thr}초보다 느립니다. 레벨 기준 시간은 회전 전체가 아니라 풍축까지 끌고 가는 전반부 구간을 가리킵니다 — 이 구간에서 추진력을 잃고 멈칫하는 것으로 보입니다. 풍축 이후 탈출·재정비 구간은 별도 회복 지표로 봅니다.':
      'Average time from tack entry to head-to-wind (true upwind) is {dur}s, slower than the {skill} threshold of {thr}s. The benchmark covers only the first half (carrying through to wind axis) — it looks like momentum is lost and the turn stalls there. Post-axis exit / re-set is tracked by recovery metrics separately.',
    '진입 속도를 충분히 싣고, 윙을 머리 위·앞쪽에 둔 채 망설임 없이 한 번에 손을 바꿔 풍축을 빠르게 넘깁니다.':
      'Carry enough entry speed, keep the wing overhead and forward, and switch hands in one decisive motion to cross the wind axis quickly.',

    /* --- R7 — 2단으로 끊기는 회전 --- */
    '2단으로 끊기는 회전': 'Two-step turn',
    '회전이 한 박자로 이어지지 않고 둘로 끊깁니다.':
      'The turn breaks into two motions instead of one continuous beat.',
    '회전율 봉우리가 둘 이상으로, 회전이 한 번의 리듬으로 이어지지 않고 두 동작으로 끊깁니다 — 발교차와 손교차의 시간차가 큰 것으로 보입니다.':
      'Turn rate shows two or more peaks — the turn doesn’t flow as one rhythm and breaks into two motions, suggesting too much delay between hand-switch and foot-switch.',
    '손교차를 먼저 하고, 발교차를 최대한 손교차에 가까운 타이밍으로 붙여 한 박자에 끝냅니다.':
      'Switch hands first, then bring the foot-switch as close to the hand-switch as possible — finish the whole turn in one beat.',

    /* --- R8 — 자이빙 탈출 각도 과깊음 --- */
    '자이빙 탈출 각도 과깊음': 'Gybe exit angle too deep',
    '자이빙이 너무 깊게 풍하로 빠져나옵니다.':
      'Gybe is exiting too deep downwind.',
    '자이빙 탈출 시 보드를 필요 이상으로 깊게 풍하로 떨궈, 정풍하에 가까운 느린 코스로 빠져나온 것으로 보입니다 — VMG 손실이 큽니다.':
      'On gybe exit, the board is dropped deeper downwind than needed, coming out near dead downwind — a slow course with significant VMG loss.',
    '회전을 목표 코스각(브로드 리치)에서 멈춰 세우고, 그 각에서 보드를 평평하게 눌러 가속으로 전환합니다.':
      'Stop the turn at the target course angle (broad reach), then flatten the board at that angle and switch into acceleration.',

    /* --- R9 — 회전 기술 양호 --- */
    '회전 기술 양호': 'Turn technique is solid',
    '포트·스타보드 회전이 고르고 효율이 높습니다.':
      'Port and starboard turns are even and high-efficiency.',
    '포트·스타보드 회전이 고르고 효율이 높습니다(평균 {eff}/100). 현재 회전 기술이 안정적입니다.':
      'Port and starboard turns are even and high-efficiency (avg {eff}/100). Your turning technique is stable.',

    /* --- coach.js guard / VPS notes / missing 항목 --- */
    '풍속': 'Wind speed',
    '체중': 'Weight',
    '윙 사이즈': 'Wing size',
    '풍향(확정)': 'Wind direction (confirmed)',
    '실측 풍상 VMG(풍향 확정 필요)': 'Measured upwind VMG (requires confirmed wind)',
    '리프팅 계산기 모듈': 'Lift calculator module',
    '풍향을 입력하면 포트·스타보드 비교 코칭이 가능합니다.':
      'Set the wind direction to enable port vs starboard comparison coaching.',
    '한쪽 택만 선택돼 포트·스타보드 비대칭 코칭은 생략했습니다.':
      'Only one tack is selected — port vs starboard asymmetry coaching is skipped.',
    '속도 점수 산출 불가 — 계산기가 이 조건에서 풍상 주행 불가로 예측':
      'Speed score not available — the calculator predicts upwind sailing is infeasible at these conditions',
    '회전 데이터 없음 — 속도 항목만 반영 (회전 30% 미적용)':
      'No maneuver data — speed only (turn 30% omitted)',

    /* ============================================================
     * Phase 2-C — app.js 정적 라벨 (DOM 자동 번역 대상) (Danny 2026-05-25)
     * ============================================================ */
    /* --- 스포츠 --- */
    '윙포일': 'Wingfoil',
    '윈드서핑': 'Windsurfing',
    '윈드포일': 'Windfoil',
    '포뮬라 카이트': 'Formula Kite',
    '카이트': 'Kite',

    /* --- 짧은 라벨 --- */
    '회전': 'Turn',
    '회전수': 'Maneuvers',
    '종류': 'Type',
    '구분': 'Side',
    '시각': 'Time',
    '진입': 'Entry',
    '최저': 'Min',
    '탈출': 'Exit',
    '진입 SOG': 'Entry SOG',
    '최저 SOG': 'Min SOG',
    '탈출 SOG': 'Exit SOG',
    '속도 손실': 'Speed loss',
    '총 회전각': 'Total turn angle',
    '평균 회전율': 'Avg turn rate',
    '소요 시간': 'Duration',
    '회복 시간': 'Recovery time',
    '날짜 정보 없음': 'No date',
    '미입력': 'Not entered',
    '확정됨': 'Confirmed',
    '미확정 — 확정 필요': 'Unconfirmed — please confirm',
    '✓ 풍향 해제': '✓ Clear wind',
    '풍향이 해제되었습니다.': 'Wind direction cleared.',
    '느림': 'Slow',
    '빠름': 'Fast',
    '실제 시각': 'Clock time',
    '진단': 'Diagnosis',
    '조언': 'Advice',
    '높을수록 좋음': 'Higher is better',
    '낮을수록 좋음': 'Lower is better',
    '중립 지표': 'Neutral metric',
    '중립 · 최적각 ≈140–150°': 'Neutral · optimum ≈140–150°',
    '중립 · 좌우 트림': 'Neutral · lateral trim',
    '중립 · 앞뒤 트림': 'Neutral · fore-aft trim',
    '중립 · 신체 부하 참고': 'Neutral · physical-load reference',
    '시각 정보 없음': 'No time information',
    '시각 정보가 없어 속도 그래프를 표시할 수 없습니다.':
      'No time information — speed chart unavailable.',
    '시각 정보가 없어 표준 지표를 계산할 수 없습니다.':
      'No time information — standard metrics unavailable.',
    '시각 정보가 없어 퍼포먼스 통계를 계산할 수 없습니다.':
      'No time information — performance stats unavailable.',
    '시각 정보가 없어 회전 분석 불가': 'No time information — maneuver analysis unavailable',
    '검출된 고속 구간이 없습니다.': 'No high-speed runs detected.',
    '평균 · 최고': 'avg · top',
    '힐(Heel)': 'Heel',
    '피치(Pitch)': 'Pitch',

    /* --- 요약 스트립 라벨 --- */
    '총 거리 (km)': 'Total distance (km)',
    '이동 시간 (min:sec)': 'Ride time (min:sec)',
    '최고 속도 (kt)': 'Top speed (kt)',
    '최고 속도 (km/h)': 'Top speed (km/h)',
    '평균 속도 (kt)': 'Avg speed (kt)',
    '평균 속도 (km/h)': 'Avg speed (km/h)',
    '포일링 시간 (min:sec)': 'Foiling time (min:sec)',
    '플레이닝 시간 (min:sec)': 'Planing time (min:sec)',
    '풍향 (°)': 'Wind direction (°)',
    '풍향 ': 'Wind direction ',
    '2초 구간 최고': '2-second peak',
    '이동 중': 'while moving',

    /* --- 풍향 안내 --- */
    '풍상/풍하 주행과 택·자이브가 모두 부족해 풍향을 추정할 수 없습니다. 리칭(횡주) 위주이거나 직진 구간이 적은 세션입니다 — 직접 설정해 주세요.':
      'Not enough upwind / downwind sailing and tacks / gybes to estimate the wind direction. The session is mostly reaching or has few straight runs — please set the wind manually.',
    '풍향 추정 소스': 'Wind direction sources',
    '여러 방식의 추정을 비교해 적용하세요': 'Compare different estimation methods and apply',
    '현재 적용': 'Currently applied',
    '권장': 'Recommended',
    '미리보기 적용': 'Apply preview',
    '권장값 적용': 'Apply recommended',
    '아래 추정값으로 바꾸려면 “미리보기 적용” 후 다시 확정해 주세요.':
      'To switch to one of the estimates below, tap "Apply preview" then re-confirm.',
    '자동 추정에 쓸 풍상·풍하 주행이나 택·자이브가 부족합니다 — 다이얼·슬라이더로 직접 입력해 주세요.':
      'Not enough upwind / downwind sailing or tacks / gybes for auto-estimation — please set the wind manually via the dial or slider.',

    /* --- 회전 코칭 footnote / 안내 --- */
    '회전효율 점수 0–100점 척도 · 평균 회전효율·손실의 ± 는 표준편차(±1σ) · 상위 n% 는 회전효율 높은 회전 순 평균':
      'Turn efficiency on 0–100 scale · ± after averages is standard deviation (±1σ) · top n% = mean of the highest-efficiency maneuvers',
    '택킹과 자이빙은 풍축 통과 감속이 달라 회전효율을 합산하지 않고 유형별로 나눠 봅니다.':
      'Tacking and gybing have different deceleration through the wind axis, so turn efficiency is shown per type rather than summed.',
    '회전효율 — 택킹 · 자이빙 따로': 'Turn efficiency — Tacking · Gybing separately',
    '택킹·자이빙 기술 — 포트 / 스타보드별': 'Tack / Gybe technique — by Port / Starboard',
    '평균 속도 손실': 'Avg speed loss',
    '평균 회복 시간': 'Avg recovery time',
    '평균 회전 속도': 'Avg turn rate',
    '평균 손실': 'Avg loss',
    '평균 심박': 'Avg HR',

    /* --- 회전 stats stat tiles --- */
    '전체 회전': 'Total maneuvers',
    '택킹 횟수': 'Tacks',
    '택킹 성공률': 'Tack success rate',
    '자이빙 횟수': 'Gybes',
    '자이빙 성공률': 'Gybe success rate',
    '택킹 / 자이빙': 'Tacking / Gybing',
    '풍향 필요': 'Wind required',
    '풍향 입력 시 분류': 'Classified when wind is set',
    '베스트 택킹': 'Best tack',
    '베스트 자이빙': 'Best gybe',
    '풍향을 입력하면 택킹·자이빙을 분류하고 베스트 회전을 가립니다.':
      'Set the wind to classify tacks / gybes and identify the best maneuver.',
    '검출된 택킹·자이빙이 없습니다.': 'No tacks or gybes detected.',
    '풍향을 먼저 설정하세요.': 'Please set the wind first.',
    '풍향이 확정되면 회전이 택킹·자이빙으로 분류되어, 풍축을 넘는 진짜 택킹·자이빙만 골라 여기에 표시됩니다. 위 풍향 설정 카드에서 풍향을 확정해 주세요.':
      'Once the wind is confirmed, maneuvers are classified into tacks / gybes — only those that cross the wind axis are shown here. Please confirm the wind direction in the card above.',
    '해당 종류의 회전이 없습니다.': 'No maneuvers of this type.',
    '접기 ▴': 'Collapse ▴',
    '자세히 ▾': 'Details ▾',
    '그라데이션으로 강조된 줄은 세션 베스트 회전입니다 — 택킹·자이빙 각 종류에서 효율 점수가 가장 높은 회전을 표시합니다.':
      'Gradient-highlighted rows are session-best maneuvers — the highest-efficiency tack and gybe.',
    '스타보드(S)': 'Starboard (S)',
    '포트(P)': 'Port (P)',
    '포트 → 스타보드 (P→S)': 'Port → Starboard (P→S)',
    '스타보드 → 포트 (S→P)': 'Starboard → Port (S→P)',
    '✓ 속도 손실이 거의 없는 깔끔한 회전입니다.': '✓ Clean maneuver with almost no speed loss.',

    /* --- 회전 detail 추가 --- */
    '모두 선택': 'Select all',
    '전체 해제': 'Clear all',
    '회 선택': ' selected',
    '좌우 = 포트 · 스타보드 · 밴드 = ±1σ': 'L/R = Port · Starboard · band = ±1σ',
    '굵은 선 = 평균 · 밴드 = ±1σ': 'Bold line = mean · band = ±1σ',
    '평균 SOG': 'Avg SOG',
    '평균 회전율 ': 'Avg turn rate ',
    'SOG ±1σ 밴드 ': 'SOG ±1σ band ',
    '회전율 ±1σ 밴드 ': 'Turn rate ±1σ band ',
    '개별 회전': 'Individual maneuvers',
    '포트 · 스타보드 비교 — 평균 ± 표준편차': 'Port · Starboard comparison — mean ± SD',
    '선택한 회전 — 평균 ± 표준편차': 'Selected maneuvers — mean ± SD',
    '각 값은 선택한 회전들의 평균 ± 표준편차(±1σ)입니다. 그래프가 밴드로 보여주는 회전 간 분산을 정확한 수치로 정리한 것입니다. 세일링 퍼포먼스 스코어는 회전 전후 VMG 의 로스·게인 기반 점수(0–100)의 평균으로, SPS 카드의 회전 항목과 같은 정의입니다.':
      'Each value is the mean ± standard deviation (±1σ) of the selected maneuvers — a numeric summary of the inter-maneuver spread that the chart shows as a band. The Sailing Performance Score is a 0–100 score derived from VMG loss / gain around each maneuver, using the same definition as the SPS card.',
    '세일링 퍼포먼스 스코어 (택킹)': 'Sailing Performance Score (Tacking)',
    '세일링 퍼포먼스 스코어 (자이빙)': 'Sailing Performance Score (Gybing)',
    '회전효율 점수': 'Turn efficiency',
    '차이 (S−P)': 'Δ (S−P)',
    '지표': 'Metric',
    '데이터 패턴 감지는 알고리즘이, 진단·조언은 코치 검토 초안입니다 — 추정·과장 없이 가설로 제시합니다.':
      'Pattern detection is algorithmic; diagnosis and advice are coach-reviewed drafts — presented as hypotheses without inflation.',

    /* --- 바이올린 --- */
    '풍향을 입력·확정하면 포트·스타보드 택별 속도 분포(바이올린)를 표시합니다.':
      'Set and confirm the wind to show port / starboard distribution (violin).',
    '입력하신 파일에 해당 데이터가 없습니다.': 'The uploaded file does not contain this data.',
    '포일링': 'Foiling',
    '플레이닝': 'Planing',

    /* --- 타깃 폴라 --- */
    '풍상 % of target': 'Upwind % of target',
    '풍하 % of target': 'Downwind % of target',
    '비교 가능한 구간 없음': 'No comparable segment',
    '타깃 = 이번 세션 단독 기준입니다(누적 데이터 없음) — 세션을 저장하면 다음부터 누적 베스트로 갱신됩니다.':
      'Target = this session only (no accumulated data) — save sessions to build a running personal-best target.',

    /* --- HR section --- */
    '평균 심박 (bpm)': 'Avg HR (bpm)',
    '최고 심박 (bpm)': 'Max HR (bpm)',
    '최저 심박 (bpm)': 'Min HR (bpm)',
    '심박 기록률 (%)': 'HR coverage (%)',
    '세션 시간가중 평균': 'Session time-weighted average',
    '세션 관측 최대': 'Session observed max',
    '세션 관측 최소': 'Session observed min',
    '순항 기준 심박 (bpm)': 'Cruise HR (bpm)',
    '최대 생리 반응 (bpm)': 'Max physiological response (bpm)',
    '포일링·회전 밖 시간가중 평균': 'Time-weighted avg outside foiling and turns',
    '세션 회복 지수 (bpm/min)': 'Session recovery index (bpm/min)',
    '분석한 회전 (times)': 'Maneuvers analyzed',
    '회복 표본 부족': 'Insufficient recovery samples',
    '풍향을 확정하면 택킹·자이빙별 심박 반응과 회복을 분석합니다.':
      'Confirm the wind to analyze tack / gybe HR response and recovery.',
    '심박이 함께 기록된 택킹·자이빙이 아직 없습니다.':
      'No tacks / gybes recorded with HR yet.',
    '분석 수': 'N analyzed',
    '진입 전': 'Pre-entry',
    '기술 중 최고': 'Peak (during)',
    '순항 대비': 'vs cruise',
    '완료 후 회복': 'Post-exit recovery',
    '주행 평균 심박': 'Sailing avg HR',
    '주행 평균 속도': 'Sailing avg speed',
    '심박 효율 지수': 'HR efficiency index',
    '심박 드리프트': 'HR drift',
    '회복 구간 아래 — 정지·표류·휴식': 'Below recovery — stop, drift, rest',
    '휴식': 'Rest',

    /* --- HR 효율 footnote --- */
    '효율 분석에 필요한 주행 구간이 부족합니다.':
      'Not enough sailing segments for efficiency analysis.',

    /* --- 압션 토스트 / 안내 --- */
    'GPX 파일을 분석하지 못했습니다.': 'Failed to parse the GPX file.',
    'VKX 파일을 분석하지 못했습니다.': 'Failed to parse the VKX file.',
    '파일을 읽지 못했습니다.': 'Failed to read the file.',
    '편집 적용에 실패했습니다.': 'Failed to apply edits.',
    '리플레이는 시각 정보가 있는 세션에서만 가능합니다.':
      'Replay is only available for sessions with time information.',
    '리플레이 모듈을 불러오지 못했습니다.': 'Failed to load the replay module.',
    '저장에 실패했습니다.': 'Save failed.',
    '✓ 편집본을 저장된 세션으로 복사했습니다.':
      '✓ Edited copy saved as a separate session.',
    '✓ 세션을 저장했습니다.': '✓ Session saved.',
    '저장된 모든 세션을 삭제할까요?': 'Delete all saved sessions?',
    '⚠ 이 GPX 에는 시각 정보가 없어 속도·시간 분석을 할 수 없습니다. 지도와 총 거리만 표시됩니다.':
      '⚠ This GPX has no time information — speed and time analysis are unavailable. Only the map and total distance are shown.',
    '샘플 — 부산 송정 (실측 GPX)': 'Sample — Songjeong, Busan (real GPX)',
    '샘플 데이터를 불러오지 못했습니다. 직접 GPX 파일을 업로드해 주세요.':
      'Failed to load sample data. Please upload your own GPX file.',

    /* --- 풍향 / 컴퍼스 --- */
    '북': 'N', '북동': 'NE', '동': 'E', '남동': 'SE',
    '남': 'S', '남서': 'SW', '서': 'W', '북서': 'NW',
    '우선회': 'Right turn',
    '좌선회': 'Left turn',

    /* --- 요일 --- */
    '일': 'Sun', '월': 'Mon', '화': 'Tue', '수': 'Wed',
    '목': 'Thu', '금': 'Fri', '토': 'Sat',

    /* --- 폴라 footnote --- */
    '타깃 폴라를 만들 폴라 데이터가 부족합니다.':
      'Not enough polar data to build a target polar.',
    '타깃 곡선을 만들 표본이 부족합니다 — TWA 빈별 주행 데이터가 더 필요합니다.':
      'Not enough samples to build a target curve — more sailing data per TWA bin is needed.',
    '풍향을 설정하면 타깃 폴라와 % of target 가 표시됩니다 — TWA 계산에 풍향이 필요합니다.':
      'Set the wind to display target polar and % of target — TWA calculation requires a wind direction.',
    '곡선이나 점에 커서를 올리면 해당 곡선이 강조되고 값이 표시됩니다.':
      'Hover a curve or point — that curve is emphasized and its value is displayed.',
    '% of target 타일은 매 순간 속도(시간가중 평균)를 같은 TWA의 타깃과 비교한 값입니다.':
      '% of target tiles compare instantaneous speed (time-weighted average) against the target at the same TWA.',

    /* ============================================================
     * Phase 2-C 보강 — 긴 tooltip / footnote / info-panel 텍스트
     * 호버 title 속성에 들어가는 LOSS_TIP/EFF_TIP/DURATION_TIP/RECOVERY_TIP/
     * SUCCESS_TIP 와 stats info-panel 의 sog/vmg/twa/heel/pitch/hr 해설.
     * ============================================================ */
    '회전이 골 방향(풍상·풍하) 속도를 얼마나 잃었는지를 효율 점수와 같은 기준으로 나타냅니다. 풍향이 신뢰도 있게 확정된 세션은 VMG(풍상·풍하 유효속도) 기준이라 손실 % + 효율 점수 = 100 이며, 그렇지 않으면 SOG(속도)의 진입·탈출 중 빠른 쪽 대비 회전 중 최저 속도까지의 감속폭입니다.':
      'How much speed the maneuver lost relative to the goal direction (upwind/downwind), on the same scale as the efficiency score. With reliably confirmed wind, this is based on VMG (upwind/downwind effective speed) so loss % + efficiency = 100. Otherwise, it’s the SOG deceleration from the faster of entry/exit down to the minimum speed during the turn.',
    '회전효율 점수(0~100)입니다. 풍향이 신뢰도 있게 확정된 세션은 회전 전후 VMG 의 보존율(탈출 VMG ÷ 진입 VMG), 그렇지 않으면 속도 손실(65%)과 회복 시간(35%) 을 합산해 산출합니다. 높을수록 좋은 회전입니다.':
      'Turn efficiency score (0–100). With reliably confirmed wind, it’s the VMG preservation ratio across the turn (exit VMG ÷ entry VMG). Otherwise, it’s a blend of speed loss (65%) and recovery time (35%). Higher is better.',
    '소요 시간 = 회전에 걸린 시간. 진행 방향(헤딩)이 꺾이기 시작한 순간부터 회전이 끝나 헤딩이 안정될 때까지를 잰 값으로, 회전 후 속도를 되찾는 회복 시간과는 별개입니다.':
      'Duration = time taken by the maneuver — measured from when heading starts to turn until heading settles after the turn. Separate from the recovery time required to regain speed after the turn.',
    '회복 시간 = 회전 중 최저 속도 지점부터, 회전 전후의 기준 속도(진입·탈출 중 빠른 쪽)의 95% 까지 다시 가속하는 데 걸린 시간입니다. 45초 안에 회복하지 못하면 “—” 로 표시합니다.':
      'Recovery time = time from the minimum-speed point during the turn until re-accelerating back to 95% of the reference speed (faster of entry/exit). Shown as "—" if recovery does not occur within 45s.',
    '전체 시도 중 터치다운 없이 완료한 비율입니다. 회전 도중 최저 속도가 포일링 속도 임계 아래로 떨어지지 않고 포일을 유지한 채 완료한 회전을 “성공” 으로 봅니다. 트랙 편집으로 일부 구간을 제외해도, 성공률은 편집 전 세션 전체의 택·자이브를 분모로 삼습니다 — 제외한 구간에 든 실패 회전이 빠져 성공률이 부풀지 않게 하기 위함입니다.':
      'Share of attempts completed without touchdown. A maneuver counts as a "success" if the minimum speed during the turn stays above the foiling threshold and the foil is maintained. Even with track edits that exclude segments, the success rate is computed against all tacks/gybes from the full pre-edit session — so excluded failed maneuvers don’t inflate the rate.',
    'SOG = 속도(GPS 기준 실제 이동 속도). 높을수록 좋습니다. 풍상/풍하 × 포트/스타보드 택별로, 평균과 상위 50%·20%(높은 값 구간의 시간가중 평균)를 보여 줍니다 — 단일 GPS 포인트의 순간 극값(노이즈)은 쓰지 않습니다.':
      'SOG = speed over ground (GPS-derived actual travel speed). Higher is better. Shown per upwind/downwind × port/starboard tack, with the mean and Top 50% / Top 20% (time-weighted averages of the high-value bands). Single-point GPS extremes (noise) are not used.',
    'VMG = 풍상·풍하 유효속도(바람 축으로 다가가거나 멀어지는 속도). 풍상·풍하 모두 양수로 저장하므로 높을수록 좋습니다. 포트/스타보드 택별 상위 50%·20% 는 높은 값 구간의 시간가중 평균.':
      'VMG = velocity made good toward/away from the wind axis. Stored as a positive value for both upwind and downwind, so higher is better. Top 50% / Top 20% per port/starboard tack are time-weighted averages of the high-value bands.',
    'TWA = 보트 헤딩과 풍향이 이루는 각. 풍상은 작을수록 바람에 가깝게 포인팅이라 좋아 \'상위\'가 가장 좁은 각 쪽입니다. 풍하는 VMG 최적각이 약 140~150°이고 정풍하(180°)는 오히려 느려 중립으로 두고 크기가 큰(깊은) 각 쪽을 상위로 표시합니다. 포트/스타보드 택별로 나눠 좌우 포인팅 차이를 볼 수 있습니다.':
      'TWA = angle between boat heading and wind direction. Upwind: smaller is better (pointing closer to the wind), so "top" is the narrowest angle. Downwind: VMG optimum is around 140–150° and dead downwind (180°) is actually slower, so it’s treated as neutral and "top" is the deeper angle. Split by port/starboard tack to compare pointing left vs right.',
    '힐(Heel) = 보드 좌우 기울기. 택에 따라 부호가 갈리므로(한 택 −/반대 택 +) 포트·스타보드 버킷으로 나눠 부호 있는 실제 값을 보여 줍니다 — 포트(−)와 스타보드(+)의 크기가 비슷하면 좌우로 대칭되게 기운 것입니다. 평균·상위 50%/20% 는 각 버킷에서 더 크게 기운 구간의 시간가중 평균. 트림 특성이라 좋고 나쁨을 매기지 않습니다.':
      'Heel = lateral board tilt. Sign flips by tack (one tack negative, the other positive), so it’s split into port/starboard buckets and shown with signed values — when |port| ≈ |starboard|, you’re heeling symmetrically. Mean and Top 50% / Top 20% are time-weighted averages of the deeper-heel segments in each bucket. As a trim characteristic, no good/bad rating is applied.',
    '피치(Pitch·트림) = 보드 앞뒤 기울기. 포일링 중에는 대체로 뱃머리 들림(+) 한 방향이라 부호 그대로 평균합니다. 다른 지표처럼 풍상/풍하 × 포트/스타보드 버킷으로 나눠 좌우 택 차이를 함께 봅니다. 상위 50%·20% 는 뱃머리가 더 들린 구간. 트림 특성이라 좋고 나쁨을 매기지 않습니다. 자세 센서가 담긴 .vkx 에서만 표시.':
      'Pitch (trim) = fore-aft board tilt. While foiling it’s usually nose-up (+) consistently, so averaging keeps the sign. Like other metrics, split by upwind/downwind × port/starboard to compare tacks. Top 50% / Top 20% are the more-nose-up segments. As a trim characteristic, no good/bad rating. Only shown for .vkx files with attitude sensors.',
    '심박수(HR) = 센서 관측 심박. 좌우 택과 무관해 풍상/풍하로만 나눠, 위쪽 SOG 와 같은 풍상/풍하 구조로 나란히 봅니다 — 풍상·풍하에서 더 빠를 때 실제로 더 애쓰는지 비교할 수 있습니다. 평균은 시간가중, 상위 50%·20% 는 심박이 높은 구간의 시간가중 평균입니다 — 지속된 고심박 구간을 뜻하며 단일 순간 최고가 아닙니다. 신체 부하 참고 지표라 좋고 나쁨을 매기지 않습니다.':
      'Heart rate = sensor-observed HR. Independent of tack side, so it’s split only by upwind/downwind to align with the SOG split above — letting you compare whether you’re actually working harder when faster on each side. Mean is time-weighted; Top 50% / Top 20% are time-weighted averages of the high-HR bands — representing sustained high-HR segments, not a single peak. As a physical-load reference, no good/bad rating is applied.',
    '풍상·풍하 통계는 풍향 확정 후 주행 표본의 시간가중값입니다 (풍상 {up} · 풍하 {down} 기준).':
      'Upwind / downwind stats are time-weighted over riding samples after the wind is confirmed (upwind {up} · downwind {down}).',
    'SOG·VMG·TWA·힐·피치는 풍상/풍하 × 포트/스타보드 4 버킷으로 나눠 좌우 택 차이를 함께 봅니다(심박은 좌우 택과 무관해 분할하지 않고 풍상/풍하로만 나눔). 평균·상위 50%·상위 20% 세 구간을 두며, 평균은 그 방향(풍상/풍하)의 시간가중 평균, 상위 N% 는 시간가중 구간 평균(단일 GPS 포인트 노이즈 배제)입니다. \'상위\'는 지표의 좋은 방향 기준이며(SOG·VMG 높은 값, 풍상 TWA 좁은 각), 중립 지표는 크기가 큰 값 쪽입니다. 힐은 포트(−)·스타보드(+) 부호 그대로 표시합니다.':
      'SOG / VMG / TWA / Heel / Pitch are split into 4 buckets (upwind/downwind × port/starboard) to show tack differences. HR is independent of tack side, so it’s split only by upwind/downwind. Three tiers (Mean / Top 50% / Top 20%): mean is the time-weighted average for that direction; "Top N%" is the time-weighted average over the high-value band (excludes single-point GPS noise). "Top" follows each metric’s "good direction" — high values for SOG / VMG, narrow angle for upwind TWA; for neutral metrics, the deeper-magnitude side. Heel is shown with its native port (−) / starboard (+) sign.'
  };

  /* ============================================================
   * 상태 + 영속화
   * ============================================================ */
  var lang = 'ko';
  try {
    var stored = localStorage.getItem(STORE_KEY);
    if (stored === 'ko' || stored === 'en') lang = stored;
  } catch (e) { /* localStorage disabled */ }

  function getLang() { return lang; }

  function setLang(l) {
    if (l !== 'ko' && l !== 'en') return;
    if (l === lang) return;
    lang = l;
    try { localStorage.setItem(STORE_KEY, l); } catch (e) {}
    document.documentElement.setAttribute('lang', l === 'en' ? 'en' : 'ko');
    document.documentElement.setAttribute('data-rd-lang', l);
    /* 토글 버튼 상태 반영 */
    updateToggleButtons();
    /* 구독자(앱)가 재렌더하도록 알림 — RDDashboard.rerender() 등 */
    window.dispatchEvent(new CustomEvent('rd:langchange', { detail: { lang: l } }));
    /* 정적 DOM 즉시 번역 / 복원 */
    if (l === 'en') translateAll(document.body);
    else restoreAll(document.body);
  }

  /* ============================================================
   * T(ko, vars) — 호출부 변환 (캔버스·동적 보간 등)
   * ============================================================ */
  function T(ko, vars) {
    var s = (lang === 'en' && MAP[ko] != null) ? MAP[ko] : ko;
    if (vars) {
      Object.keys(vars).forEach(function (k) {
        s = s.split('{' + k + '}').join(String(vars[k]));
      });
    }
    return s;
  }

  /* ============================================================
   * DOM 자동 번역 / 복원
   * 매칭 단위 = 텍스트노드의 trimmed 전체 (부분 매치 X — 충돌 방지).
   * 원문은 textNode._rdOrig / element._rdOrigAttrs 에 보존.
   * ============================================================ */
  /* 메인 사이트 헤더·내비·트러스트바는 번역 범위 X (대시보드 영역만).
     `.site-header`, `.trust-bar`, 또는 [data-rd-i18n-skip] 안쪽은 건너뛴다. */
  function inSkipZone(node) {
    var el = node.nodeType === 1 ? node : node.parentElement;
    while (el && el !== document.body) {
      if (el.classList && (el.classList.contains('site-header') ||
          el.classList.contains('trust-bar'))) return true;
      if (el.hasAttribute && el.hasAttribute('data-rd-i18n-skip')) return true;
      el = el.parentElement;
    }
    return false;
  }

  /* 보간 동적 문자열용 정규식 패턴 — 'GPS 포인트 5,468개 전량 사용' 같이
     숫자/시간 등이 섞인 런타임 문자열을 패턴 매칭으로 번역. PATTERNS 끝의
     en 문자열은 $1·$2 백참조로 캡처 그룹을 끼워 넣는다 (Phase 2-C). */
  var PATTERNS = [
    { ko: /^GPS 포인트 ([\d,]+)개 전량 사용$/, en: 'GPS points: $1 (all used)' },
    { ko: /^편집 적용 ([\d,]+)개 분석$/, en: 'Edit applied — $1 points analyzed' },
    { ko: /^속도원: 기기 기록$/, en: 'Speed source: device record' },
    { ko: /^속도원: GPS 좌표 계산$/, en: 'Speed source: GPS-derived' },
    { ko: /^임계 ([\d.]+) (kt|km\/h) 이상$/, en: 'Threshold ≥ $1 $2' },
    { ko: /^전체 ([\dhms ]+)$/, en: 'Total $1' },
    { ko: /^편집됨 · (.+?) · 분석 길이 (.+)$/, en: 'Edited · $1 · analyzed length $2' },
    { ko: /^원본 전체 \((.+)\)$/, en: 'Full track ($1)' },
    { ko: /^앞 (.+?) 잘림$/, en: 'Trimmed front $1' },
    { ko: /^뒤 (.+?) 잘림$/, en: 'Trimmed back $1' },
    { ko: /^제외 (\d+)구간$/, en: '$1 excluded section(s)' },
    { ko: /^([\d.]+)% 비율$/, en: '$1% ratio' },
    { ko: /^오늘의 세션 속도 \((노트|km\/h)\)$/, en: 'Today’s session speed ($1)' },
    { ko: /^오늘의 세션 속도 \(노트\)$/, en: 'Today’s session speed (knots)' },
    { ko: /^✓ 풍향 (\d+)° \((.+?)\) 확정 — 택킹\/자이빙·VMG·폴라에 반영되었습니다\.$/,
      en: '✓ Wind direction $1° ($2) confirmed — tack / gybe, VMG and polar updated.' },
    { ko: /^✓ 풍향 (\d+)° \((.+?)\) 확정$/, en: '✓ Wind $1° ($2) confirmed' },
    { ko: /^풍향 (\d+)° \((.+?)\) · (.+)$/, en: 'Wind $1° ($2) · $3' },
    { ko: /^✦ 권장 추정값 (\d+)° \((.+?)\) · 신뢰도 (.+?) — (.+) 다이얼·슬라이더로 보정 후 “확정”을 누르세요\.$/,
      en: '✦ Recommended estimate $1° ($2) · confidence $3 — $4 Adjust via dial / slider, then tap "Confirm".' },
    { ko: /^권장 추정값 (\d+)° \((.+?)\) · 신뢰도 (.+?) — (.+) 다이얼·슬라이더로 보정 후 “확정”을 누르세요\.$/,
      en: 'Recommended estimate $1° ($2) · confidence $3 — $4 Adjust via dial / slider, then tap "Confirm".' },
    { ko: /^추정값 (\d+)° \((.+?)\) 을\(를\) 미리보기에 적용했습니다 — 다이얼로 보정 후 “확정”을 누르세요\.$/,
      en: 'Applied estimate $1° ($2) to preview — adjust via dial, then tap "Confirm".' },
    { ko: /^신뢰도 (.+)$/, en: 'Confidence $1' },
    { ko: /^무항주 구역 폭 (\d+)°$/, en: 'No-go zone width $1°' },
    { ko: /^그리드 정렬도 ([\d.]+)$/, en: 'Grid alignment $1' },
    { ko: /^회전 (\d+)개$/, en: '$1 maneuvers' },
    { ko: /^추정 분산 ([\d.]+)°$/, en: 'Spread $1°' },
    { ko: /^풍상·풍하 판정 여유 ([\d.]+)%p$/, en: 'Upwind / downwind margin $1%p' },
    { ko: /^✗ (.+)$/, en: '✗ $1' },
    { ko: /^⚠ (.+)$/, en: '⚠ $1' },
    { ko: /^✓ (.+)$/, en: '✓ $1' },
    { ko: /^▾ 소스 접기$/, en: '▾ Collapse sources' },
    { ko: /^▸ 소스 펴기$/, en: '▸ Expand sources' },
    { ko: /^(\d+) \/ (\d+)회 성공 · 세션 전체 기준$/, en: '$1 / $2 success · whole-session basis' },
    { ko: /^(\d+) \/ (\d+)회 성공$/, en: '$1 / $2 success' },
    { ko: /^(\d+) times$/, en: '$1 times' },
    { ko: /^(\d+)회$/, en: '$1 times' },
    { ko: /^(\d+)점$/, en: '$1 pts' },
    { ko: /^(\d+) score$/, en: '$1 score' },
    { ko: /^총 (\d+)회 중 (\d+)회 표시$/, en: 'Showing $2 of $1 total' },
    { ko: /^택킹 (\d+)회 중 (\d+)회 표시$/, en: 'Showing $2 of $1 tacks' },
    { ko: /^자이빙 (\d+)회 중 (\d+)회 표시$/, en: 'Showing $2 of $1 gybes' },
    { ko: /^(택킹|자이빙) (\d+)회 — 포트 (\d+) · 스타보드 (\d+) 좌우 분할 비교 \(Y축 동일 스케일\)$/,
      en: '$1 ×$2 — Port $3 · Starboard $4 split comparison (same Y-axis)' },
    { ko: /^(.+?) (\d+)회 겹쳐 보기 — 개별 곡선\(연한 선\) \+ 평균\(굵은 선\) \+ ±1σ 밴드$/,
      en: '$1 ×$2 overlaid — individual (light) + mean (bold) + ±1σ band' },
    { ko: /^(택킹|자이빙) (\d+)회$/, en: '$1 × $2' },
    { ko: /^(포트|스타보드) ([\d.]+)$/, en: '$1 $2' },
    { ko: /^임계 ([\d.]+) (kt|km\/h)/, en: 'Threshold $1 $2' },
    { ko: /^예: (.+)$/, en: 'e.g. $1' },
    { ko: /^심박이 함께 기록된 (택킹|자이빙|회전)$/, en: '$1 with HR' },
    { ko: /^심박이 함께 기록된 택킹·자이빙$/, en: 'Tacks / gybes with HR' },
    { ko: /^회복 표본 (\d+)회 평균 · 클수록 빠른 회복$/, en: 'Avg of $1 recovery samples — higher = faster recovery' },
    { ko: /^기록 포인트 ([\d,]+)개 중 심박 ([\d,]+)개$/, en: '$2 HR samples among $1 recorded points' },
    { ko: /^(.+) · 순항 대비$/, en: '$1 · vs cruise HR' },
    { ko: /^입력하신 최대 심박수 (\d+) bpm 기준으로 존을 나눕니다\.$/,
      en: 'Zones based on your max HR of $1 bpm.' },
    { ko: /^미입력 — 세션 관측 최대값 (\d+) bpm 을 기준으로 합니다\. 본인의 최대 심박수를 입력하시면 더 정확해집니다\.$/,
      en: 'Not entered — using session-observed max of $1 bpm. Enter your max HR for higher accuracy.' },
    { ko: /^타깃 = 저장된 세션 (\d+)개의 TWA별 개인 베스트\(지속 속도 95퍼센타일\)입니다\.$/,
      en: 'Target = personal-best per TWA bin (sustained-speed 95th percentile) across $1 saved sessions.' },
    { ko: /^✦ 권장 추정값 (\d+)° \((.+?)\) · 신뢰도 (.+?) — (.+)$/,
      en: '✦ Recommended estimate $1° ($2) · confidence $3 — $4' },
    { ko: /^주행의 (\d+)%만 타깃 보유$/, en: '$1% of sailing has target coverage' },
    { ko: /^점선 빈 (\d+)개\(표본 없음·보간 추정\)$/,
      en: '$1 dashed bins (no samples — interpolated)' },
    { ko: /^연한 점 빈 (\d+)개\(표본 60초 미만\)$/,
      en: '$1 faint-dot bins (under 60s samples)' },
    { ko: /^선택 (\d+)회 · (.+)$/, en: 'Selected $1 · $2' },
    { ko: /^(\d+) 선택$/, en: '$1 selected' },
    { ko: /^표본 (\d+)$/, en: '$1 samples' },
    { ko: /^표본 P (\d+)개 · S (\d+)개$/, en: 'Samples P $1 · S $2' },
    { ko: /^([\d.]+) 비교$/, en: '$1 compared' },
    { ko: /^주행의 ([\d.]+)%만 타깃 보유$/, en: '$1% of sailing has target coverage' },
    { ko: /^(\d+) ?(min|sec|sec|초|분) 비교$/, en: '$1 $2 compared' },
    { ko: /^([\d.]+) 분 \((.+?) ~ (.+?)\)$/, en: '$1 min ($2 — $3)' },
    /* 세션 헤더 source 문자열 — '속도원: GPS 좌표 계산 · GPS 포인트 N개 전량 사용 · 편집 적용 M개 분석' */
    { ko: /^(속도원: .+?) · (GPS 포인트 [\d,]+개 전량 사용)$/, en: '$1 · $2' },
    { ko: /^(속도원: .+?) · (GPS 포인트 [\d,]+개 전량 사용) · (편집 적용 [\d,]+개 분석)$/,
      en: '$1 · $2 · $3' },
    { ko: /^풍상·풍하 통계는 풍향 확정 후 주행 표본의 시간가중값입니다 \(풍상 (.+?) · 풍하 (.+?) 기준\)\.$/,
      en: 'Upwind / downwind stats are time-weighted over riding samples after the wind is confirmed (upwind $1 · downwind $2).' },
    { ko: /^타깃 = 저장된 세션 (\d+)개의 TWA별 개인 베스트.*\.$/,
      en: 'Target = personal-best per TWA bin (sustained-speed 95th percentile) across $1 saved sessions.' },
    { ko: /^그래프 중간의 옅은 띠는 GPS 장치가 8초 넘게 기록을 멈춘 시간대\(또는 트랙 편집에서 제외한 구간\)입니다 — 이 세션 (\d+)곳\..+$/,
      en: 'The faint bands in the chart mark gaps where the GPS device paused for over 8s (or excluded sections from track editing) — $1 in this session. "HR coverage" measures HR-attached share of recorded points, so it can still be near 100% even with such time gaps — they measure different things.' },
    { ko: /^심박 효율 지수 = 주행 평균 속도\(.+?\) ÷ 평균 심박\(bpm\) × 100 입니다\..*$/,
      en: 'HR efficiency index = sailing avg speed ÷ avg HR × 100. Higher = faster at the same HR — better aerobic efficiency. Watching this rise across sessions signals improving fitness. In the scatter below, points lower (lower HR at the same speed) indicate better efficiency.' },
    { ko: /^심박 드리프트는 활주 구간의 후반 평균 심박이 전반보다.*$/,
      en: 'HR drift = late-half average HR minus early-half during active riding — closer to 0 means you held the same effort to the end.' },
    { ko: /^✓ 회전 직전\(4초 평균\)보다 최저 속도가 더 빠릅니다 — 속도를 잃지 않고 오히려 가속하며 빠져나온 좋은 회전입니다\..*$/,
      en: '✓ Minimum speed exceeded the pre-entry (4-second average) — a strong maneuver that accelerated through rather than losing speed. Loss is computed against the faster of entry/exit ($1).' }
  ];

  function applyPatterns(s) {
    for (var i = 0; i < PATTERNS.length; i++) {
      var m = s.match(PATTERNS[i].ko);
      if (m) {
        return PATTERNS[i].en.replace(/\$(\d+)/g, function (_, n) {
          return m[+n] != null ? m[+n] : '';
        });
      }
    }
    return null;
  }

  function translateTextNode(n) {
    var v = n.nodeValue;
    if (v == null) return;
    var trimmed = v.replace(/^\s+|\s+$/g, '');
    if (!trimmed) return;
    if (inSkipZone(n)) return;
    var out = (MAP[trimmed] != null) ? MAP[trimmed] : applyPatterns(trimmed);
    if (out == null) return;
    if (out === trimmed) return;   // 동일 → 무한 mutation 루프 방지
    if (n._rdOrig == null) n._rdOrig = v;
    var lead = v.match(/^\s*/)[0], trail = v.match(/\s*$/)[0];
    n.nodeValue = lead + out + trail;
  }
  function restoreTextNode(n) {
    if (n._rdOrig != null) {
      n.nodeValue = n._rdOrig;
      n._rdOrig = null;
    }
  }

  var ATTRS = ['title', 'aria-label', 'placeholder', 'alt'];
  function translateAttrs(el) {
    if (!el || !el.hasAttribute) return;
    if (inSkipZone(el)) return;
    ATTRS.forEach(function (a) {
      if (!el.hasAttribute(a)) return;
      var v = el.getAttribute(a);
      var trimmed = (v || '').replace(/^\s+|\s+$/g, '');
      if (!trimmed) return;
      var out = (MAP[trimmed] != null) ? MAP[trimmed] : applyPatterns(trimmed);
      if (out == null) return;
      if (out === trimmed) return;
      if (!el._rdOrigAttrs) el._rdOrigAttrs = {};
      if (el._rdOrigAttrs[a] == null) el._rdOrigAttrs[a] = v;
      var lead = v.match(/^\s*/)[0], trail = v.match(/\s*$/)[0];
      el.setAttribute(a, lead + out + trail);
    });
  }
  function restoreAttrs(el) {
    if (!el || !el._rdOrigAttrs) return;
    Object.keys(el._rdOrigAttrs).forEach(function (a) {
      el.setAttribute(a, el._rdOrigAttrs[a]);
    });
    el._rdOrigAttrs = null;
  }

  function walkTextNodes(root, fn) {
    if (!root) return;
    var w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var n;
    while ((n = w.nextNode())) fn(n);
  }
  function walkElements(root, fn) {
    if (!root) return;
    if (root.nodeType === 1) fn(root);
    var els = root.querySelectorAll ? root.querySelectorAll('*') : [];
    for (var i = 0; i < els.length; i++) fn(els[i]);
  }

  function translateAll(root) {
    walkTextNodes(root, translateTextNode);
    walkElements(root, translateAttrs);
  }
  function restoreAll(root) {
    walkTextNodes(root, restoreTextNode);
    walkElements(root, restoreAttrs);
  }

  /* ============================================================
   * MutationObserver — 동적으로 들어온 노드도 자동 번역(en 일 때)
   * ============================================================ */
  var observerStarted = false;
  function startObserver() {
    if (observerStarted || !document.body) return;
    observerStarted = true;
    var obs = new MutationObserver(function (muts) {
      if (lang !== 'en') return;
      for (var i = 0; i < muts.length; i++) {
        var m = muts[i];
        if (m.type === 'childList') {
          m.addedNodes.forEach(function (n) {
            if (n.nodeType === 1) translateAll(n);
            else if (n.nodeType === 3) translateTextNode(n);
          });
        } else if (m.type === 'characterData') {
          translateTextNode(m.target);
        } else if (m.type === 'attributes') {
          translateAttrs(m.target);
        }
      }
    });
    obs.observe(document.body, {
      childList: true, subtree: true, characterData: true,
      attributes: true, attributeFilter: ATTRS
    });
  }

  /* ============================================================
   * 토글 버튼 설치 — body 안 어디든 [data-rd-lang-btn] 자동 결선
   * ============================================================ */
  function updateToggleButtons() {
    var btns = document.querySelectorAll('[data-rd-lang-btn]');
    for (var i = 0; i < btns.length; i++) {
      var l = btns[i].getAttribute('data-rd-lang-btn');
      btns[i].setAttribute('aria-pressed', l === lang ? 'true' : 'false');
      if (l === lang) btns[i].classList.add('is-on');
      else btns[i].classList.remove('is-on');
    }
  }
  function setupToggle() {
    var btns = document.querySelectorAll('[data-rd-lang-btn]');
    for (var i = 0; i < btns.length; i++) {
      (function (b) {
        var l = b.getAttribute('data-rd-lang-btn');
        b.addEventListener('click', function () { setLang(l); });
      })(btns[i]);
    }
    updateToggleButtons();
  }

  /* ============================================================
   * 부팅
   * ============================================================ */
  /* 토글 UI CSS — 외부 css 파일 의존 없이 self-contained 주입 */
  function injectStyle() {
    if (document.getElementById('rd-i18n-style')) return;
    var css =
      '.rd-langtoggle{position:fixed;top:8px;right:8px;z-index:9999;' +
        'display:inline-flex;background:#FFFFFFE6;border:1px solid #C7CFD8;' +
        'border-radius:999px;padding:2px;box-shadow:0 2px 8px rgba(10,37,64,0.08);' +
        'font:600 12px system-ui,-apple-system,sans-serif;backdrop-filter:blur(6px)}' +
      '.rd-langtoggle__btn{appearance:none;border:0;background:transparent;' +
        'color:#5C6F7E;padding:5px 12px;border-radius:999px;cursor:pointer;' +
        'min-width:54px;letter-spacing:.01em;line-height:1;transition:all .12s ease}' +
      '.rd-langtoggle__btn:hover{color:#0A2540}' +
      '.rd-langtoggle__btn.is-on{background:#0A2540;color:#FFFFFF;' +
        'box-shadow:0 1px 3px rgba(10,37,64,0.18)}' +
      '@media (max-width:540px){.rd-langtoggle{top:6px;right:6px}' +
        '.rd-langtoggle__btn{padding:5px 10px;min-width:46px;font-size:11px}}';
    var s = document.createElement('style');
    s.id = 'rd-i18n-style';
    s.textContent = css;
    document.head.appendChild(s);
  }

  function init() {
    document.documentElement.setAttribute('data-rd-lang', lang);
    if (lang === 'en') document.documentElement.setAttribute('lang', 'en');
    injectStyle();
    setupToggle();
    startObserver();
    if (lang === 'en') translateAll(document.body);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  /* ============================================================
   * 공개 API
   * ============================================================ */
  global.RDI18n = {
    T: T, getLang: getLang, setLang: setLang,
    MAP: MAP,
    translateNode: function (n) { if (lang === 'en') translateAll(n); },
    restoreNode: function (n) { restoreAll(n); }
  };
})(typeof window !== 'undefined' ? window : globalThis);
