/* Korean presentation adapter. Text/labels only; never rewrites values, IDs or analysis data. */
(function(){'use strict';
const norm=s=>s.replace(/\s+/g,' ').trim();
const dictionary=Object.create(null);
Object.entries((window.RDI18n||{}).MAP||{}).forEach(([ko,en])=>{if(typeof en==='string'&&/[A-Za-z]/.test(en)&&!en.includes('{'))dictionary[norm(en)]=ko;});
Object.assign(dictionary,{"Performance score":"조건 대비 세션 점수","Top speed":"최고 속도","Avg speed":"평균 속도","Foiling time":"포일링 시간","speed 70% + turns 30%":"주행 70% + 회전 30%","Re-estimate from track":"주행 기록으로 다시 추정","Confirm the wind direction":"풍향을 확인하세요","set this first — every tack, VMG and polar is measured against it":"풍향을 먼저 설정하세요. 택·VMG·폴라 분석의 기준입니다.","Arrows point the way the wind blows. Drag the slider until they line up with how the session felt — upwind legs should sit either side of the arrows.":"화살표는 바람이 불어가는 방향입니다. 당시 체감한 풍향과 맞도록 슬라이더를 조절하세요. 풍상 주행 구간은 화살표의 양쪽에 놓입니다.","sign out":"로그아웃", "sign in":"로그인", "Used by the performance score":"퍼포먼스 점수 계산에 사용합니다", "Riding Dashboard": "라이딩 분석 대시보드", "Upload files": "기록 파일 업로드", "Loading session…": "라이딩 기록을 불러오는 중…", "No comparison": "비교 안 함", "▶ Replay": "▶ 라이딩 재생", "Save session": "라이딩 기록 저장", "Old dashboard": "이전 대시보드", "Weight (kg)": "체중 (kg)", "Wing (m²)": "윙 크기 (m²)", "Skill": "라이딩 수준", "Novice": "입문", "Beginner": "초급", "Intermediate": "중급", "Advanced": "상급", "Advanced-Pro": "상급·선수 준비", "Pro": "선수", "Wind speed (kt)": "풍속 (kt)", "Recalculate": "다시 분석", "Condition": "라이딩 조건", "Performance": "퍼포먼스", "Track": "주행 경로", "Turns": "회전 분석", "Attitude": "장비 기울기", "Coach": "코칭", "Physiology": "신체·운동 지표", "Sessions": "라이딩 기록", "Training load": "훈련 부하", "Best speed by duration": "지속 시간별 최고 속도", "knots · duration on a log scale": "속도: 노트 · 지속 시간: 로그 눈금", "Time at speed": "속도 구간별 주행 시간", "minutes": "분", "Session timeline": "라이딩 타임라인", "drag to select a range · one shared time axis": "드래그하여 구간 선택 · 같은 시간축으로 비교", "Speed": "속도", "Wind shift": "풍향 변화", "Tack": "택킹", "Gybe": "자이빙", "Turn loss": "회전 손실", "Map": "지도", "Satellite": "위성 지도", "Type": "유형", "Count": "횟수", "Speed loss": "속도 손실", "Recovery": "회복", "Efficiency": "효율", "Success": "성공률", "Light": "밝은 화면", "Dark": "어두운 화면", "Switch between light and dark": "밝은 화면·어두운 화면 전환", "No time data": "시간 정보 없음", "Could not load the sample session": "샘플 라이딩 기록을 불러오지 못했습니다", "Wind direction": "풍향", "Confirm wind": "풍향 확정", "Equipment": "장비", "Sea condition": "해상 상태", "Body condition": "신체 상태", "Save": "저장", "Cancel": "취소", "Delete": "삭제", "Close": "닫기", "Apply": "적용", "Reset": "초기화", "Compare": "비교", "Duration": "주행 시간", "Distance": "거리", "Max speed": "최고 속도", "Average speed": "평균 속도", "Upwind": "풍상", "Downwind": "풍하", "Session": "라이딩 기록", "Notes": "메모", "Heart rate": "심박수", "Wind": "바람", "Board": "보드", "Foil": "포일", "Wing": "윙", "Date": "날짜", "Name": "이름", "Sample": "샘플", "Load": "불러오기", "Export": "내보내기", "Settings": "설정", "Personal best": "개인 최고 기록", "Moving time": "이동 시간", "Total time": "전체 시간", "Sea state": "해상 상태", "Flat": "평수면", "Chop": "잔파도", "Waves": "파도", "Unknown": "알 수 없음", "Not set": "미설정", "Confirmed": "확정됨", "Estimated": "추정값", "Manual": "직접 입력", "Auto": "자동", "Edit": "수정", "Saved": "저장됨", "No data": "데이터 없음", "Import": "가져오기", "Clear": "지우기", "Both panels show the same seven numbers — the curve gives the shape, the table the exact values. The 2 s and 10 s points come from time windows; the rest are your best 100 m, 250 m, 500 m and 1 NM converted to how long they took. Duration runs on a log scale so a two-second burst and a two-minute run fit in one view. Alpha 500 sits off the curve because it is a gated course — 500 m out and back inside a 50 m gate — so it measures a speed you can turn around from, not a straight-line best.": "그래프와 표는 같은 7가지 기록을 보여줍니다. 2초·10초는 해당 시간 동안의 최고 기록이며, 100m·250m·500m·1해리는 구간 기록을 소요 시간으로 환산합니다. 시간축은 짧은 가속과 긴 주행을 함께 볼 수 있도록 로그 눈금을 사용합니다. 알파 500은 총 500m를 주행하며 출발·도착 지점이 50m 이내인 회항 기록으로, 직선 최고 속도와 구분합니다.", "Where your riding time actually went. The left-hand bars are time on the water below foiling speed — starts, stops, drifting and touchdowns — so a tall bar there is not a slow session, it is time not yet spent riding.": "라이딩 시간을 어느 속도 구간에서 보냈는지 보여줍니다. 왼쪽 막대는 출발·정지·표류·착수 등 포일링 속도보다 느린 구간입니다. 이 막대가 높다고 라이딩 자체가 느렸다는 뜻은 아닙니다."});

Object.assign(dictionary,{
  "Gear": "장비",
  "Sea": "해상 상태",
  "Body": "신체 상태",
  "Wind direction (°)": "풍향 (°)",
  "Use this direction": "이 풍향 적용",
  "The part you rode": "실제 라이딩 구간",
  "Restore full track": "전체 경로 복원",
  "Exclude this range": "선택 구간 제외",
  "No turns detected": "감지된 회전 없음",
  "No series": "시계열 데이터 없음",
  "No track loaded.": "주행 기록을 먼저 불러오세요.",
  "Could not draw the track chart.": "주행 그래프를 표시하지 못했습니다.",
  "Water state": "수면 상태",
  "Save to this session": "이 라이딩 기록에 저장",
  "Gear for this session": "이날 사용한 장비",
  "Your gear today": "오늘 사용할 장비",
  "Front wing": "프런트 포일",
  "Rear wing": "리어 포일",
  "Hand wing": "핸드윙",
  "Mast": "마스트",
  "Harness": "하네스",
  "Take-off speed": "이륙 속도",
  "Heel available": "허용 힐 각도",
  "Side force you can hold": "버틸 수 있는 횡력",
  "All-up weight": "라이더·장비 총중량",
  "set by foil area": "포일 면적 기준",
  "before the foil tip surfaces": "포일 끝이 수면 위로 나오기 전",
  "before the wing tip catches": "윙 끝이 수면에 닿기 전",
  "you and the rig, leaning in line": "라이더와 장비가 함께 기울어진 상태",
  "foil area sets take-off, spans set how far you can heel": "포일 면적은 이륙 속도, 폭은 허용 힐 각도를 결정합니다.",
  "what you rode — foil area sets take-off, spans set how far you can heel": "이날 사용한 장비를 선택하세요. 면적과 폭이 이륙 속도와 허용 기울기를 결정합니다.",
  "the water that day": "이날의 수면 상태",
  "cut out what was not riding — everything else in the dashboard is recomputed without it": "라이딩하지 않은 구간을 제외하면 모든 분석에 반영됩니다.",
  "drag across the chart, then Exclude this range": "차트를 드래그한 뒤 ‘선택 구간 제외’를 누르세요.",
  "No session": "라이딩 기록 없음",
  "Not saved yet": "아직 저장하지 않음",
  "Not in saved list": "저장 목록에 없음",
  "Save failed": "저장 실패",
  "Save failed.": "저장하지 못했습니다.",
  "Saved": "저장됨",
  "saved": "저장됨",
  "blocked": "다운로드 차단됨",
  "Loading…": "불러오는 중…",
  "Loading...": "불러오는 중…",
  "Not enough data": "데이터 부족",
  "not enough data": "데이터 부족",
  "Not enough points": "측정 지점 부족",
  "Needs a wind direction": "풍향 설정이 필요합니다.",
  "Mark by mark": "부표별 비교",
  "Mark to mark": "부표 사이 구간 비교",
  "Race": "경기",
  "Exit spread": "탈출 속도 차이",
  "speed in → lowest → out, kt": "진입 → 최저 → 탈출 속도 (kt)",
  "seconds · average kt, rounding to rounding": "부표 회전 사이의 시간(초) · 평균 속도(kt)",
  "This file contains no heart-rate data.": "이 파일에는 심박수 데이터가 없습니다.",
  "Heart rate over the session": "라이딩 중 심박수",
  "Time in heart-rate zones": "심박 구간별 시간",
  "Turn effort & recovery": "회전 시 운동 강도·회복",
  "Resting heart rate": "안정 시 심박수",
  "Resting heart rate (bpm)": "안정 시 심박수 (bpm)",
  "HRV (rMSSD or SDNN) (ms)": "심박변이도 (rMSSD 또는 SDNN, ms)",
  "Sleep (h)": "수면 시간 (h)",
  "Sleep": "수면",
  "Fatigue": "피로",
  "Stress": "스트레스",
  "Soreness": "근육통",
  "Muscle soreness": "근육통",
  "Sleep quality": "수면의 질",
  "How you feel today": "오늘의 신체 상태",
  "입력하는 즉시 저장됩니다 — saved as you type, no button needed.": "입력 즉시 날짜별로 자동 저장됩니다.",
  "saved on this browser": "이 브라우저에 저장됨",
  "Training history": "훈련 이력",
  "Your profile": "라이더 프로필",
  "your profile": "라이더 프로필",
  "this session": "이 라이딩 기록",
  "carried over": "이전 입력값",
  "from gear": "장비 기준",
  "Age": "나이",
  "Sex": "성별",
  "Male": "남성",
  "Female": "여성",
  "Height (cm)": "키 (cm)",
  "Weight with wetsuit (kg)": "슈트 포함 체중 (kg)",
  "Resting HR": "안정 시 심박수",
  "Max HR": "최대 심박수",
  "Average HR": "평균 심박수",
  "Workout": "운동 기록",
  "Add workout": "운동 기록 추가",
  "Activity": "운동 종류",
  "Intensity": "강도",
  "Easy": "가볍게",
  "Moderate": "보통",
  "Hard": "강하게",
  "Very hard": "매우 강하게",
  "Low": "낮음",
  "Medium": "보통",
  "High": "높음",
  "low": "낮음",
  "medium": "보통",
  "high": "높음",
  "Fitness": "체력",
  "Freshness": "회복 여유",
  "Readiness": "운동 준비도",
  "Load balance": "훈련 부하 균형",
  "Weekly load": "주간 훈련 부하",
  "Daily load": "일일 훈련 부하",
  "Acute load": "단기 훈련 부하",
  "Chronic load": "장기 훈련 부하",
  "No workouts yet": "운동 기록 없음",
  "Import wellness CSV": "컨디션 CSV 가져오기",
  "Choose CSV": "CSV 선택",
  "Import CSV": "CSV 가져오기",
  "Download template": "양식 다운로드",
  "Session history": "라이딩 이력",
  "Saved sessions": "저장한 라이딩 기록",
  "Open": "열기",
  "Remove": "삭제",
  "Rename": "이름 변경",
  "Add gear": "장비 기록 추가",
  "add gear": "장비 기록 추가",
  "All sessions": "전체 라이딩 기록",
  "My sessions": "내 라이딩 기록",
  "Guest sessions": "게스트 라이딩 기록",
  "All": "전체",
  "None": "없음",
  "No comparison": "비교 안 함",
  "Select a session": "라이딩 기록 선택",
  "Refresh": "새로고침",
  "Retry": "다시 시도",
  "Download": "다운로드",
  "Replay": "라이딩 재생",
  "Play": "재생",
  "Pause": "일시 정지",
  "Stop": "정지",
  "Playback speed": "재생 속도",
  "Video": "영상",
  "Choose video": "영상 선택",
  "Add video": "영상 추가",
  "Sync": "동기화",
  "Offset": "시간 오프셋",
  "Full screen": "전체 화면",
  "Exit fullscreen": "전체 화면 종료",
  "Follow": "따라가기",
  "Follow rider": "라이더 따라가기",
  "Reset view": "화면 초기화",
  "Port": "포트",
  "Starboard": "스타보드",
  "port": "포트",
  "starboard": "스타보드",
  "Heading": "진행 방향",
  "Heel": "좌우 기울기",
  "Pitch": "앞뒤 기울기",
  "Roll": "롤",
  "Yaw": "요",
  "VMG": "VMG",
  "TWA": "TWA",
  "Apparent wind": "겉보기 바람",
  "Wind direction sources": "풍향 추정 근거",
  "Source": "출처",
  "Confidence": "신뢰도",
  "Method": "방법",
  "Result": "결과",
  "Details": "자세히 보기",
  "Summary": "요약",
  "Recommendation": "추천",
  "Recommendations": "추천",
  "Sailing Performance Score": "라이딩 퍼포먼스 점수",
  "Speed 70%": "속도 70%",
  "Turns 30%": "회전 30%",
  "partial — turn data missing": "일부 점수 — 회전 데이터 부족",
  "Enter weight, wing size and wind speed above.": "체중·윙 크기·풍속을 입력하세요.",
  "Downwind is where the wing runs out": "풍하에서 부족해지는 윙 파워",
  "Apparent wind upwind": "풍상 겉보기 풍속",
  "Apparent wind downwind": "풍하 겉보기 풍속",
  "Wing force downwind": "풍하 윙 힘",
  "of what it gets upwind": "풍상에서 받는 힘 대비",
  "So size for downwind, not for upwind comfort": "풍하에서 필요한 힘을 기준으로 윙 크기를 판단하세요.",
  "Predicted upwind VMG by wing size": "윙 크기별 예상 풍상 VMG",
  "Relationship": "관계",
  "Steadiest 25%": "가장 안정적인 25%",
  "Roughest 25%": "가장 불안정한 25%",
  "Difference": "차이",
  "no separation": "차이 없음",
  "Used by the performance score — saved with this session.": "퍼포먼스 계산에 사용하며 이 라이딩 기록에 저장했습니다.",
  "Used by the performance score — restored from this session.": "이 라이딩 기록에서 불러온 값으로 퍼포먼스를 계산합니다.",
  "Session title — click to rename": "라이딩 제목 — 클릭하여 변경",
  "Enter your weight (with wetsuit) in the Training load tab to see what this setup can hold.": "훈련 부하 탭에서 슈트 포함 체중을 입력하면 장비 조합의 한계를 확인할 수 있습니다.",
  "Four questions, five seconds. This is the Hooper index — the standard subjective wellness measure in sports science, and the single cheapest thing you can add to a recovery decision. Without it the training-load suggestion is made on load alone.": "수면·피로·스트레스·근육통을 기록하는 주관적 컨디션 지표입니다. 회복 상태를 판단하는 데 참고하며, 입력하지 않으면 훈련 부하만으로 제안합니다.",
  "Not enough upwind sailing on both tacks at this direction to judge.": "이 풍향에서는 양쪽 택의 풍상 주행 데이터가 부족하여 판단하기 어렵습니다.",
  "This is the direction that makes your port and starboard upwind angles match. It is a check, not proof: if one tack is genuinely weaker, this will quietly absorb that into the wind.": "양쪽 택의 풍상 각도가 비슷해지는 풍향입니다. 한쪽 택의 실력 차이도 풍향 차이로 해석될 수 있으므로 참고용으로 확인하세요.",
  "This session is not saved yet — press \"Save session\" in the header first, then these inputs stay with it.": "먼저 상단에서 라이딩 기록을 저장하면 이 입력값도 함께 보관할 수 있습니다.",
  "This session is no longer in your saved list — it may have been deleted. Press \"Save session\" in the header to store it again.": "저장 목록에서 찾을 수 없는 라이딩 기록입니다. 상단의 저장 버튼으로 다시 저장하세요.",
  "Nothing logged yet. Save a ride, or add a land workout below.": "기록이 없습니다. 라이딩을 저장하거나 아래에서 지상 운동을 추가하세요.",
  "Save a session after entering resting heart rate and sex, and it will appear here.": "안정 시 심박수와 성별을 입력한 뒤 라이딩을 저장하면 이곳에 표시됩니다."
});
Object.assign(dictionary,{
  "Wind not resolved.": "풍향을 확인하지 못했습니다.",
  "velocity made good": "목표 방향 유효 속도",
  "Polar": "폴라 그래프",
  "top 5% speed per angle": "각도별 상위 5% 속도",
  "Storage module unavailable.": "저장 기능을 사용할 수 없습니다.",
  "Your numbers": "라이더 기본 정보",
  "shared with the old dashboard": "이전 대시보드와 공유됩니다.",
  "used by the load coefficient only": "훈련 부하 계수 계산에만 사용합니다.",
  "Rides need a few numbers before they carry a load": "훈련 부하 계산에 기본 정보가 필요합니다.",
  "No rides carry a load yet": "훈련 부하가 기록된 라이딩이 없습니다.",
  "Fitness, fatigue and form": "체력·피로·컨디션",
  "Log a land workout": "지상 운동 기록",
  "anything that is not sailing": "라이딩 외 운동",
  "Import from your watch or ring": "워치·링 기록 가져오기",
  "Could not read that file": "파일을 읽지 못했습니다.",
  "this browser only": "이 브라우저에만 저장",
  "Heart-rate recovery": "심박수 회복",
  "drop 60 s after a hard patch": "고강도 구간 종료 60초 후 감소폭",
  "What to do today": "오늘의 훈련 제안",
  "If you cannot get on the water": "물에 나갈 수 없는 날",
  "Load ledger": "훈련 부하 기록",
  "newest first": "최신순",
  "auto": "자동",
  "Was the wind about where, or about when?": "바람 변화가 위치 때문인가요, 시간 때문인가요?",
  "distance along the wind axis": "풍향 축을 따른 거리",
  "Bin table": "구간별 집계표",
  "all": "전체",
  "Polar by wind strength": "풍속별 폴라 그래프",
  "Show the numbers": "수치 보기",
  "sessions": "라이딩 기록",
  "Relationships": "지표 간 관계",
  "Fewer than five windows match — nothing worth fitting a line through.": "조건에 맞는 구간이 5개 미만이므로 추세를 판단하기 어렵습니다.",
  "Target band": "목표 범위",
  "not enough history": "누적 기록 부족",
  "Today, best 30%": "오늘의 상위 30%",
  "used": "분석에 사용",
  "Best speed splits": "구간별 최고 속도",
  "best sustained average": "지속 구간 최고 평균",
  "Fast runs": "고속 주행 구간",
  "No sustained runs above the threshold.": "기준 속도를 유지한 구간이 없습니다.",
  "Performance statistics": "퍼포먼스 통계",
  "Metric": "지표",
  "Direction": "방향",
  "Move to my sessions": "내 라이딩 기록으로 이동",
  "mine": "내 기록",
  "rename": "이름 변경",
  "No saved sessions yet. Use \"Save session\" in the header to start building a season trend.": "저장한 라이딩이 없습니다. 상단에서 저장하면 시즌 추세를 확인할 수 있습니다.",
  "summary only": "요약만 보관",
  "· added later": "· 나중에 추가함",
  "guest": "게스트",
  "Season trend": "시즌 추세",
  "Heart rate distribution": "심박수 분포",
  "Speed vs heart rate": "속도와 심박수",
  "each dot = one sample window": "점 하나는 한 측정 구간입니다.",
  "none": "없음",
  "Every turn": "전체 회전 기록",
  "Which way you turn": "회전 방향",
  "entry tack → exit tack": "진입 택 → 탈출 택",
  "How the foiling was strung together": "포일링의 연결 흐름",
  "Tack bias — port against starboard": "포트·스타보드 택 편차",
  "Diff": "차이",
  "Read this one against your wind direction": "설정한 풍향을 기준으로 확인하세요.",
  "Downwind VMG is not clearly above upwind — read these numbers with care": "풍하 VMG가 풍상보다 뚜렷하게 높지 않습니다. 풍향과 데이터를 함께 확인하세요.",
  "Show them": "선택 항목 보기",
  "Deselect them": "선택 해제",
  "Clear selection": "전체 선택 해제",
  "Seen from above": "위에서 본 주행",
  "Best angles you actually sailed": "실제 주행에서 가장 좋았던 각도",
  "from this session, not a boat polar": "이 라이딩 기록을 기준으로 계산합니다.",
  "← Back": "← 뒤로",
  "None detected in this session.": "이 라이딩에서는 감지되지 않았습니다.",
  "Segment": "구간",
  "No samples in this segment.": "이 구간에 측정값이 없습니다.",
  "Against your best this session": "이번 라이딩의 최고 기록 대비",
  "A few things the track cannot tell": "주행 기록만으로 알 수 없는 정보",
  "Show on map": "지도에서 보기",
  "That stretch is out of the performance numbers. Press again to undo.": "이 구간을 퍼포먼스 분석에서 제외했습니다. 다시 누르면 복원합니다.",
  "Kept in the numbers, flagged as a training-load signal.": "분석에 포함하며 훈련 부하의 참고 신호로 표시합니다.",
  "Kept in the numbers.": "분석에 포함합니다.",
  "How the turns went over the session": "시간에 따른 회전 성과",
  "Turn quality by group": "그룹별 회전 품질",
  "efficiency = speed recovered after the turn": "효율은 회전 후 속도 회복 정도입니다.",
  "Career totals": "누적 기록",
  "Distribution by tack": "택별 분포",
  "No samples for this metric.": "이 지표의 측정값이 없습니다.",
  "Turn coaching": "회전 코칭",
  "Trim demand needs a wind speed": "트림 분석에는 풍속이 필요합니다.",
  "Trim demand — boom angle a speed change asks for": "트림 요구량 — 속도 변화에 필요한 붐 각도",
  "Not enough riding in any one course band to read a trim demand from.": "주행 방향별 데이터가 부족하여 트림 요구량을 판단하기 어렵습니다.",
  "Board attitude is not available for this session": "이 라이딩에는 보드 기울기 데이터가 없습니다.",
  "Speed, distance, turns and VMG are unaffected — only heel and pitch are missing.": "힐·피치 데이터만 없으며 속도·거리·회전·VMG 분석에는 영향이 없습니다.",
  "while riding · 10 kt+": "10 kt 이상 주행 중",
  "Left / right balance": "좌우 균형",
  "Board stability": "보드 안정성",
  "Save gear": "장비 저장",
  "Why the two are so far apart": "풍상·풍하의 차이가 큰 이유",
  "Wing size — what if": "윙 크기 변경 시 예상",
  "This is the edge of what the model can judge": "모델로 판단할 수 있는 범위의 경계입니다.",
  "knots": "노트",
  "This session:": "현재 라이딩:",
  "What the colour means.": "색상 의미",
  "How to read it upwind.": "풍상 구간 읽는 법",
  "Line width is pressure.": "선의 굵기는 풍압입니다.",
  "⚠ How this is worked out.": "⚠ 계산 방법과 한계",
  "▶ Race it in Replay": "▶ 재생 화면에서 비교",
  "That is the session you have open — pick a different one to compare.": "현재 열어 둔 라이딩입니다. 다른 기록을 선택하여 비교하세요.",
  "Merged": "병합됨"
});
Object.assign(dictionary,{
  "Green is a lift — the wind swung so you could point higher without changing anything. Orange is a header — it swung the other way and pushed you off course. Grey is the angle you held most of the time on that tack.": "초록색은 더 높이 풍상으로 향할 수 있는 리프트, 주황색은 풍상 진행에 불리한 헤더를 뜻합니다. 회색은 해당 택에서 주로 유지한 각도입니다.",
  "A long orange stretch is the classic sign you stayed on a headed tack too long — that is where tacking would have paid. Green stretches are the ones worth staying on. Look for whether the colours cluster in one part of the course: that means the shift was in the place, not the clock.": "주황색이 길게 이어지면 택을 바꾸는 편이 유리했을 가능성이 있습니다. 초록색 구간은 현재 택을 유지하기 유리합니다. 특정 위치에 같은 색이 모이면 위치에 따른 바람 차이를 확인해 보세요.",
  "Thick means you were going faster than your own median on that tack, thin means slower — read as gust and lull.": "선이 굵으면 해당 택의 평소 속도보다 빠르고, 가늘면 느립니다. 돌풍·약풍의 참고 신호로 보세요.",
  "There is no wind instrument on the board, so this is inferred from the track itself: your heading is compared with the angle you normally held on that same tack, smoothed over about 20 seconds. That means anything that changes your heading or speed reads the same way as wind — a lost bit of trim, a wave, a moment of pumping, or easing off to look around. Treat it as where to look, not as a measurement.": "풍향 센서 없이 주행 경로에서 추정한 값입니다. 같은 택에서 평소 유지한 각도와 진행 방향을 비교하고 약 20초 단위로 평활화합니다. 트림·파도·펌핑·감속도 같은 신호를 만들 수 있으므로 풍향 실측값이 아닌 확인할 구간의 단서로 사용하세요.",
  "A wing that feels easy upwind will be short downwind — and the gap widens as it blows harder, because downwind apparent wind barely rises with true wind while upwind it keeps climbing. Read the upwind peak below as a floor, not a ceiling: going a size under it buys upwind comfort and pays for it downwind.": "풍상에서 편안한 윙도 풍하에서는 힘이 부족할 수 있습니다. 강풍에서 풍상 겉보기 풍속은 높아지지만 풍하에서는 증가폭이 작아 차이가 커집니다. 윙을 줄일 때는 풍상에서의 편안함과 풍하에서 필요한 힘을 함께 판단하세요.",
  "Drag across any panel to select a range — the averages for that stretch appear under the chart, with the option to exclude it.": "차트를 드래그하면 선택 구간의 평균값이 아래에 표시됩니다. 라이딩하지 않은 구간은 분석에서 제외할 수 있습니다.",
  "colour = which tack · width = wind pressure": "색상 = 택 방향 · 굵기 = 풍압 추정",
  "colour = wind shift · width = wind pressure": "색상 = 풍향 변화 추정 · 굵기 = 풍압 추정",
  "circle area = distance lost in the turn": "원 면적 = 회전 중 거리 손실",
  "lifted": "리프트",
  "headed": "헤더",
  "as usual": "평소와 비슷함",
  "lull": "약풍",
  "gust": "돌풍",
  "Average": "평균",
  "Top": "최고",
  "Avg": "평균",
  "Time": "시간",
  "Top 50%": "상위 50%",
  "Top 20%": "상위 20%",
  "Open this session": "이 라이딩 열기",
  "Delete this session": "이 라이딩 삭제",
  "Filled in later, not recorded at save time": "라이딩 저장 후 추가한 장비 정보",
  "Record which wing, foil and board you used": "사용한 윙·포일·보드를 기록하세요.",
  "Sailing Performance Score": "조건 대비 세션 점수",
  "Speed 70%": "주행 70%"
});
Object.assign(dictionary,{
  "Across the water": "구역별 차이",
  "Across the session": "시간대별 차이",
  "Areas you passed through": "잠깐 통과한 구역",
  "Areas you stayed in": "오래 머문 구역",
  "Quarter": "4분할 시간대",
  "Median planing speed": "활주 속도 중앙값",
  "Areas compared": "비교 구역 수",
  "Spread across areas": "구역별 속도 차이",
  "fastest minus slowest area, at the same time": "같은 시간대의 가장 빠른 구역과 느린 구역 차이",
  "best quarter minus worst": "가장 빠른 시간대와 느린 시간대 차이",
  "too few": "데이터 부족",
  "Choppy": "잔파도가 있는 수면",
  "Wavy": "파도가 있는 수면",
  "choppy": "잔파도",
  "wavy": "파도",
  "Waist": "허리",
  "Chest": "가슴",
  "Hip": "골반",
  "None / handheld": "없음 / 손으로 잡기",
  "Best speed": "최고 속도",
  "Split": "기록 구간",
  "Alpha 500": "알파 500",
  "out & back": "회항 구간",
  "Best VMG": "최고 VMG",
  "Fastest": "최고 속도",
  "What turns cost": "회전에 따른 거리 손실",
  "Ground made upwind": "풍상 방향으로 나아간 거리",
  "Ground made downwind": "풍하 방향으로 나아간 거리",
  "measured along the wind axis": "풍향 축을 기준으로 측정",
  "Cost per tack": "택킹 1회당 손실",
  "Cost per gybe": "자이빙 1회당 손실",
  "Ground lost in tacks": "택킹으로 잃은 거리",
  "Ground lost in gybes": "자이빙으로 잃은 거리",
  "Avg cost": "평균 손실",
  "Total cost": "총손실",
  "Net of gains": "회복 이득을 뺀 순손실",
  "Turn": "회전",
  "none measured": "측정된 회전 없음",
  "Stretches": "연속 포일링 구간",
  "Longest": "최장 구간",
  "Average stretch": "평균 연속 구간",
  "Per turn": "회전 1회당",
  "breaks per turn": "회전 1회당 중단 횟수",
  "Your best": "내 상위 기록",
  "from this session only": "현재 라이딩만 기준",
  "Hide": "접기",
  "best VMG": "최고 VMG",
  "fastest": "최고 속도",
  "speed": "속도",
  "duration": "시간",
  "distance": "거리",
  "Best 50%": "상위 50%",
  "Best 20%": "상위 20%",
  "port faster": "포트가 빠름",
  "starboard faster": "스타보드가 빠름",
  "port higher": "포트가 풍상에 가까움",
  "starboard higher": "스타보드가 풍상에 가까움",
  "Median": "중앙값",
  "Target": "목표",
  "Segments": "구간",
  "Correlation": "상관관계",
  "The two tacks sit almost evenly either side of this direction.": "이 풍향을 기준으로 양쪽 택의 각도가 거의 대칭입니다.",
  "This is the direction that makes your port and starboard upwind angles match. ⚠ It assumes you sail both tacks equally well — if one tack is genuinely weaker, this will quietly absorb that into the wind. Treat it as a second opinion, not an answer.": "포트와 스타보드의 풍상 각도가 같아지는 방향입니다. 양쪽 택의 주행 능력이 같다는 가정이므로, 한쪽 택이 약하면 그 차이가 풍향 오차로 해석될 수 있습니다. 참고 의견으로 확인하세요.",
  "The squares you only passed through were slower than the ones you stayed in, so you were reading the water and avoiding the dead patches. The \"no difference\" reading above is partly a result of that choice.": "잠깐 통과한 구역의 속도가 오래 머문 구역보다 느렸습니다. 느린 구역을 피한 선택이 결과에 영향을 주었을 수 있으므로, 위의 차이가 작다는 결과와 함께 해석하세요.",
  "The squares you passed through briefly were no slower than the ones you stayed in, so this is not a case of successfully dodging dead patches — there were not many to dodge.": "잠깐 통과한 구역이 오래 머문 구역보다 느리지 않았습니다. 다만 주행 속도만으로 구역별 바람의 강약을 확정할 수는 없습니다.",
  "Apple Health, Garmin Connect, Samsung Health and Oura all export CSV. Drop one here and the columns are matched automatically — no account, no keys, works today. (A direct API connection needs a server we do not have yet; when it exists this same parser is reused.)": "Apple Health·Garmin Connect·Samsung Health·Oura에서 내보낸 CSV 파일을 가져오세요. 열 이름을 자동으로 확인합니다. 계정 연결 없이 파일을 이용하며 직접 API 연동은 지원하지 않습니다.",
  "Red = port tack, green = starboard — the international convention. Up is upwind. The solid line is your best 5% at that angle, the shaded band down to your usual speed — a wide band means an inconsistent angle. Angles with fewer than 5 samples are left blank rather than drawn at zero. A dent on one side means that tack is losing speed.": "빨강은 포트, 초록은 스타보드 택입니다. 위쪽이 풍상입니다. 실선은 각도별 상위 5% 속도이며 음영은 평소 속도까지의 범위입니다. 폭이 넓을수록 속도 편차가 큽니다. 측정값이 5개 미만인 각도는 비워 두며 한쪽이 움푹하면 그 택에서 속도 손실이 있다는 뜻입니다.",
  "Upwind is judged on VMG — upwind you trade angle for height, so progress to windward is the goal. Downwind is judged on speed: on a foil, going deeper looks better on VMG right up until you drop off the foil, so speed is the honest measure. Both need the wind direction to be right — check it on the Environment tab first.": "풍상은 바람을 향해 나아가는 VMG, 풍하는 포일링을 유지하는 속도로 평가합니다. 두 지표 모두 정확한 풍향이 필요하므로 라이딩 조건에서 먼저 확인하세요.",
  "Cross-tabulate any two of tack, wind angle, speed zone or heart-rate zone against a metric. Folded away because the everyday question — port against starboard — is answered more legibly by Tack bias above; open this when you want an axis pair that has no card of its own.": "택·풍각·속도 구간·심박 구간 중 두 축으로 지표를 교차 비교합니다. 일상적인 좌우 택 비교는 위의 택 편차 카드에서 확인하고, 다른 축 조합이 필요할 때 이 표를 펼치세요.",
  "Windows are picked by VMG; the speed and angle shown are whatever came with them, so each row is a combination you actually rode. Picking the fastest speed and the tightest angle separately would give a target no one has ever sailed.": "VMG를 기준으로 구간을 선택하고 당시 속도와 각도를 함께 표시합니다. 각 행은 실제로 주행한 조합입니다. 최고 속도와 최소 각도를 따로 뽑아 비현실적인 목표를 만들지 않습니다."
});
Object.assign(dictionary,{
  "Raised (below sternum)": "높게 (명치 아래)",
  "Waist (normal)": "허리 (기본)",
  "Pulled low (full power)": "낮게 (풀파워)",
  "separate times up on foil": "서로 나뉜 연속 포일링 구간",
  "starboard vs port": "포트 대비 스타보드",
  "starboard vs port · size of the angle": "포트 대비 스타보드 · 각도의 크기",
  "starboard vs port · too small a base for %": "포트 대비 스타보드 · 비율 계산에는 기준값이 너무 작음",
  "level": "비슷함",
  "no turns detected": "감지된 회전 없음",
  "port higher → ahead": "포트 값이 높을수록 유리 →",
  "port lower → ahead": "포트 값이 낮을수록 유리 →",
  "ahead ← starboard higher": "← 스타보드 값이 높을수록 유리",
  "ahead ← starboard lower": "← 스타보드 값이 낮을수록 유리",
  "Target VMG": "목표 VMG",
  "Target speed": "목표 속도",
  "% of target": "목표 대비",
  "Delta": "차이",
  "Your VMG": "내 VMG",
  "Your speed": "내 속도",
  "Shown once wind direction is set": "풍향 설정 후 표시됩니다.",
  "⏳ Reading…": "⏳ 읽는 중…",
  "🕑 Detect time from screen (OCR)": "🕑 영상의 시간 인식 (OCR)",
  "Not enough windows to say anything.": "구간 데이터가 부족하여 관계를 판단하기 어렵습니다.",
  "You came off the foil about once per turn — that is what a clean session looks like at this stage, since a turn is where it normally happens. The number to grow is the longest stretch, not this one.": "회전당 약 한 번씩 포일링이 끊겼습니다. 회전 중 착수 여부를 확인하고 최장 연속 포일링 구간을 늘려 보세요.",
  "Longest unbroken stretch is the number worth growing — total foiling time can rise just from a longer session.": "총 포일링 시간은 라이딩이 길어져도 늘어납니다. 최장 연속 포일링 구간을 함께 확인하세요.",
  "This is the edge of what you sailed — the real best may be beyond it.": "실제로 주행한 각도 범위의 끝입니다. 이 범위 밖에 더 좋은 각도가 있을 수 있습니다.",
  "These two are linked by definition — VMG is speed times the cosine of CWA. The correlation here comes from the arithmetic, not from your sailing. The slope is still worth reading: it says what a degree of angle is actually worth in VMG.": "VMG는 속도에 CWA의 코사인을 곱하므로 두 지표는 수학적으로 연결되어 있습니다. 이 상관관계 자체는 실력의 증거가 아닙니다. 기울기는 각도 1° 변화에 따른 VMG 차이로 읽을 수 있습니다.",
  "Each dot is a 20-second window of riding above 8 kt, not a single GPS sample — neighbouring samples are not independent, and using them raw would make any relationship look far more certain than it is.": "점 하나는 8 kt 이상 주행한 20초 구간입니다. 인접 GPS 측정값은 독립적이지 않으므로 개별 점을 그대로 쓰면 관계를 실제보다 확실하게 보일 수 있습니다."
});
Object.assign(dictionary,{
  "Auto: VMG": "자동: VMG",
  "Auto: ahead": "자동: 선두",
  "✕ Stop comparing": "✕ 비교 종료",
  "Which rider is drawn bold": "강조할 라이더 선택",
  "Bold = whoever has the higher VMG over the last 3 s": "최근 3초 VMG가 높은 라이더 강조",
  "Bold = whoever has covered more distance since the start (same course)": "같은 코스에서 시작 후 더 멀리 진행한 라이더 강조",
  "Always draw this rider bold": "이 라이더를 항상 강조",
  "Remove the second rider and go back to a normal replay": "비교를 끝내고 단일 라이딩 재생으로 돌아갑니다.",
  "No metrics to show.": "표시할 지표가 없습니다.",
  "needs a wind direction": "풍향 설정 필요",
  "Hide the numbers": "수치 접기",
  "Upwind is scored on VMG — progress to windward is the goal.": "풍상은 바람을 향한 전진 성능인 VMG로 평가합니다.",
  "Downwind is scored on speed — on a foil, deeper flatters VMG right up until you drop off.": "풍하는 포일링 유지가 중요하므로 속도로 평가합니다. 더 깊은 각도에서 VMG가 좋아 보여도 착수할 수 있습니다.",
  "Max": "최대",
  "Avg HR": "평균 심박수"
});
Object.assign(dictionary,{
  "What the turns cost": "회전에 따른 거리 손실",
  "port is faster": "포트가 더 빠름",
  "starboard is faster": "스타보드가 더 빠름",
  "rings are knots · 0° is straight upwind": "동심원 단위: kt · 0°는 정면 풍상",
  "Where": "위치",
  "Speed / SOG (kt)": "지면 기준 속도 / SOG (kt)",
  "Course wind angle (°)": "주행 풍각 (°)",
  "Apparent wind speed (kt)": "겉보기 풍속 (kt)",
  "Apparent wind angle (°)": "겉보기 풍각 (°)",
  "Heart rate (bpm)": "심박수 (bpm)",
  "Heel (°)": "좌우 기울기 (°)",
  "Pitch (°)": "앞뒤 기울기 (°)",
  "Channels": "표시 지표",
  "colour = boat speed": "색상 = 주행 속도",
  "tack": "택킹",
  "gybe": "자이빙",
  "How it works": "계산 방법",
  "The empty wedge in the heading histogram: you cannot sail straight into wind.": "맞바람으로 직접 주행할 수 없다는 점을 이용해 진행 방향 분포의 빈 구간에서 추정합니다.",
  "Turn geometry": "회전 궤적",
  "Bisector of entry and exit headings across every detected tack and gybe.": "감지된 택킹·자이빙의 진입·탈출 방향을 이등분하여 추정합니다.",
  "Weather service": "기상 서비스",
  "Not connected yet.": "아직 연결되지 않았습니다.",
  "Only one estimate could be made for this session.": "이 라이딩에서는 한 가지 방법으로만 풍향을 추정할 수 있었습니다.",
  "upwind": "풍상",
  "downwind": "풍하",
  "Avg VMG": "평균 VMG",
  "Avg wind angle": "평균 풍각",
  "solid": "데이터 충분",
  "short segment": "짧은 구간",
  "클릭해서 제목을 바꿉니다 · click to rename": "클릭하여 라이딩 제목을 변경합니다.",
  "Summary only — the track was cleared to save space, so this one cannot be reopened.": "공간 확보를 위해 경로가 삭제되어 요약만 남았습니다. 경로를 다시 열 수 없습니다."
});
Object.assign(dictionary,{
  "Riding Replay": "라이딩 재생",
  "Select metrics": "표시 지표 선택",
  "Upload Video": "영상 불러오기",
  "Upload a video": "영상을 불러오세요.",
  "Layout": "화면 배치",
  "Side by Side": "나란히 보기",
  "Swap sides": "좌우 바꾸기",
  "Swap video / map sides": "영상·지도 위치 바꾸기",
  "Sync video": "영상 시간 맞추기",
  "Close replay": "재생 종료",
  "Close (Esc)": "닫기 (Esc)",
  "to fill the screen and play it alongside your data.": "전체 화면에서 주행 데이터와 함께 재생할 수 있습니다.",
  "Upload a video to fill the screen and play it alongside your data.": "영상을 불러오면 전체 화면에서 주행 데이터와 함께 재생할 수 있습니다.",
  "The file opens only in your browser and is never uploaded anywhere.": "영상 파일은 이 브라우저에서만 열리며 서버로 전송되지 않습니다.",
  "Zoom out map": "지도 축소",
  "Zoom in map": "지도 확대",
  "⊕ Center": "⊕ 중앙 정렬",
  "Center on board": "보드를 지도 중앙에 표시",
  "🎯 Track Board": "🎯 보드 따라가기",
  "Keep the board centered and pan the map to follow it": "보드가 중앙에 오도록 지도를 따라 이동합니다.",
  "Wind Axis": "풍향 기준선",
  "Wind axis line through the board (along the wind)": "보드를 지나는 풍향 방향 기준선",
  "Ladder": "횡방향 기준선",
  "Ladder rung line through the board (across the wind)": "보드를 지나는 풍향 직각 방향 기준선",
  "Metric mini-graphs": "지표별 미니 그래프",
  "Stop (to start)": "정지 후 시작 위치로",
  "Stop — back to start": "정지하고 시작 위치로 돌아갑니다.",
  "Time scrubber": "재생 시점 선택",
  "Zoom out track": "시간축 축소",
  "Zoom in track": "시간축 확대",
  "Full": "전체 구간",
  "🔗 Link Map": "🔗 지도 연동",
  "Link track zoom to map range": "시간축 확대 범위를 지도 범위에 연동",
  "cardio": "유산소 운동",
  "strength": "근력 운동",
  "hiit": "고강도 인터벌",
  "recovery": "회복 운동",
  "Run": "달리기",
  "Cycle": "자전거",
  "Row": "로잉",
  "Swim": "수영",
  "Hike": "등산",
  "Walk": "걷기",
  "Elliptical": "일립티컬",
  "Strength": "근력 운동",
  "HIIT": "고강도 인터벌",
  "CrossFit": "크로스핏",
  "Yoga": "요가",
  "Pilates": "필라테스",
  "Mobility": "가동성 운동",
  "Stretching": "스트레칭"
});
// Whole-message templates only: never replace a word inside user text or a model name.
const patterns=[
[/^(Run|Cycle|Row|Swim|Hike|Walk|Elliptical|Strength|HIIT|CrossFit|Yoga|Pilates|Mobility|Stretching)(?: · (easy|moderate|vigorous|intervals|leisure|hiit|brisk|bodyweight|barbell|circuit|vinyasa))? \(MET ([\d.]+)\)$/,(_,sport,level,met)=>translate(sport)+(level?' · '+({easy:'가볍게',moderate:'보통 강도',vigorous:'높은 강도',intervals:'인터벌',leisure:'여유롭게',hiit:'고강도 인터벌',brisk:'빠르게',bodyweight:'맨몸',barbell:'바벨',circuit:'서킷',vinyasa:'빈야사'}[level]):'')+' (MET '+met+')'],

[/^above ([\d.]+) kt$/,(_,n)=>n+' kt 이상'],
[/^upwind ([\d:]+) · downwind ([\d:]+)$/,(_,u,d)=>'풍상 '+u+' · 풍하 '+d],
[/^drag to select · gaps closed — ([\d:]+) of stops and removed time folded out$/,(_,n)=>'드래그하여 구간 선택 · 정지·제외 시간 '+n+'을 접은 시간축'],
[/^two estimates differ by ([\d.]+)°$/,(_,n)=>'두 추정값의 차이 '+n+'°'],
[/^The two independent estimates agree within ([\d.]+)°\.( Both methods are weak on this session, so treat VMG, wind angle and the polar as indicative only\.)?$/,(_,n,weak)=>'두 독립 추정값이 '+n+'° 이내로 일치합니다.'+(weak?' 두 방법 모두 신뢰도가 낮으므로 VMG·풍각·폴라를 참고용으로만 확인하세요.':'')],
[/^The two independent estimates disagree by ([\d.]+)° — check the track and set the direction yourself if you know it\.( Both methods are weak on this session, so treat VMG, wind angle and the polar as indicative only\.)?$/,(_,n,weak)=>'두 독립 추정값이 '+n+'° 차이입니다. 경로를 확인하고 당시 풍향을 안다면 직접 설정하세요.'+(weak?' 두 방법 모두 신뢰도가 낮으므로 VMG·풍각·폴라를 참고용으로만 확인하세요.':'')],
[/^Leg #(\d+)$/,(_,n)=>'레그 #'+n],
[/^max ([\d.]+) kt$/,(_,n)=>'최대 '+n+' kt'],
[/^(\d+) samples$/,(_,n)=>n+'개 측정값'],
[/^Averages are time-weighted\. "Best" tiers reject noise — for wind angles that means the lowest angles upwind, the highest downwind\. Heart rate is split by tack too, but read a difference carefully — if you sailed one tack mostly late in the session, that alone lowers it\.( Apparent wind speed is built from the wind speed you entered, so it carries that error almost one-for-one — read it as a trend, not a measurement\. The angle is far less sensitive to it\.)?$/,(_,aws)=>'평균은 시간을 가중하여 계산합니다. 상위 기록은 잡음을 제외하며 풍각은 풍상에서 작은 각도, 풍하에서 큰 각도를 기준으로 합니다. 택별 심박수 차이는 주행한 시간대의 영향도 있으므로 좌우 체력 차이로 단정하지 마세요.'+(aws?' 겉보기 풍속은 입력 풍속의 오차를 거의 그대로 반영하므로 실측값이 아닌 경향으로 확인하세요. 풍각은 이 오차에 덜 민감합니다.':'')],

[/^Speeds in knots\. Sessions are bucketed by the wind strength you entered, so gusts and lulls inside one session all land in the same bucket — this grid separates days, not moments\. A dot means samples exist but too few to report\.(?: (\d+) saved sessions? (?:have|has) no wind speed recorded\.)?$/,(_,n)=>'속도 단위는 kt입니다. 입력한 풍속에 따라 라이딩을 나누므로 같은 라이딩의 돌풍·약풍은 한 그룹에 포함됩니다. 순간별이 아닌 날짜별 비교입니다. 점은 측정값이 있으나 개수가 부족하다는 뜻입니다.'+(n?' '+n+'개 저장 기록에는 풍속이 없습니다.':'')],
[/^(\d+) windows of (\d+)s$/,(_,n,t)=>t+'초 구간 '+n+'개'],
[/^Sorted fastest first — click a row to see that stretch on the map\. The threshold moves with the day: it is set from your own 90th-percentile speed, (?:so ([\d.]+) kt today|not a fixed number)\. That is why it lands near the ([\d.]+) kt foiling line on an ordinary day and pulls away on a fast one — the foiling stretches above are cut at a fixed speed, these are cut relative to you\.$/,(_,r,f)=>'빠른 순서이며 행을 누르면 지도에서 구간을 확인합니다. 고속 구간은 이날 속도의 90백분위를 기준으로 정합니다.'+(r?' 오늘 기준은 '+r+' kt입니다.':'')+' 고정된 포일링 기준 '+f+' kt와 달리 주행 성과에 따라 달라집니다.'],
[/^You sailed this at (\d+)° while your best (VMG|speed) angle was (\d+)° — that is (\d+)° (lower than you can point|higher, so you were pinching|deeper than your fastest|higher than your fastest)\. Much of the gap below is the angle, not the boat speed\.$/,(_,a,k,b,g,why)=>'이 구간의 각도는 '+a+'°, 최고 '+(k==='VMG'?'VMG':'속도')+' 각도는 '+b+'°로 '+g+'° 차이입니다. 성과 차이에는 주행 속도뿐 아니라 각도의 영향이 큽니다.'],
[/^Wind angle moved ([+−\-\d.]+)° across this segment \((\d+)° → (\d+)°\) — you were (freed|headed)\. Could be a real shift or the wind direction drifting\.$/,(_,d,a,b,k)=>'이 구간의 풍각은 '+a+'° → '+b+'° ('+d+'°) 변했습니다. '+(k==='freed'?'풍상 진행에 유리한':'풍상 진행에 불리한')+' 변화이며 실제 풍향 변화인지 설정 오차인지 확인하세요.'],


[/^(Port|Starboard) \((above|below)\) · (\d+) samples(?: · median ([\d.−\-]+)(°| kt))?$/,(_,side,place,n,v,u)=>translate(side)+' ('+(place==='above'?'위':'아래')+') · '+n+'개 측정값'+(v?' · 중앙값 '+v+u:'')],
[/^Both tacks are within a couple of percent on speed and VMG — no meaningful bias to work on (upwind|downwind)\.$/,(_,k)=>(k==='upwind'?'풍상':'풍하')+'에서 양쪽 택의 속도와 VMG 차이가 작아 뚜렷한 편차가 없습니다.'],
[/^You are ([\d.]+)% faster on (starboard|port) and the VMG follows it \(([\d.]+)%\) — this reads as a speed difference rather than an angle one\.$/,(_,n,side,v)=>translate(side)+'가 '+n+'% 빠르고 VMG도 '+v+'% 높습니다. 각도보다 속도 차이의 영향으로 보입니다.'],
[/^You are ([\d.]+)% faster on (starboard|port) but your VMG is ([\d.]+)% better on (starboard|port) — the two point opposite ways, which only happens when the faster tack is giving up angle\.(.*)$/,(_,n,side,v,other,tail)=>translate(side)+'에서 '+n+'% 빠르지만 VMG는 '+translate(other)+'에서 '+v+'% 높습니다. 빠른 택의 주행 각도를 확인하세요.'+translate(tail)],
[/^Speed is close on both tacks \(([+−\-\d.]+)%\) but VMG differs by ([\d.]+)% — that gap is coming from angle, not boat speed\.(.*)$/,(_,s,v,tail)=>'양쪽 택의 속도 차이는 '+s+'%지만 VMG 차이는 '+v+'%입니다. 주행 각도의 영향이 큽니다.'+translate(tail)],
[/^You sail ([\d.]+)° wider on (starboard|port) — upwind that is the wrong way, and that is where the VMG goes\.$/,(_,n,side)=>translate(side)+'에서 풍상 각도가 '+n+'° 더 벌어져 VMG를 잃습니다.'],
[/^You sail ([\d.]+)° wider on (starboard|port) — downwind that is deeper, which helps until the extra angle costs more speed than it gains\.$/,(_,n,side)=>translate(side)+'에서 '+n+'° 더 깊게 풍하로 진행합니다. 각도 이득보다 속도 손실이 커지면 불리해집니다.'],
[/^out & back · within (\d+) m gate$/,(_,n)=>'회항 · 출발·도착 간격 '+n+' m 이내'],
[/^Alpha (\d+) m$/,(_,n)=>'알파 '+n+' m'],
[/^(\d+) runs · threshold ([\d.]+|—) kt$/,(_,n,v)=>n+'개 고속 구간 · 기준 '+v+' kt'],
[/^Both of these also drift with time in this session \(r = ([−\-\d.]+) and ([−\-\d.]+) against elapsed time\)\. If the wind built or died, that alone would produce this relationship\. Compare windows from the same part of the session before concluding anything\.$/,(_,a,b)=>'두 지표 모두 시간에 따라 변합니다 (시간과의 상관계수 '+a+', '+b+'). 풍속 변화만으로도 이런 관계가 나타날 수 있으므로 같은 시간대의 구간끼리 비교하세요.'],
[/^(\d+:\d+(?::\d+)?) elapsed$/,(_,t)=>t+' 경과'],
[/^Getting the wind direction wrong by δ pushes one tack’s angle up by δ and the other down by δ, so the gap you see is the real gap plus 2δ\. This ([\d.]+)° gap would be fully explained by a wind direction that is off by just ([\d.]+)°(?: — the track estimate is (.+) confidence)?\. Confirm the wind before training this away\.$/,(_,g,e,c)=>'풍향 오차는 양쪽 택의 각도 차이를 두 배로 벌릴 수 있습니다. 현재 '+g+'° 차이는 풍향이 '+e+'°만 틀려도 설명됩니다.'+(c?' 추정 신뢰도: '+translate(c)+'.':'')+' 훈련 과제로 삼기 전에 풍향을 확인하세요.'],

[/^Use for all (\d+) saved sessions on (\d{4}-\d{2}-\d{2})$/,(_,n,d)=>d+'에 저장한 '+n+'개 라이딩에 적용'],
[/^Upwind angle — port ([\d.]+)° · starboard ([\d.]+)° · gap ([\d.]+)°$/,(_,p,s,g)=>'풍상 각도 — 포트 '+p+'° · 스타보드 '+s+'° · 차이 '+g+'°'],
[/^Getting the direction wrong by δ lifts one tack by δ and drops the other by δ, so a ([\d.]+)° gap is what a ([\d.]+)° error would produce\.$/,(_,g,e)=>'풍향이 δ만큼 틀리면 양쪽 택의 각도 차이는 2δ만큼 벌어집니다. '+g+'° 차이는 풍향 오차 '+e+'°로도 발생할 수 있습니다.'],
[/^Most symmetric direction: (\d+)° — that is what you have$/,(_,d)=>'가장 대칭적인 풍향: '+d+'° · 현재 설정과 같습니다.'],
[/^Most symmetric direction: (\d+)° \(([+−\-\d.]+)° from the (\d+)° in use\)$/,(_,d,g,c)=>'가장 대칭적인 풍향: '+d+'° · 현재 '+c+'°에서 '+g+'°'],
[/^(\d+) m squares$/,(_,n)=>n+' m 정사각 구역'],
[/^(\d+) squares, under 90 s each$/,(_,n)=>n+'개 구역 · 각각 90초 미만'],
[/^(\d+) squares, 3 min or more$/,(_,n)=>n+'개 구역 · 각각 3분 이상'],
[/^([1-4]) of 4$/,(_,n)=>'4개 시간대 중 '+n+'번째'],
[/^Areas are (\d+) m squares and only those with at least three minutes of planing are compared, with the time window held fixed so a fading breeze cannot masquerade as a bad patch\. Gusts smaller or shorter than that will not show up here\.$/,(_,n)=>n+' m 정사각 구역 중 3분 이상 활주한 구역을 같은 시간대끼리 비교합니다. 이보다 좁거나 짧은 돌풍은 표시되지 않습니다.'],
[/^(.+) span ([\d.]+)m( \(est\.\))?$/,(_,name,n,e)=>name+' · 폭 '+n+' m'+(e?' (추정)':'')],
[/^(.+) \(thickness est\.\)$/,(_,name)=>name+' (두께 추정)'],
[/^best VMG ([\d.]+) kt \(at ([\d.]+) kt\)$/,(_,v,s)=>'최고 VMG '+v+' kt (속도 '+s+' kt)'],
[/^fastest ([\d.]+) kt \(VMG ([\d.]+) kt\)$/,(_,s,v)=>'최고 속도 '+s+' kt (VMG '+v+' kt)'],
[/^(\d+) s at this angle$/,(_,n)=>'이 각도에서 '+n+'초 주행'],
[/^Turns are left out of the polar and these picks \(([\d,]+) samples within (\d+) s of a tack or gybe\)\. A board passes through every angle while it turns — counting that would put your best upwind angle right into the wind\.$/,(_,n,t)=>'회전 전후 '+t+'초의 '+n+'개 측정값은 폴라와 최적각도 계산에서 제외합니다. 회전 중 스쳐 가는 각도를 지속 가능한 풍상 각도로 오해하지 않기 위해서입니다.'],
[/^(\d+) (tacks|gybes) measured$/,(_,n,k)=>n+'회 '+(k==='tacks'?'택킹':'자이빙')+' 측정'],
[/^equals ([\d.]+)% of the ground made (upwind|downwind)$/,(_,n,k)=>(k==='upwind'?'풍상':'풍하')+' 진행 거리의 '+n+'%'],
[/^(Tack|Gybe) · (port|starboard)$/,(_,a,b)=>(a==='Tack'?'택킹':'자이빙')+' · '+(b==='port'?'포트':'스타보드')],
[/^Only (\d+)% of your planing time was spent on a straight run of 25 seconds or more, so this reads as a turning session rather than sailing a course\. The numbers below are still the cost of each turn, but in a drill that cost is the price of the repetition, not a mistake — the useful figure is the cost per turn and whether it falls as the session goes on, not the total\.$/,(_,n)=>'25초 이상 직선 주행한 시간은 활주 시간의 '+n+'%로, 회전 연습 비중이 높습니다. 반복 연습에서는 총손실보다 회전 1회당 손실과 시간에 따른 개선 여부를 확인하세요.'],
[/^(\d+) turns? went backwards relative to the objective for more than 3 seconds \(rounding up out of a gybe, or stalling head-to-wind in a tack\)\. That is a different fault from simply being slow — it is the exit angle, not the speed\.$/,(_,n)=>n+'회 회전에서 목표 방향의 반대로 3초 이상 진행했습니다. 자이빙 후 풍상으로 치우치거나 택킹 중 맞바람에 멈춘 구간일 수 있습니다. 속도뿐 아니라 탈출 각도를 확인하세요.'],
[/^Counted (\d+) of (\d+) turns(?: — skipped .+)?\. These are distances, not speed drops: a turn costing 40 m means you ended up 40 m further from where you were heading than if you had held your pace through it\. Cost is the ground you fell behind your own best pace — measured from position, from the moment the turn starts until you get that pace back \(the better of your before or after pace\)\. "Net of gains" subtracts any moments inside that window where you beat the pace, so it is always the smaller number; a wide gap between the two means you clawed a lot back on the exit\.$/,(_,n,t)=>'전체 '+t+'회 중 '+n+'회 회전을 계산했습니다. 기준 속도·구간 경계·풍각을 확인할 수 없는 회전은 제외됩니다. 손실은 속도 감소율이 아니라 거리입니다. 회전 전후의 더 나은 페이스를 유지했을 때보다 뒤처진 거리를 회전 시작부터 페이스 회복까지 계산합니다. 순손실은 그 구간에서 기준보다 빨라 회복한 거리도 빼므로 더 작은 값입니다.'],
[/^breaks per turn \((\d+) turns\)$/,(_,n)=>'회전당 포일링 중단 · '+n+'회 회전'],
[/^([\d.]+) km each$/,(_,n)=>'구간당 '+n+' km'],
[/^You got up on foil (\d+) separate times across (\d+) turns — about one break every ([\d.]+) turns, so you carried the foil through most of them\. The number to grow now is the longest stretch, not this one\.$/,(_,n,t,b)=>t+'회 회전 중 '+n+'개 연속 포일링 구간이 있었습니다. 약 '+b+'회 회전마다 한 번 끊겼으므로 대부분 포일링을 유지했습니다. 이제 최장 연속 구간을 늘려 보세요.'],
[/^You came off the foil ([\d.]+) times per turn, so roughly (\d+) of these breaks were not at a turn — touchdowns in a straight line\. That is a different fault from a bad gybe: it is height control or a foil that is loaded up, not turn technique\.$/,(_,r,n)=>'회전당 '+r+'회 포일링이 끊겨 약 '+n+'회는 직선 구간 중단으로 추정됩니다. 회전 기술뿐 아니라 높이 조절·포일 하중·파도도 확인하세요.'],
[/^from (\d+) saved sessions?$/,(_,n)=>'저장한 '+n+'개 라이딩 기준'],
[/^(Upwind|Downwind) · (\d+) windows of (\d+)s$/,(_,k,n,t)=>(k==='Upwind'?'풍상':'풍하')+' · '+t+'초 구간 '+n+'개'],
[/^Top (\d+)%$/,(_,n)=>'상위 '+n+'%'],
[/^Today is (\d+)% of your top-10% VMG target\.$/,(_,n)=>'오늘은 상위 10% VMG 목표의 '+n+'%입니다.'],
[/^(\d+)th percentile of your (\d+)-second windows across saved sessions$/,(_,p,t)=>'저장한 라이딩의 '+t+'초 구간 중 '+p+'백분위'],
[/^No other saved sessions carry target windows yet, so the band is built from today alone — it reads as consistency within today, not a personal best\. (?:(\d+) older sessions? (?:were|was) saved before this was recorded, so they cannot contribute\. )?Save a few more and it becomes a cross-day comparison\.$/,(_,n)=>'다른 저장 기록에 목표 구간 데이터가 없어 오늘 기록만으로 범위를 만들었습니다. 개인 최고가 아닌 오늘의 일관성을 나타냅니다.'+(n?' 이전 '+n+'개 기록은 해당 데이터가 없어 제외합니다.':'')+' 기록이 더 쌓이면 날짜 간 비교가 가능합니다.'],
[/^90th-percentile speed · (\d+) sessions?$/,(_,n)=>'90백분위 속도 · '+n+'개 라이딩'],
[/^r = ([−\-\d.]+) over (\d+) windows — (essentially no relationship|a weak relationship|a moderate relationship|a strong relationship|a very strong relationship)\. (.+) (rises|falls) about ([\d.]+) (.*?) per (.*?) of (.+)\.$/,(_,r,n,str,y,dir,v,yu,xu,x)=>n+'개 구간의 상관계수 r = '+r+' · '+({'essentially no relationship':'상관관계가 거의 없음','a weak relationship':'약한 상관관계','a moderate relationship':'보통 상관관계','a strong relationship':'강한 상관관계','a very strong relationship':'매우 강한 상관관계'}[str])+'. '+translate(x)+' 1 '+xu+'당 '+translate(y)+' 약 '+v+' '+yu+' '+(dir==='rises'?'증가':'감소')+'.'],

[/^Speed is scored against what the lift calculator predicts is achievable for your weight, wing and skill in these conditions(?:, on your (.+) \(aspect ratio ([\d.]+)\))?\.$/,(_,foil,ar)=>'현재 체중·윙·라이딩 수준과 조건에서 모델이 예상하는 주행 성능을 기준으로 점수를 계산합니다.'+(foil?' 포일: '+foil+' · 종횡비 '+ar+'.':'')],
[/^(\d+) segments? excluded — everything below is recomputed without them: distance, average speed, foiling share, turns, the map and the timeline\.$/,(_,n)=>n+'개 구간을 제외했습니다. 거리·평균 속도·포일링 비율·회전·지도·타임라인에 반영됩니다.'],
[/^The wing feels apparent wind, not true wind, and force goes with its square\. Upwind your speed adds to the wind, so apparent wind climbs to ([\d.]+) kt\. Downwind you are sailing away from it, so your speed cancels it back down to ([\d.]+) kt\. That is ([\d.]+)% of the wind speed but only ([\d.]+)% of the force — you would need about ([\d.]+)× the wing area downwind to match the pull you get upwind\.$/,(_,u,d,w,f,a)=>'윙이 받는 힘은 겉보기 풍속의 제곱에 비례합니다. 추정 겉보기 풍속은 풍상 '+u+' kt, 풍하 '+d+' kt입니다. 풍하는 풍상의 풍속 '+w+'%, 힘 '+f+'%에 해당합니다. 같은 힘을 내려면 이론상 약 '+a+'배의 면적이 필요하지만 실제 장비 선택에는 다른 제약도 고려해야 합니다.'],
[/^The ratio is solid, the absolute numbers less so — apparent wind speed inherits your wind-speed input almost one for one, so read ([\d.]+) and ([\d.]+) kt as a trend rather than a measurement\.$/,(_,a,b)=>'입력한 풍속에 따라 추정치가 달라집니다. '+a+' kt와 '+b+' kt는 실측값이 아닌 경향으로 확인하세요.'],
[/^Anchored to your measured upwind VMG of ([\d.]+) kt, so the curve is scaled to what you actually achieved — not raw theory\.$/,(_,v)=>'실제 풍상 VMG '+v+' kt를 기준으로 예상 곡선을 보정했습니다.'],
[/^(\d+)% (lifted|headed)$/,(_,n,v)=>n+'% '+(v==='lifted'?'리프트':'헤더')],
[/^How you felt on (\d{4}-\d{2}-\d{2})$/,(_,d)=>d+'의 신체 상태'],
[/^sleep and how you felt on (\d{4}-\d{2}-\d{2})$/,(_,d)=>d+'의 수면과 신체 상태'],
[/^Currently ([\d.]+)° \(manual\)$/,(_,d)=>'현재 풍향 '+d+'° · 직접 설정'],
[/^Currently ([\d.]+)° from track estimate · confidence (low|medium|high)(.*)$/,(_,d,c,tail)=>'현재 풍향 '+d+'° · 주행 기록 추정 · 신뢰도 '+({low:'낮음',medium:'보통',high:'높음'}[c])+tail.replace(/^ · two methods (agree within|differ by) ([\d.]+)°$/,(_,v,n)=>' · 두 추정 방법의 차이 '+n+'°')],
[/^Try ([\d.]+)°$/,(_,d)=>d+'° 확인'],
[/^At ([\d.]+) kt you normally ride ([\d.]+) m²$/,(_,w,a)=>'풍속 '+w+' kt에서 평소 사용하는 윙: '+a+' m²'],
[/^You have ([\d.]+) m² selected above\.$/,(_,a)=>'선택한 윙 크기: '+a+' m²'],
[/^([\d.]+) kg you \+ ([\d.]+) kg gear$/,(_,a,b)=>'라이더 '+a+' kg + 장비 '+b+' kg'],
[/^Geometry allows (\d+)° of heel with this setup on (.+) water, limited by the (wing tip|foil tip)\.$/,(_,n,sea,tip)=>'이 장비와 수면 상태('+translate(sea)+')에서 허용 힐 각도는 '+n+'°이며, '+(tip==='wing tip'?'윙':'포일')+' 끝의 여유가 한계를 결정합니다.'],
[/^Heeling the board tilts the foil from vertical toward horizontal, which is how it resists the wing’s side pull — so more heel means more wing you can hold\. Two things stop you: the foil tip breaking the surface \(ventilation\) and the wing tip catching the water\. Rough water eats the margin on both, which is why the same wing that is fine on flat water is unusable in chop\. On this setup the (foil|wing) runs out first at (.+)\.$/,(_,part,sea)=>'보드를 기울이면 포일이 윙의 횡력을 버틸 수 있습니다. 다만 포일 끝이 수면 위로 나오거나 윙 끝이 물에 닿으면 한계에 도달합니다. 파도가 있으면 여유가 줄어듭니다. 현재 수면 상태('+translate(sea)+')에서는 '+(part==='foil'?'포일':'윙')+'의 여유가 먼저 소진됩니다.'],
[/^Rougher water needs more room between the tips and the surface, so it lowers the heel available in the Gear card — (.+) keeps ([\d.]+) cm at the foil tip and ([\d.]+) cm at the wing tip\.$/,(_,sea,f,w)=>'거친 수면에서는 끝부분과 수면 사이의 여유가 더 필요하여 허용 힐 각도가 줄어듭니다. '+translate(sea)+' 기준 여유: 포일 '+f+' cm · 윙 '+w+' cm.'],
[/^(\d+) stored · click a row to open$/,(_,n)=>n+'개 저장됨 · 행을 눌러 열기'],
[/^(\d+) stored · (\d+) can be reopened$/,(_,n,m)=>n+'개 저장됨 · '+m+'개 경로 열기 가능'],
[/^1 = wrecked · 5 = fresh$/,()=> '1 = 매우 피곤함 · 5 = 상쾌함'],
[/^1 = very high · 5 = none$/,()=> '1 = 매우 높음 · 5 = 없음'],
[/^1 = severe · 5 = none$/,()=> '1 = 심함 · 5 = 없음'],
[/^1 = awful · 5 = great$/,()=> '1 = 매우 나쁨 · 5 = 매우 좋음'],
[/^Upwind angle — port ([\d.]+)° · starboard ([\d.]+)°(.*)$/,(_,p,s,t)=>'풍상 각도 — 포트 '+p+'° · 스타보드 '+s+'°'+t],
[/^Best average over a (.+) window$/,(_,n)=>n+' 구간의 최고 평균'],
[/^Delete (.+)$/,(_,name)=>name+' 삭제'],
[/^(\d+) sessions$/,(_,n)=>n+'개 라이딩 기록']
];
Object.assign(dictionary,(window.RDKoreanExtra||{}).dictionary||{});
patterns.push(...((window.RDKoreanExtra||{}).patterns||[]));
function translate(s){const key=norm(s);let value;if(key&&Object.hasOwn(dictionary,key))value=dictionary[key];else {for(const [re,fn] of patterns){if(re.test(key)){value=key.replace(re,fn);break;}}}if(typeof value==='string')value=value.replace(/([가-힣])\.(\s*)$/,function(all,last,space){return '다요까오죠'.includes(last)?all:last+space;});return value===undefined?s:s.replace(s.trim(),value);}
// Session list second cells are titles; equipment names must remain intact.
function protectedText(node){const p=node.parentElement;if(!p)return false;
if(p.closest('script,style,textarea,[contenteditable],#hdr-title,#nav-meta,.replay-lead__btn[data-mode="me"],.replay-lead__btn[data-mode="ghost"],#replay-ghost-label,#replay-player-label,[data-no-translate],[translate="no"]'))return true;
if(p.matches('#sessions-body tbody td:nth-child(2)'))return true;
if(p.closest('#replay-ghost option:not([value=""])'))return true;

return false;}

function walk(root){if(root.nodeType===3){if(!protectedText(root)){const t=translate(root.nodeValue);if(t!==root.nodeValue)root.nodeValue=t;}return;}
if(root.nodeType!==1||root.matches('script,style,textarea'))return;
['title','aria-label','placeholder',...(root.matches('optgroup')?['label']:[])].forEach(a=>{if(root.hasAttribute(a)){const v=root.getAttribute(a),t=translate(v);if(t!==v)root.setAttribute(a,t);}});
Array.from(root.childNodes).forEach(walk);}
function start(){if(window.RDI18n)RDI18n.setLang('ko');document.documentElement.lang='ko';walk(document.body);
const obs=new MutationObserver(records=>{for(const rec of records){if(rec.type==='characterData')walk(rec.target);else if(rec.type==='attributes')walk(rec.target);else rec.addedNodes.forEach(walk);}});
obs.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder','label']});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
window.RDV2Korean={translate};
})();