#!/bin/bash
# install_daemon.command v0.2 — Python 3.9+ 허용 (deploy-only mode)
# (v0.1 → v0.2 패치: Python detection 완화 + 시스템 Python 버전 다 보여줌)
#
# 더블클릭 1회로 daemon 셋업 완료. 단계:
#   1. Python 3.10+ 확인
#   2. ~/dev/orchestrator/ 로 코드 복사 (iCloud 밖)
#   3. Python venv 생성 + 의존성 설치
#   4. ~/.config/orchestrator/.env 생성 (deploy-only mode)
#   5. ~/Library/LaunchAgents/com.dmj.orchestrator.plist 설치 + 로드
#   6. 30초 polling 시작 확인 + 첫 heartbeat 보고

set -u

# --- repo root ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -d "$SCRIPT_DIR/src" ]; then SRC_ORCH="$SCRIPT_DIR"
elif [ -d "$SCRIPT_DIR/orchestrator/src" ]; then SRC_ORCH="$SCRIPT_DIR/orchestrator"
else echo "ERROR: orchestrator/src 못 찾음"; read -n 1; exit 1; fi

SITE_REPO="$(dirname "$SRC_ORCH")"
INSTALL_DIR="$HOME/dev/orchestrator"
CONFIG_DIR="$HOME/.config/orchestrator"
LOG_DIR="$HOME/Library/Logs/Orchestrator"
LAUNCHAGENT="$HOME/Library/LaunchAgents/com.dmj.orchestrator.plist"

echo "==> source orchestrator/: $SRC_ORCH"
echo "==> site/ repo: $SITE_REPO"
echo "==> install 위치: $INSTALL_DIR (iCloud 밖)"

# --- 1. Python 찾기 (deploy-only 는 3.9+, full mode 는 3.10+ 필요) ---
echo ""
echo "==> [1/5] Python 탐색 중..."
echo "    시스템에서 찾은 Python:"
for cand in python3.13 python3.12 python3.11 python3.10 python3.9 python3 \
            /opt/homebrew/bin/python3 /opt/homebrew/bin/python3.13 /opt/homebrew/bin/python3.12 \
            /opt/homebrew/bin/python3.11 /opt/homebrew/bin/python3.10 \
            /usr/local/bin/python3 /usr/bin/python3; do
  if command -v "$cand" >/dev/null 2>&1; then
    REAL=$(command -v "$cand" 2>/dev/null)
    VER=$("$cand" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}.{sys.version_info[2]}")' 2>/dev/null)
    [ -n "$VER" ] && echo "      $cand → $REAL (Python $VER)"
  fi
done

# 최고 버전 선택 — 3.10+ 우선, 없으면 3.9 도 OK (deploy-only mode)
PY=""
PY_VER=""
PY_MINOR=0
for cand in python3.13 python3.12 python3.11 python3.10 python3.9 python3 \
            /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do
  if command -v "$cand" >/dev/null 2>&1; then
    VER=$("$cand" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")' 2>/dev/null)
    if [ -n "$VER" ]; then
      MAJOR=$(echo "$VER" | cut -d. -f1)
      MINOR=$(echo "$VER" | cut -d. -f2)
      if [ "$MAJOR" -ge 3 ] && [ "$MINOR" -ge 9 ]; then
        # 최소 3.9, 최고 버전 선호
        if [ "$MINOR" -gt "$PY_MINOR" ]; then
          PY="$cand"
          PY_VER="$VER"
          PY_MINOR="$MINOR"
        fi
      fi
    fi
  fi
done

if [ -z "$PY" ]; then
  echo ""
  echo "ERROR: Python 3.9 이상 없음."
  if command -v brew >/dev/null 2>&1; then
    echo "       해결: 터미널에서 'brew install python@3.11' 실행 후 다시 더블클릭."
  else
    echo "       Homebrew 도 없음. 먼저 https://brew.sh 에서 brew 설치 후"
    echo "       'brew install python@3.11' 실행 → 다시 더블클릭."
  fi
  read -n 1; exit 1
fi

echo ""
echo "    채택: $PY (Python $PY_VER)"
if [ "$PY_MINOR" -lt 10 ]; then
  echo "    ⚠️  Python 3.10 미만 — deploy-only mode 만 동작."
  echo "       Full mode (claude-agent-sdk) 는 3.10+ 필요. 추후 'brew install python@3.11' 권장."
  PYTHON_DEPLOY_ONLY=1
else
  PYTHON_DEPLOY_ONLY=0
fi

# --- 2. 코드 복사 ---
echo ""
echo "==> [2/5] $INSTALL_DIR 로 코드 복사 (iCloud 밖)..."
mkdir -p "$INSTALL_DIR"
# rsync: __pycache__ / .venv / __pycache__ 제외, 신규/변경만
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete \
    --exclude '__pycache__' --exclude '*.pyc' \
    --exclude '.venv' --exclude 'venv' \
    --exclude '.DS_Store' \
    "$SRC_ORCH/" "$INSTALL_DIR/"
else
  cp -R "$SRC_ORCH/" "$INSTALL_DIR/"
  find "$INSTALL_DIR" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null
fi
echo "    복사 완료."

# --- 3. venv + 의존성 ---
echo ""
echo "==> [3/5] Python venv + 의존성 설치..."
cd "$INSTALL_DIR"
if [ ! -d .venv ]; then
  "$PY" -m venv .venv || { echo "ERROR: venv 생성 실패"; read -n 1; exit 1; }
fi
./.venv/bin/pip install --quiet --upgrade pip 2>/dev/null || true

if [ "$PYTHON_DEPLOY_ONLY" = "1" ]; then
  echo "    Python 3.9 → deploy-only mode 만 동작. 의존성 설치 skip (stdlib 만 사용)."
else
  if ! ./.venv/bin/pip install --quiet -r requirements.txt; then
    echo "WARN: 일부 의존성 설치 실패. deploy-only mode 는 stdlib 만으로 OK 라 계속 진행."
  fi
fi
echo "    venv: $INSTALL_DIR/.venv"

# --- 4. .env 생성 ---
echo ""
echo "==> [4/5] $CONFIG_DIR/.env 생성..."
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
ENV_FILE="$CONFIG_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  echo "    기존 $ENV_FILE 발견 — 보존 (덮어쓰지 않음)."
else
  cat > "$ENV_FILE" <<EOF
# Auto-generated by install_daemon.command on $(date -u +%FT%TZ)
# deploy-only mode (default) — API key 불필요
ENABLE_DIRECTIVE_LOOP=false

# 자동 push 대상 (단무지공방 site)
AUTO_DEPLOY_REPOS=$SITE_REPO

# Tuning
POLL_INTERVAL_SECONDS=30
WORKSPACE_DIR=$HOME/dev/orchestrator-workspace
LOG_DIR=$LOG_DIR
EOF
  chmod 600 "$ENV_FILE"
  echo "    생성됨 (chmod 600)."
fi

mkdir -p "$HOME/dev/orchestrator-workspace" "$LOG_DIR"

# --- 5. launchd plist ---
echo ""
echo "==> [5/5] launchd plist 설치..."
mkdir -p "$HOME/Library/LaunchAgents"
SRC_PLIST="$INSTALL_DIR/launchd/com.dmj.orchestrator.plist"
if [ ! -f "$SRC_PLIST" ]; then
  echo "ERROR: $SRC_PLIST 없음"; read -n 1; exit 1
fi
sed -e "s|/Users/dannyok/dev/orchestrator|$INSTALL_DIR|g" \
    -e "s|/Users/dannyok/Library/Logs/Orchestrator|$LOG_DIR|g" \
    "$SRC_PLIST" > "$LAUNCHAGENT"

# unload 가능하면 unload (기존 실행 중일 경우)
launchctl unload "$LAUNCHAGENT" 2>/dev/null || true
if ! launchctl load "$LAUNCHAGENT"; then
  echo "ERROR: launchctl load 실패. $LOG_DIR/launchd.err.log 확인."
  read -n 1; exit 1
fi
echo "    설치 + load 완료: $LAUNCHAGENT"

# --- 6. 작동 확인 ---
echo ""
echo "==> daemon 시작 대기 (5초)..."
sleep 5
STATUS=$(launchctl list | grep com.dmj.orchestrator | awk '{print $1}')
if [ -z "$STATUS" ] || [ "$STATUS" = "-" ]; then
  echo "WARN: daemon 이 아직 시작 안 됐거나 실패. 로그 확인:"
  echo "      tail -20 $LOG_DIR/orchestrator.log"
  echo "      tail -20 $LOG_DIR/launchd.err.log"
else
  echo "==> daemon PID: $STATUS ← 실행 중 ✓"
fi

echo ""
echo "==> 첫 로그 (있으면):"
sleep 2
tail -5 "$LOG_DIR/orchestrator.log" 2>/dev/null | sed 's/^/    /' || echo "    (아직 로그 없음 — 정상, 30초 내 첫 polling)"

echo ""
echo "==> 셋업 완료!"
echo ""
echo "   • 실시간 로그:   tail -f $LOG_DIR/orchestrator.log"
echo "   • daemon 상태:   launchctl list | grep com.dmj.orchestrator"
echo "   • 중지:          launchctl unload $LAUNCHAGENT"
echo "   • 시작:          launchctl load   $LAUNCHAGENT"
echo "   • 설정 파일:     $ENV_FILE"
echo ""
echo "   이제부터: site/ 안에 변경 → 30초 안에 자동 push."
echo "   더블클릭조차 불필요."
echo ""
read -n 1 -p "Press any key to close..."
