(function(){'use strict';const $=id=>document.getElementById(id),edit=$('customer-edit-form'),review=$('stock-review-form');let state=null,epoch=0,request=null,requestBody='';
const outcomes={available:'판매 재고 반영',hold:'판매 보류',returned:'반품 완료',missing:'현물 확인 필요'},states={awaiting_payment:'입금 대기',paid:'입금 확인',ordered:'발주 완료',received:'입고 완료',shipped:'출고 완료',cancelled:'취소'};
function node(tag,text){const el=document.createElement(tag);el.textContent=text;return el}
function customers(){const body=$('customer-rows');body.replaceChildren();if(!state)return;const query=$('customer-search').value.toLowerCase().trim();for(const r of state.customers.filter(r=>[r.display_name,r.email,r.phone].join(' ').toLowerCase().includes(query))){const tr=document.createElement('tr');for(const key of ['display_name','email','phone','service_note'])tr.append(node('td',r[key]||'—'));const td=node('td',''),b=node('button','상세·수정');b.type='button';b.onclick=()=>openCustomer(r);td.append(b);tr.append(td);body.append(tr)}}
function openCustomer(r){if(!state)return;edit.reset();for(const [field,key] of [['id','id'],['expected','updated_at'],['display_name','display_name'],['email','email'],['phone','phone'],['note','service_note']])edit.elements[field].value=r[key]||'';edit.querySelector('[role=status]').textContent='';const history=state.history.filter(h=>h.contact_id===r.id),orders=state.orders.filter(o=>o.contact_id===r.id),paid=orders.filter(o=>['paid','ordered','received','shipped'].includes(o.status));$('customer-summary').textContent=`기존 이력 ${history.length}건 · 신규 주문 ${orders.length}건 · 확인된 입금 주문 ${paid.reduce((n,o)=>n+Number(o.total_krw),0).toLocaleString('ko-KR')}원 · ${r.auth_user_id?'회원 계정 연결됨':'회원 계정 미연결'}`;const a=$('customer-history-preview'),b=$('customer-orders-preview');a.replaceChildren();b.replaceChildren();for(const h of history.sort((a,b)=>(b.sale_date||'').localeCompare(a.sale_date||'')))a.append(node('p',`${h.sale_date||'판매일 미기재'} · ${h.model} ${h.size} · ${h.sku} · ${h.quantity}개 · ${h.purchase_amount_krw===null?'금액 미기재':Number(h.purchase_amount_krw).toLocaleString('ko-KR')+'원'}`));if(!history.length)a.append(node('p','기존 구매·교체 기록이 없습니다.'));for(const o of orders)b.append(node('p',`${states[o.status]||o.status} · ${Number(o.total_krw).toLocaleString('ko-KR')}원 · ${o.id}`));if(!orders.length)b.append(node('p','신규 주문이 없습니다.'));$('customer-editor').open=true;$('customer-editor').scrollIntoView({block:'start'});edit.elements.display_name.focus({preventScroll:true})}
function source(){const v=review.elements,r=state?.legacyStock.find(r=>r.id===v.legacy.value),latest=state?.verifications.filter(x=>x.legacy_id===r?.id).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];$('stock-review-source').textContent=r?`${r.model} · ${r.size} · ${r.quantity}개 · 원본 판정: ${r.disposition}${latest?' · 최근 확인: '+outcomes[latest.outcome]:''}`:'';const saleable=v.outcome.value==='available';$('stock-review-saleable').hidden=!saleable;for(const k of ['sku','product','variant','tag'])v[k].required=saleable}
review.elements.legacy.onchange=()=>{const r=state?.legacyStock.find(r=>r.id===review.elements.legacy.value);if(r){review.elements.sku.value=r.sku;review.elements.variant.value=r.model+' · '+r.size;review.elements.product.value='';review.elements.product.readOnly=false;$('review-product-choice').value='';$('review-variant-options').replaceChildren();review.elements.tag.value=r.serial_number||''}source()};review.elements.outcome.onchange=source;
$('review-product-choice').onchange=()=>{const value=$('review-product-choice').value,p=state?.catalog.products.find(p=>p.id===value);review.elements.product.value=p?.id||'';review.elements.product.readOnly=!!p;$('review-variant-options').replaceChildren(...(p?.retailVariants?.map(r=>r.option)||p?.options||[]).map(v=>new Option(v,v)));if(p)review.elements.variant.value='';};
$('customer-search').oninput=customers;
window.addEventListener('dmj-ops-data',e=>{state=e.detail;customers();const productSelect=$('review-product-choice'),productValue=productSelect.value;productSelect.replaceChildren(new Option('기존 연식·카탈로그 외 제품 직접 입력',''));for(const p of state.catalog.products)productSelect.add(new Option(p.brand+' · '+p.name,p.id));productSelect.value=productValue;const select=review.elements.legacy,value=select.value;select.replaceChildren(new Option('기존 재고 선택',''));for(const r of state.legacyStock){const done=state.verifications.some(v=>v.legacy_id===r.id&&v.outcome==='available');if(!done)select.add(new Option(r.sku+' · '+r.model+' · '+r.disposition,r.id))}select.value=value;source()});
function clear(){epoch++;state=null;request=null;requestBody='';edit.reset();review.reset();review.elements.product.readOnly=false;$('review-variant-options').replaceChildren();$('customer-search').value='';$('customer-editor').open=false;for(const id of ['customer-rows','customer-summary','customer-history-preview','customer-orders-preview','stock-review-source'])$(id).replaceChildren();review.elements.legacy.replaceChildren(new Option('관리자 연결 후 선택',''));for(const form of [edit,review])form.querySelector('[role=status]').textContent='';source()}
window.addEventListener('dmj-auth-change',clear);window.addEventListener('dmj-ops-unavailable',clear);
async function run(form,method,p){const status=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]');if(!state){status.textContent='관리자 연결이 필요합니다.';return false}const generation=epoch,sb=state.client,owner=state.owner;button.disabled=true;try{const r=await sb.rpc(method,p);if(generation!==epoch)return false;if(r.error)throw Error(r.error.message);const auth=await sb.auth.getUser();if(generation!==epoch||auth.data.user?.id!==owner)return false;status.textContent='운영 DB에 저장했습니다.';$('refresh').click();return true}catch(err){if(generation===epoch)status.textContent='저장 실패: '+err.message;return false}finally{button.disabled=false}}
edit.onsubmit=async e=>{e.preventDefault();const v=edit.elements,ok=await run(edit,'ops_update_customer',{p_id:v.id.value,p_expected:v.expected.value,p_name:v.display_name.value,p_email:v.email.value,p_phone:v.phone.value,p_note:v.note.value});if(ok)$('customer-editor').open=false};
review.onsubmit=async e=>{e.preventDefault();const v=review.elements,r=state?.legacyStock.find(r=>r.id===v.legacy.value);if(!r)return;const p={p_legacy:r.id,p_outcome:v.outcome.value,p_quantity:v.outcome.value==='available'?r.quantity:0,p_sku:v.sku.value,p_product:v.product.value,p_variant:v.variant.value,p_tag:v.tag.value,p_note:v.note.value,p_confirm:v.confirm.checked},body=JSON.stringify(p);if(body!==requestBody){request=crypto.randomUUID();requestBody=body}if(await run(review,'ops_verify_legacy_stock',{p_id:request,...p})){request=null;requestBody='';review.reset();review.elements.product.readOnly=false;$('review-variant-options').replaceChildren();source()}};
})();
