(function(){'use strict';
const $=id=>document.getElementById(id),form=$('campaign-form'),f=form.elements;let state=null,epoch=0,productChoices=[],renderSignature='';
const labels={draft:'초안',review:'검수 중',ready:'게시 준비 완료',published:'게시 확인',paused:'보류'},channels={instagram:'인스타그램',band:'밴드',youtube:'유튜브',facebook:'페이스북'};
const money=n=>Number(n).toLocaleString('ko-KR')+'원';
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function action(host,text,fn){const b=el('button',text);b.type='button';b.onclick=fn;host.append(b)}
function link(host,text,url){const a=el('a',text);a.href=url;a.target='_blank';a.rel='noopener';host.append(a)}
function metrics(){const host=$('campaign-metrics');host.replaceChildren();if(!state)return;const linked=state.inquiries.filter(i=>i.campaign_id),ids=new Set(linked.map(i=>i.id)),paid=state.orders.filter(o=>ids.has(o.inquiry_id)&&['paid','ordered','received','shipped'].includes(o.status));for(const [title,value] of [['게시 확인',state.campaigns.filter(c=>c.status==='published').length+'건'],['게시 준비',state.campaigns.filter(c=>!['published','paused'].includes(c.status)).length+'건'],['연결된 회원 상담',linked.length+'건'],['연결된 입금 주문액',money(paid.reduce((n,o)=>n+Number(o.total_krw),0))]]){const card=el('div',undefined,'card');card.append(el('strong',value),el('div',title));host.append(card)}}
function render(){metrics();const signature=JSON.stringify([state?.campaigns,state?.inquiries,state?.orders,$('campaign-channel').value]);if(signature===renderSignature)return;renderSignature=signature;const host=$('campaign-list');host.replaceChildren();if(!state){host.append(el('p','관리자 연결 확인 후 홍보 계획이 표시됩니다.'));return}const selected=$('campaign-channel').value,rows=state.campaigns.filter(c=>selected==='all'||c.channel===selected).sort((a,b)=>(a.planned_at||'9999').localeCompare(b.planned_at||'9999'));if(!rows.length)host.append(el('p','이 채널에 등록된 홍보 계획이 없습니다.'));for(const c of rows){const card=el('article',undefined,'campaign-card'),badge=el('span',labels[c.status],'campaign-state');badge.dataset.status=c.status;const leads=state.inquiries.filter(i=>i.campaign_id===c.id),ids=new Set(leads.map(i=>i.id)),paid=state.orders.filter(o=>ids.has(o.inquiry_id)&&['paid','ordered','received','shipped'].includes(o.status));card.append(badge,el('h3',c.title),el('p',channels[c.channel]+' · '+(c.planned_at?new Date(c.planned_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'일정 미정'),'hint'),el('p',c.caption,'caption'));const buttons=el('div',undefined,'card-actions'),feedback=el('p','','copy-feedback');feedback.setAttribute('role','status');action(buttons,'내용 편집',()=>edit(c));action(buttons,'문안·홍보 링크 복사',async()=>{try{await navigator.clipboard.writeText(c.caption+'\n\n'+DMJCommerce.campaignUrl(c.target_path,c.channel,c.slug));feedback.textContent='복사했습니다. 공개 사이트 확인 후 게시해 주세요.'}catch(e){feedback.textContent='복사하지 못했습니다. 링크: '+DMJCommerce.campaignUrl(c.target_path,c.channel,c.slug)}});link(buttons,'제품 미리보기','..'+c.target_path);if(c.published_url)link(buttons,'게시물 보기',c.published_url);card.append(buttons,feedback);if(c.media_key){const detail=el('details'),summary=el('summary','30초 영상 검토본'),video=document.createElement('video');video.controls=true;video.preload='none';video.playsInline=true;video.src='../assets/media/promotions/'+c.media_key+'.mp4';detail.append(summary,video,el('p','제품 사진·자막 중심의 무음 초안입니다.','hint'));card.append(detail)}card.append(el('p',`상담 ${leads.length}건 · 입금 ${paid.length}건 · ${money(paid.reduce((n,o)=>n+Number(o.total_krw),0))}`,'campaign-stat'));host.append(card)}}
function localDate(value){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function edit(c){if(!state)return;form.reset();form.querySelector('[role=status]').textContent='';f.id.value=c?.id||crypto.randomUUID();f.expected.value=c?.updated_at||'';for(const k of ['title','business','product_id','slug','caption','channel','media_key','status','published_url'])f[k].value=c?.[k]??({business:'DMJ',channel:'instagram',status:'draft',product_id:productChoices[0]?.id}[k]||'');if(c?.product_id==='')f.product_id.value='__catalog';f.planned_at.value=localDate(c?.planned_at);f.channel.disabled=!!c;f.slug.readOnly=!!c;for(const k of ['facts','rights','destination'])f[k].checked=c?.checks?.[k]===true;$('campaign-editor').open=true;$('campaign-editor').scrollIntoView({behavior:'auto',block:'start'});f.title.focus({preventScroll:true})}
$('campaign-new').onclick=()=>edit(null);$('campaign-channel').onchange=render;
window.addEventListener('dmj-ops-data',e=>{state=e.detail;const signature=state.catalog.products.map(p=>p.id).join('|');if(f.product_id.dataset.signature!==signature){const previous=f.product_id.value;productChoices=[...state.catalog.products,{id:'',name:'전체 장비',brand:'DMJ',path:'catalog.html'}];f.product_id.replaceChildren(...productChoices.map(p=>new Option(p.brand+' · '+p.name,p.id||'__catalog')));f.product_id.dataset.signature=signature;if(previous)f.product_id.value=previous}render()});
function clear(){epoch++;state=null;renderSignature='';form.reset();f.id.value='';f.expected.value='';f.channel.disabled=false;f.slug.readOnly=false;form.querySelector('[role=status]').textContent='';$('campaign-editor').open=false;render()}
window.addEventListener('dmj-auth-change',clear);window.addEventListener('dmj-ops-unavailable',clear);
form.addEventListener('submit',async e=>{e.preventDefault();const message=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]');if(!state){message.textContent='관리자 연결을 먼저 확인해 주세요.';return}const current=epoch,sb=state.client,owner=state.owner;button.disabled=true;try{const product=productChoices.find(p=>(p.id||'__catalog')===f.product_id.value);if(!product)throw Error('연결 제품을 선택해 주세요.');const details={title:f.title.value.trim(),business:f.business.value,product_id:product.id,target_path:'/'+product.path.replace(/^\//,''),channel:f.channel.value,slug:f.slug.value,caption:f.caption.value,media_key:f.media_key.value,status:f.status.value,published_url:f.published_url.value.trim(),planned_at:f.planned_at.value?new Date(f.planned_at.value).toISOString():null,checks:Object.fromEntries(['facts','rights','destination'].map(k=>[k,f[k].checked]))};const r=await sb.rpc('ops_save_campaign',{p_id:f.id.value,p_expected:f.expected.value||null,p_details:details});if(current!==epoch)return;if(r.error)throw Error(r.error.message);const auth=await sb.auth.getUser();if(current!==epoch||auth.data.user?.id!==owner)return;message.textContent='서버에 저장했습니다. 외부 채널에 게시한 것은 아닙니다.';f.expected.value='';f.id.value='';$('campaign-editor').open=false;$('refresh').click()}catch(err){if(current===epoch)message.textContent='저장 실패: '+err.message+' · 다른 화면에서 변경했다면 목록을 새로 확인한 뒤 편집해 주세요.'}finally{button.disabled=false}});
render();})();
