(function(){'use strict';const $=id=>document.getElementById(id);let running=false,refreshQueued=false,client=null,inventory=[],moveId=null,movePayload='',authGeneration=0,historyRows=[],historyNames=new Map(),taskRows=[];
function item(host,text){const li=document.createElement('li');li.textContent=text;host.append(li)}
function metric(label,value){const card=document.createElement('div');card.className='card';const n=document.createElement('strong');n.textContent=value;card.append(n,document.createElement('br'),document.createTextNode(label));$('metrics').append(card)}
function table(id,rows,cols){const body=$(id),matrix=rows.map(row=>cols.map(c=>typeof c==='function'?c(row):(row[c]??'—'))),signature=JSON.stringify(matrix);if(body.childElementCount&&body.dataset.rows===signature)return;body.dataset.rows=signature;body.replaceChildren();for(const cells of matrix){const tr=document.createElement('tr');for(const value of cells){const td=document.createElement('td');td.textContent=value;tr.append(td)}body.append(tr)}}
async function all(t){let rows=[];for(let from=0;from<10000;from+=500){const r=await client.from(t).select('*').order(t==='ops_inventory'?'sku':'id').range(from,from+499);if(r.error)throw Error(t+' 조회 실패');rows.push(...r.data);if(r.data.length<500)return rows}throw Error('조회 한도 초과: 전체 집계 미완료')}
async function refresh(){if(running){refreshQueued=true;return}running=true;const generation=authGeneration;client=null;$('stock-submit').disabled=true;try{
const catalog=await fetch('../data/commerce.json',{cache:'no-store'}).then(r=>r.json());
const productNames=new Map(catalog.products.map(p=>[p.id,(catalog.brands[p.brand]?.name||p.brand)+' · '+p.name]));const productLabel=id=>productNames.get(id)||(id?.startsWith('outlet-')?'아울렛 · '+(inventory.find(r=>r.product_id===id)?.variant||'등록 상품'):id)||'일반 상담';
const missing=catalog.products.filter(p=>!p.price),estimated=catalog.products.filter(p=>p.priceStatus==='estimate');
await DMJAuth._ensureClient();const sb=DMJAuth._supabase();const user=await sb.auth.getUser();if(user.error||!user.data.user)throw Error('관리자 로그인이 필요합니다');const owner=user.data.user.id;const check=await sb.rpc('is_ops_admin');if(check.error||check.data!==true)throw Error('관리자 DB 미연결 또는 관리자 권한 미확인');client=sb;
const [inv,orders,tasks,events,inquiries,customers,legacyStock,history,campaigns,orderLines,verifications]=await Promise.all(['ops_inventory','ops_orders','ops_tasks','ops_events','ops_inquiries','ops_customers','ops_legacy_inventory','ops_purchase_history','ops_campaigns','ops_order_lines','ops_stock_verifications'].map(all));const current=await sb.auth.getUser();if(generation!==authGeneration||current.data.user?.id!==owner)throw Error('계정이 변경되어 조회를 중단했습니다');inventory=inv;$('work-status').replaceChildren();tasks.filter(t=>t.status==='done'||t.status==='blocked').forEach(t=>item($('work-status'),t.title+' — '+({done:'완료',blocked:'확인 필요'}[t.status])+' · '+(t.blocker||'')));['actions','events','metrics'].forEach(id=>$(id).replaceChildren());metric('확정가 / 예상가 / 확인 필요',`${catalog.products.length-missing.length-estimated.length} / ${estimated.length} / ${missing.length}`);item($('actions'),`가격 확인: ${estimated.length}개 모델 예상가 표시 · ${missing.length}개 모델 가격 미확인. 예상가는 주문 확정가가 아닙니다.`);window.dispatchEvent(new CustomEvent('dmj-ops-data',{detail:{client:sb,campaigns,inquiries,orders,catalog,owner,customers,legacyStock,history,verifications,tasks,inventory:inv}}));
let inbox=$('inquiry-inbox');if(!inbox){inbox=document.createElement('section');inbox.id='inquiry-inbox';$('metrics').before(inbox)}inbox.replaceChildren();const pending=inquiries.filter(i=>i.status==='new').sort((a,b)=>b.created_at.localeCompare(a.created_at));const heading=document.createElement('h2');heading.textContent='새 문의 '+pending.length+'건';inbox.append(heading);for(const i of pending.slice(0,20)){const card=document.createElement('article');card.className='card';const title=document.createElement('h3');title.textContent=productLabel(i.product_id)+' · '+new Date(i.created_at).toLocaleString('ko-KR');const body=document.createElement('p');body.style.whiteSpace='pre-wrap';body.textContent='사이즈: '+(i.size||'상담 필요')+'\n경험: '+(i.experience||'미입력')+'\n타는 곳·장비: '+(i.setup||'미입력')+'\n문의: '+(i.note||'별도 내용 없음');const link=document.createElement('a');link.href='#inquiry-status-form';link.textContent='응대 상태 관리 →';card.append(title,body,link);inbox.append(card)}
$('connection').textContent='운영 DB 연결됨 · 30초마다 갱신';metric('확정된 판매 가능 재고',inv.length?inv.reduce((n,r)=>n+r.on_hand-r.reserved,0)+'개':'실사 전 · 미확정');metric('응대 대기 상담',inquiries.filter(r=>r.status==='new').length+'건');metric('입금 확인 이후 주문액',orders.filter(r=>['paid','ordered','received','shipped'].includes(r.status)).reduce((n,r)=>n+Number(r.total_krw),0).toLocaleString('ko-KR')+'원');
DMJOps.alerts({inventory:inv,orders,tasks,inquiries,campaigns}).forEach(r=>item($('actions'),(r.priority===1?'우선 · ':'')+r.text));const unread=events.filter(r=>!r.read_at).sort((a,b)=>b.created_at.localeCompare(a.created_at));unread.slice(0,40).forEach(r=>{const li=document.createElement('li');li.textContent=r.summary.replace(/ · (draft|review|ready|published|paused)$/,(_,v)=>' · '+({draft:'초안',review:'검수 중',ready:'게시 준비 완료',published:'게시 확인',paused:'보류'}[v]))+' ';const b=document.createElement('button');b.textContent='확인';b.onclick=async()=>{b.disabled=true;const res=await sb.from('ops_events').update({read_at:new Date().toISOString()}).eq('id',r.id);if(res.error){b.disabled=false;return}refresh()};li.append(b);$('events').append(li)});if(!unread.length)item($('events'),'미확인 알림 없음');
fillChoices($('order-form').elements.contact,customers,r=>r.display_name+(r.phone?' · '+r.phone:''));const customerNames=new Map(customers.map(r=>[r.id,r.display_name]));historyRows=history;historyNames=customerNames;renderHistory();table('legacy-stock-rows',legacyStock.slice().sort((a,b)=>a.disposition.localeCompare(b.disposition)||a.sku.localeCompare(b.sku)),['sku','model','size','quantity','disposition','location','review_note',r=>{const v=verifications.filter(v=>v.legacy_id===r.id).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];return v?({available:'판매 재고 반영',hold:'판매 보류',returned:'반품 완료',missing:'현물 확인 필요'}[v.outcome])+' · '+new Date(v.created_at).toLocaleDateString('ko-KR'):'미확인'}]);metric('기존 고객 목록',customers.length+'명');metric('실사 전 재고 기록',legacyStock.reduce((n,r)=>n+r.quantity,0)+'개');
const stateLabels={todo:'예정',doing:'진행',blocked:'확인 필요',done:'완료',new:'응대 대기',contacted:'응대 중',closed:'상담 종료',awaiting_payment:'입금 대기',paid:'입금 확인',ordered:'공급사 발주',received:'입고 완료',shipped:'출고 완료',cancelled:'취소'};
taskRows=tasks;renderTasks();
fillChoices($('inquiry-status-form').elements.inquiry,inquiries,r=>productLabel(r.product_id)+' · '+new Date(r.created_at).toLocaleString('ko-KR')+' · '+(r.note||'').slice(0,35));
const selectedProduct=new URLSearchParams(location.search).get('product'),selectedRows=selectedProduct?inv.filter(r=>r.product_id===selectedProduct):inv;const knownProduct=selectedProduct&&productNames.has(selectedProduct);$('stock-show-all').hidden=!selectedProduct;$('stock-product-context').textContent=selectedProduct?(knownProduct?productLabel(selectedProduct):'등록되지 않은 제품')+(selectedRows.length?' · '+selectedRows.length+'개 옵션':' · 등록된 재고 품목이 없습니다. 아래 품목 등록에서 SKU와 옵션을 등록해 주세요.'):'전체 제품 재고';if(knownProduct){$('sku-form').elements.product.value=selectedProduct;if(selectedRows.length===1&&!$('stock-form').elements.sku.value)$('stock-form').elements.sku.value=selectedRows[0].sku;}table('inventory-rows',selectedRows,[r=>productLabel(r.product_id),'sku','variant','on_hand','reserved',r=>r.on_hand-r.reserved,'inbound','eta']);table('order-rows',orders,['id',r=>customerNames.get(r.contact_id)||r.customer_id||'미지정',r=>stateLabels[r.status]||r.status,r=>Number(r.total_krw).toLocaleString('ko-KR'),r=>orderLines.filter(l=>l.order_id===r.id).map(l=>l.sku+' · '+l.quantity+'개 · 개당 '+Number(l.unit_price_krw).toLocaleString('ko-KR')+'원').join(' / '),'payment_due_at','eta','inquiry_id']);table('inquiry-rows',inquiries.sort((a,b)=>b.created_at.localeCompare(a.created_at)),['created_at','user_id',r=>productLabel(r.product_id),'size','experience','setup','note',r=>{const c=campaigns.find(c=>c.id===r.campaign_id);return c?c.title+' · '+c.channel:'기록 없음'},r=>stateLabels[r.status]||r.status]);
fillChoices($('transition-form').elements.order,orders,r=>(customerNames.get(r.contact_id)||r.customer_id||'고객 미지정')+' · '+(stateLabels[r.status]||r.status)+' · '+Number(r.total_krw).toLocaleString('ko-KR')+'원 · '+r.id);$('registered-skus').replaceChildren(...inv.map(r=>new Option(productLabel(r.product_id)+' · '+r.variant,r.sku)));fillChoices($('order-form').elements.inquiry,inquiries,r=>productLabel(r.product_id)+' · '+new Date(r.created_at).toLocaleDateString('ko-KR')+' · '+r.id);$('stock-submit').disabled=false;window.dispatchEvent(new Event('dmj-ops-rendered'));
}catch(e){client=null;inventory=[];historyRows=[];historyNames=new Map();$('registered-skus').replaceChildren();resetChoices();['inquiry-inbox','work-status','actions','events','metrics','inventory-rows','inquiry-rows','order-rows','task-rows','customer-rows','legacy-stock-rows','history-rows'].forEach(id=>$(id)?.replaceChildren());window.dispatchEvent(new Event('dmj-ops-unavailable'));$('connection').textContent=e.message+' · 운영 수치는 표시하지 않습니다';item($('events'),'방문·주문·재고 서버 연결이 확인되지 않았습니다.')}finally{$('checked').textContent='마지막 확인: '+new Date().toLocaleString('ko-KR');running=false;if(refreshQueued){refreshQueued=false;refresh()}}}
$('stock-form').addEventListener('submit',async e=>{e.preventDefault();if(!client)return;const form=e.currentTarget,v=form.elements;const p={p_sku:v.sku.value.trim(),p_movement:v.movement.value,p_quantity:Number(v.quantity.value),p_note:v.note.value.trim()};try{const row=inventory.find(r=>r.sku===p.p_sku);if(!row)throw Error('등록된 SKU를 입력해 주세요');DMJOps.stockAfter(row,p.p_movement,p.p_quantity);const serial=JSON.stringify(p);if(serial!==movePayload){movePayload=serial;moveId=crypto.randomUUID()}$('stock-submit').disabled=true;const result=await client.rpc('ops_move_stock',{p_request:moveId,...p});if(result.error)throw Error('처리 실패: '+result.error.message);$('stock-status').textContent='서버에 반영했습니다.';movePayload='';await refresh()}catch(err){$('stock-status').textContent=err.message;$('stock-submit').disabled=!client}});
function bind(id,method,build){const form=$(id);let request=null,last='';form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]')||form.querySelector('button');if(!client){status.textContent='운영 DB 연결과 관리자 로그인을 먼저 확인해 주세요.';return}try{const generation=authGeneration,p=build(form.elements),serial=JSON.stringify(p);if(serial!==last){request=crypto.randomUUID();last=serial}if(['ops_create_linked_basket','ops_register_customer'].includes(method))p.p_id=request;if(method==='ops_transition_order')p.p_request=request;button.disabled=true;const r=await client.rpc(method,p);if(generation!==authGeneration)return;if(r.error)throw Error(r.error.message);status.textContent='서버 반영 완료'+(['ops_create_linked_basket','ops_register_customer'].includes(method)?' · 접수번호 '+r.data:'');last='';await refresh()}catch(err){status.textContent='반영 실패: '+err.message}finally{button.disabled=false}})}
bind('sku-form','ops_register_sku',e=>({p_sku:e.sku.value.trim(),p_product:e.product.value.trim(),p_variant:e.variant.value.trim(),p_reorder:Number(e.reorder.value)}));
function basketLines(){return Array.from($('basket-lines').children).map(row=>({sku:row.querySelector('[data-field=sku]').value.trim(),quantity:Number(row.querySelector('[data-field=quantity]').value),unit_price_krw:Number(row.querySelector('[data-field=price]').value)}))}
function basketTotal(){const amount=basketLines().reduce((sum,row)=>sum+row.quantity*row.unit_price_krw,0);$('basket-total').textContent='주문 합계: '+(Number.isFinite(amount)?amount.toLocaleString('ko-KR'):'—')+'원 · 부가세 포함'}
function addBasketLine(){if($('basket-lines').children.length>=50)return;const row=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent='주문 제품';row.append(legend);for(const [field,label,type,min,max] of [['sku','SKU','text',null,null],['quantity','수량','number',1,1000],['price','부가세 포함 개당 판매가','number',0,100000000]]){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.dataset.field=field;input.type=type;input.required=true;if(field==='sku')input.setAttribute('list','registered-skus');if(type==='number'){input.min=min;input.max=max;input.step=1;input.value=field==='quantity'?'1':''}else input.maxLength=100;input.addEventListener('input',basketTotal);wrap.append(input);row.append(wrap)}const remove=document.createElement('button');remove.type='button';remove.textContent='삭제';remove.onclick=()=>{if($('basket-lines').children.length>1){row.remove();basketTotal()}};row.append(remove);$('basket-lines').append(row);basketTotal()}
$('basket-add').addEventListener('click',addBasketLine);addBasketLine();
bind('order-form','ops_create_linked_basket',e=>{const lines=basketLines();if(!e.contact.value&&!e.customer.value.trim()&&!e.inquiry.value)throw Error('고객 또는 회원 상담을 먼저 선택해 주세요.');if(new Set(lines.map(r=>r.sku)).size!==lines.length)throw Error('같은 SKU는 한 줄로 합쳐 주세요.');return {p_inquiry:e.inquiry.value||null,p_contact:e.contact.value||null,p_customer:e.customer.value.trim()||null,p_fulfillment:e.fulfillment.value,p_lines:lines,p_due:e.due.value?new Date(e.due.value).toISOString():null}});
bind('customer-form','ops_register_customer',e=>({p_name:e.display_name.value.trim(),p_email:e.email.value.trim(),p_phone:e.phone.value.trim(),p_note:e.note.value.trim(),p_auth_user:e.auth_user.value.trim()||null}));
bind('transition-form','ops_transition_order',e=>({p_order:e.order.value.trim(),p_status:e.status.value,p_note:e.note.value.trim()}));

function resetChoices(){for(const [form,field] of [['task-form','task'],['inquiry-status-form','inquiry'],['order-form','contact'],['order-form','inquiry'],['transition-form','order']]){const select=$(form).elements[field];select.dataset.previous=select.value||select.dataset.previous||'';select.replaceChildren(new Option('연결 확인 후 선택',''));}}
function fillChoices(select,rows,label){select.dataset.previous=select.value||select.dataset.previous||'';select.replaceChildren(new Option('선택해 주세요',''));for(const row of rows)select.add(new Option(label(row),row.id));if(rows.some(r=>r.id===select.dataset.previous))select.value=select.dataset.previous;select.dataset.previous='';}
function bindStatus(formId,tableName,field,build){const form=$(formId);form.addEventListener('submit',async e=>{e.preventDefault();const message=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]')||form.querySelector('button');if(!client){message.textContent='관리자 연결을 먼저 확인해 주세요.';return}const sb=client,generation=authGeneration;button.disabled=true;try{const result=await sb.from(tableName).update(build(form.elements)).eq('id',form.elements[field].value).select('id');if(generation!==authGeneration)return;if(result.error||result.data?.length!==1)throw Error('권한 또는 연결을 확인해 주세요.');message.textContent='저장했습니다.';await refresh()}catch(err){message.textContent='저장 실패: '+err.message}finally{button.disabled=false}})}
bindStatus('task-form','ops_tasks','task',e=>({status:e.status.value,blocker:e.blocker.value.trim()||null,updated_at:new Date().toISOString()}));
bindStatus('inquiry-status-form','ops_inquiries','inquiry',e=>({status:e.status.value}));

function renderHistory(){const query=$('history-search').value.trim().toLowerCase();const rows=historyRows.filter(r=>[historyNames.get(r.contact_id)||'',r.sku,r.model].join(' ').toLowerCase().includes(query)).sort((a,b)=>(b.sale_date||'').localeCompare(a.sale_date||''));table('history-rows',rows,[r=>historyNames.get(r.contact_id)||'미기재','receipt_type','sale_date','sku','model','size','quantity',r=>r.purchase_amount_krw===null?'미기재':Number(r.purchase_amount_krw).toLocaleString('ko-KR')+'원','original_status','review_note']);}
function renderTasks(){const labels={todo:'예정',doing:'진행',blocked:'확인 필요',done:'완료'},rows=taskRows.slice().sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||(b.updated_at||'').localeCompare(a.updated_at||''));table('task-rows',rows,[r=>({DMJ:'단무지상사',WPL:'윙포일퍼포먼스연구소',SailTechCo:'세일테코'}[r.business]||r.business),'title',r=>r.due_at?new Date(r.due_at).toLocaleString('ko-KR'):'—',r=>labels[r.status]||r.status,'blocker']);fillChoices($('task-form').elements.task,rows,r=>r.title+' · '+(labels[r.status]||r.status));$('task-list-summary').textContent='전체 '+rows.length+'건 · 진행할 업무 '+rows.filter(r=>r.status!=='done').length+'건 · 완료 '+rows.filter(r=>r.status==='done').length+'건 · 최근 변경 순';}
$('task-create-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,v=form.elements,message=form.querySelector('[role=status]'),button=form.querySelector('button');if(!client){message.textContent='관리자 연결이 필요합니다.';return}const sb=client,generation=authGeneration;button.disabled=true;try{const title=v.title.value.trim();if(!title)throw Error('업무명을 입력해 주세요.');const r=await sb.from('ops_tasks').insert({title,business:v.business.value,due_at:v.due.value?new Date(v.due.value).toISOString():null,status:v.status.value,blocker:v.blocker.value.trim()||null}).select('*').single();if(generation!==authGeneration)return;if(r.error||!r.data?.id)throw Error(r.error?.message||'저장 결과를 확인하지 못했습니다.');taskRows=[r.data,...taskRows.filter(t=>t.id!==r.data.id)];renderTasks();form.reset();message.textContent='‘'+r.data.title+'’ 업무가 저장되어 아래 목록에 표시되었습니다.';$('task-list-summary').scrollIntoView({block:'center'});await refresh()}catch(err){message.textContent='등록 실패: '+err.message}finally{button.disabled=false}});
$('history-search').addEventListener('input',renderHistory);
$('refresh').addEventListener('click',refresh);window.addEventListener('dmj-auth-change',e=>{if(e.detail?.accountChanged===false&&e.detail?.event!=='SIGNED_OUT')return;authGeneration++;taskRows=[];client=null;inventory=[];historyRows=[];historyNames=new Map();$('registered-skus').replaceChildren();$('history-search').value='';for(const form of document.querySelectorAll('form')){form.reset();form.querySelectorAll('input').forEach(input=>{if(!['number'].includes(input.type))input.value=''})}document.querySelectorAll('form [role=status]').forEach(el=>el.textContent='');['inquiry-inbox','work-status','actions','events','metrics'].forEach(id=>$(id).replaceChildren());for(const [form,field] of [['task-form','task'],['inquiry-status-form','inquiry'],['order-form','contact'],['order-form','inquiry'],['transition-form','order']]){const select=$(form).elements[field];select.value='';select.dataset.previous='';}['inventory-rows','inquiry-rows','order-rows','task-rows','customer-rows','legacy-stock-rows','history-rows'].forEach(id=>$(id).replaceChildren());refresh()});refresh();setInterval(()=>{if(!document.hidden)refresh()},30000);
})();
