(function(){'use strict';const O=DMJOutlet,$=id=>document.getElementById(id),form=$('outlet-form');let c=null,rows=[],stock={},current=null,media=[],urls={},pending=[],busy=false,dirty=false,authVersion=0;
const field=n=>form.elements[n];
function status(t){$('save-status').textContent=t}
function lock(v){busy=v;$('admin-fields').disabled=v||!c;$('outlet-new').disabled=v||!c;$('outlet-refresh').disabled=v||!c}
function localDate(x){if(!x)return '';const d=new Date(x);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function payload(){const x={id:current?.id||crypto.randomUUID(),expected_on_hand:current?stock[current.stock_sku]?.on_hand:null,media,featured:field('featured').checked,popup:field('popup').checked};for(const n of ['title','category','brand','model_year','size','condition','repairs','included','description','video_url','publication'])x[n]=field(n).value.trim();x.price_krw=Number(field('price_krw').value);x.original_price_krw=field('original_price_krw').value?Number(field('original_price_krw').value):null;for(const n of ['promo_start','promo_end'])x[n]=field(n).value?new Date(field(n).value).toISOString():null;if(x.video_url&&!O.safeURL(x.video_url).startsWith('https:'))throw Error('영상 링크는 https 주소로 입력해 주세요.');if(x.original_price_krw&&x.original_price_krw<x.price_krw)throw Error('정상가는 판매가 이상이어야 합니다.');if(x.promo_start&&x.promo_end&&x.promo_start>=x.promo_end)throw Error('홍보 종료는 시작 이후여야 합니다.');return x}
function renderMedia(){const list=$('media-list');list.replaceChildren();media.forEach((m,i)=>{const box=O.el('div'),preview=O.el(m.type==='image'?'img':'video');preview.src=urls[m.path]||m.url;if(m.type==='image')preview.alt='상품 사진 '+(i+1);else{preview.controls=true;preview.preload='metadata'}const label=O.el('p','outlet-hint',i===media.findIndex(m=>m.type==='image')?'대표 사진':m.type==='image'?'사진':'영상');box.append(preview,label);for(const [text,fn] of [['←',()=>{if(i>0)[media[i-1],media[i]]=[media[i],media[i-1]]}],['→',()=>{if(i<media.length-1)[media[i+1],media[i]]=[media[i],media[i+1]]}],['목록에서 제거',()=>media.splice(i,1)]]){const b=O.el('button','',text);b.type='button';b.setAttribute('aria-label',(i+1)+'번 '+text);b.onclick=()=>{fn();dirty=true;renderMedia()};box.append(b)}list.append(box)})}
function edit(item){if(busy)return;if(dirty&&!confirm('저장하지 않은 변경을 버리고 다른 상품을 열까요?'))return;current=item||null;media=item?item.media.map(m=>({...m})):[];pending=[];form.reset();if(item){for(const n of ['title','category','brand','model_year','size','condition','repairs','included','description','video_url','publication','price_krw','original_price_krw'])field(n).value=item[n]??'';for(const n of ['featured','popup'])field(n).checked=item[n];for(const n of ['promo_start','promo_end'])field(n).value=localDate(item[n]);field('quantity').value=stock[item.stock_sku]?.on_hand??0;$('stock-hint').textContent='SKU '+item.stock_sku+' · 예약 '+(stock[item.stock_sku]?.reserved||0)+'개 · 운영실 재고와 함께 관리됩니다.'}else{$('stock-hint').textContent='같은 모델이라도 상태가 다르면 각각 등록하세요. 저장한 수량은 운영실 재고에도 반영됩니다.'}dirty=false;status('');$('upload-status').textContent='';renderMedia();renderList()}
function renderList(){$('admin-list').replaceChildren(...rows.map(r=>{const b=O.el('button',current?.id===r.id?'selected':'',r.title+' · '+({draft:'임시저장',published:'공개',archived:'보관'}[r.publication])+' · 재고 '+(stock[r.stock_sku]?.on_hand??0));b.type='button';b.onclick=()=>edit(r);return b}))}
async function load(){const [a,b]=await Promise.all([c.from('outlet_listings').select('*').order('created_at',{ascending:false}),c.from('ops_inventory').select('sku,on_hand,reserved').like('sku','OUTLET-%')]);if(a.error||b.error)throw Error('상품·재고 목록을 불러오지 못했습니다.');rows=a.data;stock=Object.fromEntries(b.data.map(x=>[x.sku,x]));urls={...urls,...await O.signed(c,rows.flatMap(x=>x.media))};renderList()}
async function save(forceDraft=false){if(!form.reportValidity())throw Error('필수 항목을 입력해 주세요.');const x=payload();if(forceDraft)x.publication='draft';const version=authVersion;const r=await c.rpc('outlet_save_listing',{p_item:x,p_quantity:Number(field('quantity').value),p_expected_updated_at:current?.updated_at||null});if(r.error)throw Error(r.error.message||'저장하지 못했습니다.');if(version!==authVersion)throw Error('계정이 변경되었습니다. 다시 로그인해 주세요.');current=Array.isArray(r.data)?r.data[0]:r.data;stock[current.stock_sku]={on_hand:Number(field('quantity').value),reserved:stock[current.stock_sku]?.reserved||0};dirty=false;return r.data}
form.addEventListener('input',()=>{dirty=true});form.addEventListener('change',()=>{dirty=true});
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!c)return;lock(true);status('저장 중…');try{await save();await load();status(field('publication').value==='published'?'공개 완료 · 판매 페이지에 반영되었습니다.':'저장 완료 · 비공개 상태입니다.');renderList()}catch(e){status(e.message)}finally{lock(false)}});
$('media-files').addEventListener('change',async e=>{if(busy||!c)return;const files=[...e.target.files];if(!files.length)return;let imgs=media.filter(m=>m.type==='image').length,vids=media.filter(m=>m.type==='video').length;const allowed=['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm','video/quicktime'];try{for(const f of files){if(!allowed.includes(f.type))throw Error('지원하지 않는 파일 형식입니다: '+f.name);if(f.type.startsWith('image/')){imgs++;if(f.size>20*1024*1024)throw Error('사진은 한 장에 20MB 이하로 올려 주세요.')}else{vids++;if(f.size>50*1024*1024)throw Error('영상은 한 개에 50MB 이하로 올려 주세요.')}if(imgs>20||vids>3)throw Error('사진 20장, 영상 3개까지 등록할 수 있습니다.')}if(!form.reportValidity())throw Error('사진을 올리기 전에 기본 상품 정보를 입력해 주세요.');lock(true);$('upload-status').textContent='업로드 준비 중…';if(!current)await save(true);let done=0;
 for(const f of files){const ext={ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'}[f.type];const path=current.id+'/'+crypto.randomUUID()+'.'+ext;const r=await c.storage.from('outlet-media').upload(path,f,{contentType:f.type,upsert:false});if(r.error)throw Error(f.name+' 업로드 실패. 이미 추가된 파일은 유지됩니다.');const m={path,type:f.type.startsWith('image/')?'image':'video'};media.push(m);urls={...urls,...await O.signed(c,[m])};dirty=true;renderMedia();$('upload-status').textContent=(++done)+' / '+files.length+' 업로드 완료';}
 status('사진·영상을 추가했습니다. 상품 저장을 눌러 반영해 주세요.');
 }catch(err){$('upload-status').textContent=err.message}finally{e.target.value='';lock(false)}});
$('preview-button').onclick=()=>{try{if(!form.reportValidity())return;const x=payload();if(!media.some(m=>m.type==='image'))throw Error('미리 볼 사진을 추가해 주세요.');x.sale_status=Number(field('quantity').value)>0?'available':'sold';$('preview-content').replaceChildren(O.detail(x,urls,'../'));$('outlet-preview').showModal()}catch(e){status(e.message)}};$('preview-close').onclick=()=>$('outlet-preview').close();$('outlet-new').onclick=()=>edit(null);$('outlet-refresh').onclick=async()=>{if(dirty){status('수정 중인 내용을 먼저 저장하거나 새 상품을 눌러 취소해 주세요.');return}lock(true);try{await load();lock(false);if(current)edit(rows.find(r=>r.id===current.id))}catch(e){status(e.message)}finally{lock(false)}};
async function connect(){const version=++authVersion;c=null;lock(true);try{const client=await O.client(),user=await client.auth.getUser();if(!user.data.user)throw Error('관리자 로그인 후 상품을 등록할 수 있습니다.');const r=await client.rpc('is_ops_admin');if(r.error||r.data!==true)throw Error('상품 등록은 DMJ 관리자 계정으로 이용해 주세요.');if(version!==authVersion)return;c=client;await load();$('admin-login').hidden=true;$('admin-connection').textContent='관리자 연결 완료 · '+rows.length+'개 상품';lock(false)}catch(e){$('admin-connection').textContent=e.message;$('admin-login').hidden=false}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});window.addEventListener('dmj-auth-change',e=>{if(['TOKEN_REFRESHED','PROFILE_SYNCED'].includes(e.detail?.event))return;dirty=false;current=null;media=[];rows=[];urls={};form.reset();renderList();renderMedia();connect()});connect();
})();
